DROP TRIGGER DBPROD.TR_AU_RESPOSTA_AGRAVA;
DROP TRIGGER DBPROD.TR_AU_RESULTADO_AGRAVA;
DROP TRIGGER DBPROD.TR_AU_TAVERBACAO_COMPLEM_ATM;
DROP TRIGGER DBPROD.TR_AU_TDESTINO;
DROP TRIGGER DBPROD.TR_AU_TITEM_DESTINO;


CREATE TRIGGER DBPROD.TR_AU_RESPOSTA_AGRAVA 
AFTER UPDATE ON RESPOSTA_AGRAVA REFERENCING NEW AS c_new OLD AS c_old FOR EACH ROW MODE DB2SQL 
BEGIN ATOMIC 
DECLARE v_sit_trans SMALLINT DEFAULT 0;
DECLARE v_sit_averb SMALLINT DEFAULT 0;
DECLARE v_flag 		SMALLINT DEFAULT 0;
DECLARE v_gera_log 	SMALLINT DEFAULT 0;

-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
	SET v_gera_log = ( 	SELECT COUNT(*) FROM DBPROD.TAVERBACAO WHERE DAT_EMBAR >= DATE('01/02/2016') AND CTL_AVERB = c_new.ctl_averb );	
					   
	IF v_gera_log > 0 THEN					   
		SET (v_sit_trans, v_sit_averb) = ( SELECT sit_trans, sit_averb FROM DBPROD.taverbacao_indice WHERE ctl_averb = c_new.ctl_averb );
		CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, v_sit_trans, v_sit_averb, v_sit_trans, v_sit_averb, v_flag, 'TR_AU_RESPOSTA_AGRAVA');
	END IF;
	
END



CREATE TRIGGER DBPROD.TR_AU_RESULTADO_AGRAVA 
AFTER UPDATE ON RESULTADO_AGRAVA REFERENCING NEW AS c_new OLD AS c_old 
FOR EACH ROW MODE DB2SQL 
BEGIN ATOMIC 

DECLARE v_sit_trans SMALLINT DEFAULT 0;
DECLARE v_sit_averb SMALLINT DEFAULT 0;
DECLARE v_flag 		SMALLINT DEFAULT 0;
DECLARE v_gera_log 	SMALLINT DEFAULT 0;

-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
	SET v_gera_log = ( 	SELECT COUNT(*) FROM DBPROD.TAVERBACAO WHERE DAT_EMBAR >= DATE('01/02/2016') AND CTL_AVERB = c_new.ctl_averb );	
					   
	IF v_gera_log > 0 THEN	
		IF c_new.NUM_FATOR_AGR = 17 OR c_old.NUM_FATOR_AGR = 17 THEN
			SET (v_sit_trans, v_sit_averb) = ( SELECT sit_trans, sit_averb FROM DBPROD.taverbacao_indice WHERE ctl_averb = c_new.ctl_averb );
			CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, v_sit_trans, v_sit_averb, v_sit_trans, v_sit_averb, v_flag, 'TR_AU_RESULTADO_AGRAVA');
		END IF;
	END IF;	
END




CREATE TRIGGER DBPROD.TR_AU_TAVERBACAO_COMPLEM_ATM 
AFTER UPDATE ON TAVERBACAO_COMPLEM_ATM REFERENCING NEW AS c_new OLD AS c_old FOR EACH ROW MODE DB2SQL
BEGIN ATOMIC 
DECLARE v_sit_trans SMALLINT DEFAULT 0;
DECLARE v_sit_averb SMALLINT DEFAULT 0;
DECLARE v_flag 		SMALLINT DEFAULT 0;
DECLARE v_gera_log 	SMALLINT DEFAULT 0;

-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
SET v_gera_log = ( 	SELECT COUNT(*) FROM DBPROD.TAVERBACAO WHERE DAT_EMBAR >= DATE('01/02/2016') AND CTL_AVERB = c_new.ctl_averb );	
					   
IF v_gera_log > 0 THEN	
	SET (v_sit_trans, v_sit_averb) = ( SELECT sit_trans, sit_averb FROM DBPROD.taverbacao_indice WHERE ctl_averb = c_new.ctl_averb );
	CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, v_sit_trans, v_sit_averb, v_sit_trans, v_sit_averb, v_flag, 'TR_AU_TAVERBACAO_COMPLEM_ATM');
END IF;
END


CREATE TRIGGER DBPROD.TR_AU_TDESTINO 
AFTER UPDATE ON TDESTINO REFERENCING NEW AS c_new OLD AS c_old FOR EACH ROW MODE DB2SQL BEGIN ATOMIC
DECLARE v_sit_trans SMALLINT DEFAULT 0;
DECLARE v_sit_averb SMALLINT DEFAULT 0;
DECLARE v_flag 		SMALLINT DEFAULT 0;
DECLARE v_gera_log 	SMALLINT DEFAULT 0;

-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
	SET v_gera_log = ( 	SELECT COUNT(*) FROM DBPROD.TAVERBACAO WHERE DAT_EMBAR >= DATE('01/02/2016') AND CTL_AVERB = c_new.ctl_averb );	
					   
	IF v_gera_log > 0 THEN	
		SET (v_sit_trans, v_sit_averb) = ( SELECT sit_trans, sit_averb FROM DBPROD.taverbacao_indice WHERE ctl_averb = c_new.ctl_averb );
		CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, v_sit_trans, v_sit_averb, v_sit_trans, v_sit_averb, v_flag, 'TR_AU_TDESTINO');
	END IF;
END


CREATE TRIGGER DBPROD.TR_AU_TITEM_DESTINO 
AFTER UPDATE ON TITEM_DESTINO REFERENCING NEW AS c_new OLD AS c_old FOR EACH ROW MODE DB2SQL 
BEGIN ATOMIC 
DECLARE v_sit_trans SMALLINT DEFAULT 0;
DECLARE v_sit_averb SMALLINT DEFAULT 0;
DECLARE v_flag 		SMALLINT DEFAULT 0;
DECLARE v_gera_log 	SMALLINT DEFAULT 0;

-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
	SET v_gera_log = ( 	SELECT COUNT(*) FROM DBPROD.TAVERBACAO WHERE DAT_EMBAR >= DATE('01/02/2016') AND CTL_AVERB = c_new.ctl_averb );	
					   
	IF v_gera_log > 0 THEN	
		SET (v_sit_trans, v_sit_averb) = ( SELECT sit_trans, sit_averb FROM DBPROD.taverbacao_indice WHERE ctl_averb = c_new.ctl_averb 	);
		CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, v_sit_trans, v_sit_averb, v_sit_trans, v_sit_averb, v_flag, 'TR_AU_TITEM_DESTINO');
	END IF;
END


