CREATE TRIGGER DBPROD.TR_AU_TAVERBACAO_INDICE 
AFTER
UPDATE
    ON
    TAVERBACAO_INDICE REFERENCING NEW AS c_new OLD AS c_old FOR EACH ROW MODE DB2SQL
BEGIN
        ATOMIC 
DECLARE v_flag SMALLINT DEFAULT 1;

DECLARE v_gera_log SMALLINT DEFAULT 0;
-- A PARTIR DO DIA 16/11/2015, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/09/2015
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
-- A PARTIR DO DIA 22/02/2016, NÃO SERÁ MAIS GERADO LOG PARA DATAS MENORES QUE 01/02/2016
-- A PARTIR DO DIA 04/03/2016,  c_new.sit_trans not in ( 3, 9)
SET v_gera_log = ( 	SELECT COUNT(*)
					  FROM DBPROD.TAVERBACAO
					 WHERE DAT_EMBAR >= DATE('01/02/2016')
					   AND CTL_AVERB = c_new.ctl_averb );
					   
IF v_gera_log > 0 THEN	
	IF c_new.sit_trans not in ( 3, 9) THEN
		CALL BILHET.SP_BIL_INSERE_LOG( c_new.ctl_averb, c_new.sit_trans, c_new.sit_averb, c_old.sit_trans, c_old.sit_averb, v_flag, 'TR_AU_TAVERBACAO_INDICE' );
	END IF;
END IF;	
END