/*RELAÇÃO DE EMBARQUE AJUSTE NA EXIBIÇÃO DA TAXA COMERCIAL*/

SELECT 
       AI.NUM_AVERB_PAM AS NUM_AVERB_PAM
     , A.SEQ_NUMER_AVB
     , P.SEQ_NUMER_PRS  
     , A.NUM_AVERB_CLI AS NUM_AVERB_CLI     
     , A.NUM_SEQUE_AVB AS NUM_SEQUE_AVB
     , A.COD_DOCUM_EMB AS MANIFESTO
     , (SELECT COD_IDENT_VEI FROM DBPROD.AVERBACAO_VEICULO V  WHERE V.CTL_AVERB = AI.NUM_AVERB_PAM  FETCH FIRST 1 ROWS ONLY) AS PLACA     
     , TRUNC(A.DHR_EMBAR) AS DHR_EMBAR
     , P.CTL_PEJUR_CIA AS CTL_PEJUR_CIA 
     , CIA.NOM_PESSO AS NOM_PEJUR_CIA
     , P.NUM_APOLI AS NUM_APOLI
     , CLI.NOM_PESSO AS NOM_FANTS_CLI
     , AP.VLR_IS AS TOTAL_EMBARCADO
     , DECODE(AI.VLR_PAMTX, 0, '', 'PX') STATUS_PAMTAX
     , CASE WHEN LO.TIP_LOCAL IN (1, 2) THEN LO.COD_IDENT_PAD ELSE LOR.COD_IDENT_PAD END ORIGEM 
     , CASE WHEN LD.TIP_LOCAL IN (1, 2) THEN LD.COD_IDENT_PAD ELSE LDE.COD_IDENT_PAD END DESTINO
     , (SELECT TP.PCE_TARIF_PEC FROM APLBIL.BIL_RELAC_VISAO_PERCU_PADRA RP 
         INNER JOIN APLBIL.BIL_VIGEN_TARIFA_PERCURSO TP ON (RP.CTL_VIGEN_PEC = TP.CTL_VIGEN_PEC)
         WHERE RP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND RP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
         FETCH FIRST 1 ROWS ONLY
        )AS TARIFA_PADRAO
     , (SELECT RP.VLR_TARIF_PEC FROM APLBIL.BIL_RELAC_VISAO_PERCU_PADRA RP 
         INNER JOIN APLBIL.BIL_VIGEN_TARIFA_PERCURSO TP ON (RP.CTL_VIGEN_PEC = TP.CTL_VIGEN_PEC)
         WHERE RP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND RP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
         ORDER BY RP.DHR_ALTER
         FETCH FIRST 1 ROWS ONLY
       ) AS PREMIO_TARIFA
     , FAT.NUM_MES_CPT 
     ,(SELECT  CASE WHEN COUNT(ST.SEQ_NUMER_FAT)=0 THEN 'N' ELSE 'S' END TEM_COMERCIAL
           FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA  ST 
           WHERE ST.NUM_TARIF = 16 AND ST.IDT_PREMI = 'C' AND ST.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT FETCH FIRST 1 ROWS ONLY)
     , CASE WHEN A.STA_FLUVI =null THEN 'N' ELSE A.STA_FLUVI END TEM_FLUVIAL
     , (SELECT SUM(
                CASE WHEN TP.NUM_TARIF IN(36,37) THEN NVL(VC.VLR_TARIF,0.06)
                WHEN TP.NUM_TARIF IN (33,34) THEN NVL(VC.VLR_TARIF,0.00)
                ELSE  VC.VLR_TARIF END) AS TARIFA_PROPOSTA 
                FROM APLBIL.BIL_RELAC_TAXA_PROPOSTA TP
                INNER JOIN APLBIL.BIL_TIPO_TARIFA_PROPOSTA T ON (T.NUM_TARIF = TP.NUM_TARIF)
                INNER JOIN APLBIL.BIL_VIGENCIA_TAXA_CLIENTE VC ON (TP.NUM_SEQUE_TAR = VC.NUM_SEQUE_TAR)
                WHERE TP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND TP.NUM_TARIF IN (15,16,33,34,36,37)
                AND FAT.NUM_MES_CPT BETWEEN  VARCHAR_FORMAT(VC.DAT_INICI_VIG,'YYYYMM') AND VARCHAR_FORMAT(VC.DAT_FIM_VIG,'YYYYMM') --AJUSTE TAXA COMERCIAL 
       ) AS TARIFA_PROPOSTA 
     , (SELECT NVL(MAX(PROPT.VLR_TARIF_PRS),0.00) AS PREMIO_PROPOSTA
            FROM APLBIL.BIL_RELAC_VISAO_PROPT PROPT
            INNER JOIN APLBIL.BIL_RELAC_TAXA_PROPOSTA TP ON (PROPT.SEQ_NUMER_PRS = TP.SEQ_NUMER_PRS)
            WHERE PROPT.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS  AND PROPT.SEQ_NUMER_AVB =A.SEQ_NUMER_AVB                    
      ) AS PREMIO_PROPOSTA
      , CLI.COD_DOCUM_PRI AS CNPJ
      , FAT.DAT_VENCI_FAT AS VENCTO_FATURA
      , CASE WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '01' THEN 'JANEIRO' 
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '02' THEN 'FEVEREIRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '03' THEN 'MARÇO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '04' THEN 'ABRIL'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '05' THEN 'MAIO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '06' THEN 'JUNHO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '07' THEN 'JULHO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '08' THEN 'AGOSTO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '09' THEN 'SETEMBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '10' THEN 'OUTUBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '11' THEN 'NOVEMBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '12' THEN 'DEZEMBRO' END
             ||'/'||SUBSTR(FAT.NUM_MES_CPT,1,4) ||' - '||PER.NOM_PERIO AS MES_FAT
       , R.SIG_RAMO
       ,(SELECT NVL(TF.VLR_CALCU,0) FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA TF  WHERE TF.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT AND TF.NUM_TARIF = 70 FETCH FIRST 1 ROWS ONLY) QTDE_AVB
       ,(SELECT NVL(ST.VLR_CALCU,0) PREMIO FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA ST WHERE ST.NUM_TARIF = 77 AND ST.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT FETCH FIRST 1 ROWS ONLY) AS PREMIO_AVERBACAO
	   ,  AP.VLR_IS * (
	   (SELECT TP.PCE_TARIF_PEC FROM APLBIL.BIL_RELAC_VISAO_PERCU_PADRA RP 
         INNER JOIN APLBIL.BIL_VIGEN_TARIFA_PERCURSO TP ON (RP.CTL_VIGEN_PEC = TP.CTL_VIGEN_PEC)
         WHERE RP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND RP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
         FETCH FIRST 1 ROWS ONLY
        ) +  
        (SELECT SUM(
                CASE WHEN TP.NUM_TARIF IN(36,37) THEN NVL(VC.VLR_TARIF,0.06)
                WHEN TP.NUM_TARIF IN (33,34) THEN NVL(VC.VLR_TARIF,0.00)
                ELSE  VC.VLR_TARIF END) AS TARIFA_PROPOSTA 
                FROM APLBIL.BIL_RELAC_TAXA_PROPOSTA TP
                INNER JOIN APLBIL.BIL_TIPO_TARIFA_PROPOSTA T ON (T.NUM_TARIF = TP.NUM_TARIF)
                INNER JOIN APLBIL.BIL_VIGENCIA_TAXA_CLIENTE VC ON (TP.NUM_SEQUE_TAR = VC.NUM_SEQUE_TAR)
                WHERE TP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND TP.NUM_TARIF IN (15,16,33,34,36,37)
                AND FAT.NUM_MES_CPT BETWEEN  VARCHAR_FORMAT(VC.DAT_INICI_VIG,'YYYYMM') AND VARCHAR_FORMAT(VC.DAT_FIM_VIG,'YYYYMM') --AJUSTE TAXA COMERCIAL 
       ) ) /100 
       
       
       
       
FROM APLBIL.BIL_FATURA FAT
INNER JOIN APLBIL.BIL_PROPOSTA P ON (P.SEQ_NUMER_PRS = FAT.SEQ_NUMER_PRS)
INNER JOIN APLBIL.BIL_PERIODO PER ON (P.NUM_PERIO = PER.NUM_PERIO)
INNER JOIN APLBIL.BIL_RELAC_AVERB_PROPT AP ON (AP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND AP.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT)
INNER JOIN APLBIL.BIL_AVERBACAO A ON (A.SEQ_NUMER_AVB = AP.SEQ_NUMER_AVB)
INNER JOIN APLBIL.BIL_AVERBACAO_INDICE AI ON (AI.NUM_AVERB_PAM = A.NUM_AVERB_PAM)
INNER JOIN PAMAIS.V_CRP_PESSOA CIA ON (P.CTL_PEJUR_CIA = CIA.CTL_PESSO AND CIA.TIP_PESSO = 1)
INNER JOIN PAMAIS.V_CRP_PESSOA CLI ON (P.CTL_PESSO_CLI = CLI.CTL_PESSO AND CLI.TIP_PESSO = 1) 
INNER JOIN APLBIL.BIL_LOCALIDADE LO ON (LO.SEQ_NUMER_LOC = A.SEQ_LOCAL_ORI) 
LEFT JOIN APLBIL.BIL_LOCALIDADE LOR ON  (LO.SEQ_LOCAL_PAI = LOR.SEQ_NUMER_LOC) 
INNER JOIN APLBIL.BIL_LOCALIDADE LD ON (LD.SEQ_NUMER_LOC = A.SEQ_LOCAL_DES) 
LEFT JOIN APLBIL.BIL_LOCALIDADE LDE ON (LD.SEQ_LOCAL_PAI = LDE.SEQ_NUMER_LOC) 
INNER JOIN PAMAIS.V_CRP_RAMO_SEGURO  R ON (P.NUM_RAMO_SEG = R.NUM_RAMO_SEG)    
WHERE 
FAT.SEQ_NUMER_FAT = 7000260164--7000235488 --7000233224--7000207500 --7000233224--7000245767--7000260327  
  AND AP.SEQ_NUMER_FAT IS NOT NULL
  AND AP.VLR_IS <> 0
ORDER BY ORIGEM,DHR_EMBAR,NUM_AVERB_PAM            
OPTIMIZE FOR 1 ROWS WITH UR



SELECT * FROM DBPROD.TAVERBACAO t 
WHERE CTL_AVERB = 555150861








(SELECT
	CASE
		WHEN COUNT(ST.SEQ_NUMER_FAT)= 0 THEN 'N'
		ELSE 'S'
	END TEM_COMERCIAL
FROM
	APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA ST
WHERE
	ST.NUM_TARIF = 16
	AND ST.IDT_PREMI = 'C'
	AND ST.SEQ_NUMER_FAT = 7000260164 FETCH FIRST 1 ROWS ONLY)
     ,
	CASE
		WHEN A.STA_FLUVI = NULL THEN 'N'
		ELSE A.STA_FLUVI
	END
	
	
	SELECT * FROM APLBIL.BIL_AVERBACAO
	WHERE NUM_AVERB_PAM =555150861
	
	
	
	
SELECT
	DISTINCT 0 AS num_seque_ter,
	COALESCE(MT.num_contr_cga, 0) AS num_contr_cga,
	MT.num_termn,
	SUBSTR(MT.num_latit::text, 1, 10) AS num_latit,
	SUBSTR(MT.num_longi::text, 1, 10) AS num_longi,
	MT.des_event,
	MT.tip_event_ter,
	MT.sta_event,
	MT.sta_leitu,
	MT.sta_leitu_cga,
	MT.dhr_event,
	MT.dhr_alter,
	MT.dhr_inclu_cga,
	PT.nom_fants AS des_prove_tec,
	TET.sig_event_ter,
	TET.des_event_ter,
	MT.num_faixa_tem,
	FC_VERIFICA_STATUS_IGNICAO(MT.idt_ignic_vei) AS idt_ignic_vei,
	MT.cod_orign_msg,
	FG.nom_fonte_geren ,
	mt.NUM_VELOC
FROM
	supervisor.tmonitora_terminal AS mt,
	supervisor.ttipo_evento_terminal AS tet,
	pamais_prd.v_crp_provedor_tecnologia AS pt,
	tinf_fonte_gerenciadora AS fg
WHERE
	tet.tip_event_ter = mt.tip_event_ter
	AND mt.ctl_prove_ten = pt.ctl_prove_ten
	AND FG.ctl_fonte_geren = mt.ctl_fonte_geren
	AND ROUND((((EXTRACT (EPOCH FROM (SELECT oracle.SYSDATE()) - mt.dhr_event) / 86400)::NUMERIC) * 1440)::NUMERIC) <= 60
ORDER BY
	dhr_event DESC
	
	
	
	
	