
/* TIPOS DE COBERTURA [bilhet.TBIL_COBERTURA_BASICA]
 * COD  DESCRICAO 
 * 	1	AMPLA A
 *	2	RESTRITA B
 *	3	RESTRITA C
 *	4	RESTRITA B+ROUBO
 *	5	RESTRITA C+ROUBO
 *	6	AMPLA A SEM ROUBO
 *	7	AMPLA A E1
 *	8	AMPLA A S/ ROUBO E2
 *	9	RESTRITA B E2
 */

/*VERIFICAR SE O CAMPO NUM_COBER_BAS É NULO*/
SELECT SEQ_NUMER_PRS, NUM_APOLI, NUM_PROPT, NUM_COBER_BAS  FROM bilhet.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS IN( 506369, 507629)

/*UPDATE COM NUM_COBER_BAS ADEQUADO PARA APOLICE, VERIFICAR COM AREA DE PRODUTO QUAL A COBERTURA DEVE SER ATUALIZADA*/
UPDATE bilhet.TBIL_PROPOSTA SET 
NUM_COBER_BAS = 1
WHERE SEQ_NUMER_PRS = 507629

COMMIT



SELECT * FROM SEGURO.TSEG_PROPOSTA_SEGURO tps 
WHERE NUM_PROPT IN (22007746, 23003746)



