/*
BUSCA CONTAS A SEREM PROCESSADAS
*/

SELECT DISTINCT  P.NUM_RAMO_SEG,  P.NUM_PERIO_PRS,  P.NUM_APOLI,  P.COD_DOCUM_CLI,  P.NOM_PERIO_PRS, 
 P.SEQ_NUMER_PRS AS PROPOSTA,  COALESCE(NOM_FANTS_CLI || '(' || NOM_PESSO_COG || ')', NOM_FANTS_CLI) || 
CASE WHEN AJ.QTD_PARCE_SEG IS NOT NULL THEN '(AJ)' ELSE '' END AS NOM_FANTS_CLI,  P.SIG_RAMO,  P.QTD_AVERB, 
 P.VLR_EMBAR  
FROM  
V_BIL_PROPOSTA_PROCS_PENDE P 
LEFT JOIN BIL_PROPOSTA_AJUSTAVEL AJ ON AJ.SEQ_NUMER_PRS =  P.SEQ_NUMER_PRS  
WHERE NUM_MES_CPT = '202009'
AND CTL_PEJUR_CIA = 37960
 AND NUM_RAMO_SEG = 1 
 AND TIP_NEGOC = 2 
 AND NUM_PERIO_PRS = 3 
 AND NUM_APOLI > 0 
 AND QTD_AVERB > 0
 
 
 
 /*SOMPO
 CTL_PEJUR_CIA */
 37960
 
 /*CHUBB
 CTL_PEJUR_CIA*/
 17110
 
 /*MAPFRE
 CTL_PEJUR_CIA*/
 17341
