
/*LOCALIZAR FATURA NA BASE DE DADOS*/
SELECT * FROM bilhet.tbil_fatura
WHERE SEQ_NUMER_FAT IN (7000313453) --nosso numero time bilhetagem chama dessa forma

/*ENIVAR FATURA PARA O IBM */
		     UPDATE
	bilhet.TBIL_FATURA
SET
		     	CTL_GRUPO_FAT = NULL
		     	,SIT_ENVIO_FAT = 4
		     	,IDT_ENVIO_CBR = 'I'/*AJUSTE PARA QUE FATURAS ALTERADAS NO MESMO DIA SEJAM CONSIDERADAS*/
WHERE
	SEQ_NUMER_FAT in(7000321833)


COMMIT 
	
	
select * from bilhet.TBIL_CONTROLE_ENVIO_COBRANCA tcec 
WHERE SEQ_NUMER_FAT IN (
	select SEQ_NUMER_FAT  from bilhet.tbil_fatura
	WHERE DHR_ALTER BETWEEN '2024-04-30 00:00:00' AND '2024-04-30 17:05:00'
	AND NUM_FATUR_CIA IS NOT NULL 
)