/*SEGURADORAS*/
select * from PAMAIS.V_CRP_CIA_SEGURADORA
where CTL_CIA_SEGURADORA = 37960

/*FATURAS*/
SELECT SF.DES_SITUA_FAT
      ,SEF.DES_SITUA_ENV
      ,PF.NOM_PERIO_FAT
      ,MEFC.COD_TIPO_ENV
      ,TEF.DES_TIPO_ENV
      ,FEF.DES_FORMA_ENV
       ,FAT.*
FROM BILHET.TBIL_FATURA FAT
      ,BILHET.TBIL_SITUACAO_FATURA SF
      ,BILHET.TBIL_SITUACAO_ENVIO_FATURA SEF
      ,BILHET.TBIL_PERIODO_FATURA PF
      ,bilhet.tbil_modo_envio_fatura_cia MEFC
      ,bilhet.tbil_tipo_envio_fatura TEF
      ,bilhet.tbil_FORMATO_ENVIO_FATURA FEF
WHERE SF.SIT_FATUR = FAT.SIT_FATUR
AND SEF.SIT_ENVIO_FAT = FAT.SIT_ENVIO_FAT
AND PF.NUM_PERIO_FAT = FAT.NUM_PERIO_FAT
AND SEF.SIT_ENVIO_FAT = MEFC.SIT_ENVIO_FAT
AND TEF.TIP_ENVIO_FAT = MEFC.TIP_ENVIO_FAT
AND FEF.NUM_FORMA_ENV = MEFC.NUM_FORMA_ENV
--AND MEFC.SIT_ENVIO_FAT = 1
AND FAT.SEQ_NUMER_FAT IN (7000187841,7000187844)



/* ARQUIVO RETORNO FMAP*/

select TAR.NOM_ARQUI_RET
      ,RFC.* 
from bilhet.tbil_RETOR_FATURA_CIA RFC
    ,BILHET.TBIL_TIPO_ARQUI_RETORNO TAR
WHERE  TAR.NUM_ARQUI_RET = RFC.NUM_ARQUI_RET
AND RFC.SEQ_NUMER_FAT IN (7000187841,7000187844)
