/*
SELECT * FROM bilhet.tbil_relac_averb_propt b, bilhet.TBIL_AVERBACAO a
WHERE a.SEQ_NUMER_AVB = b.SEQ_NUMER_AVB 
AND b.SEQ_NUMER_PRS = 506324
AND a.DHR_AVERB BETWEEN '2023-10-01' AND '2023-10-31'
AND SEQ_NUMER_FAT IS NULL 
AND b.SEQ_NUMER_FAT  = 7000309882
*/

/*LOCALIZAR AVERBA��ES DUPLICADAS E SEM FATURA*/
SELECT a.NUM_AVERB_PAM, a.SEQ_NUMER_AVB, a.NUM_AVERB_CLI, a.COD_MANIF, a.VLR_EMBAR, a.DHR_AVERB, a.DHR_EMBAR, a.DHR_ALTER, * 
FROM bilhet.TBIL_AVERBACAO a INNER JOIN BILHET.TBIL_RELAC_AVERB_PROPT B 
ON a.SEQ_NUMER_AVB = b.SEQ_NUMER_AVB 
WHERE NUM_AVERB_PAM IN  
()
and b.SEQ_NUMER_FAT IS NULL 
ORDER BY a.NUM_AVERB_PAM 

/*DELETAR AVERBA��ES DUPLICADAS E SEM FATURA*/
delete FROM bilhet.TBIL_RELAC_AVERB_PROPT
WHERE SEQ_NUMER_AVB IN ( 
SELECT SEQ_NUMER_AVB 
FROM bilhet.TBIL_AVERBACAO 
WHERE NUM_AVERB_PAM IN  
()
)
and SEQ_NUMER_FAT IS NULL 

COMMIT