/*INCLUSAO DOS RELATORIOS DO BILHETAGEM PARA SITE CORPORATIVO*/
INSERT INTO DBPROD.DOWNLOAD_ARQUIVO (
	NUM_CATEG_ARQ ,
	NOM_ARQUI ,
	CTL_VINCD ,
	COD_USER ,
	DHR_ALTER ,
	STA_EMAIL_SED ,
	STA_EMAIL_FIL ,
	STA_EMAIL_PAR,
	NUM_FILIA,
	CTL_CORRE ,
	NUM_ASCOM )
SELECT
	NUM_ARQUI_RET,
	NOM_ARQUI,
	COALESCE(CTL_VINCD, 0) AS CTL_VINCD,
	'MANUAL',
	CURRENT TIMESTAMP,
	'S',
	'S',
	'S',
	NUM_FILIA,
	CTL_CORRE,
	NUM_ASCOM
FROM
	BILHET.TBIL_ARQUIVO_DOCUMENTO_WEB DW
WHERE
	NOT EXISTS (
	SELECT
		NOM_ARQUI
	FROM
		DBPROD.DOWNLOAD_ARQUIVO DA
	WHERE DA.NOM_ARQUI = DW.NOM_ARQUI)
	AND DHR_ALTER >= '2024-06-01 00:00:00'
--	AND CTL_VINCD > 0
	--AND NOM_ARQUI LIKE '%202406%'
ORDER BY
	DHR_ALTER ASC

COMMIT


/*CONSULTA FILA DE PROCESSAMENTO RELATORIOS*/
SELECT * FROM bilhet.tBIL_FILA_ARQUIVO_DOCUM_WEB



/*ATUALIZA STATUS DE EXECUÇÃO QDO ESTIVER TRAVADO*/
UPDATE BILHET.TBIL_FILA_ARQUIVO_DOCUM_WEB SET 
STA_EXECU ='N',
DHR_ALTER = CURRENT TIMESTAMP 
WHERE NUM_FILA = 9

