
--TIP_ALERT_DDO 2   CORRE��O URGENTE
--SELECT * FROM GEDAD.TDAD_TIPO_ALERTA_VALID_DADO ttavd  

--TIP_VALID_DD = 7 Proposta em processamento da bilhetagem
-- SELECT * FROM GEDAD.TDAD_TIPO_VALID_DADO ttvd 

--NUM_TAREF_VAL 87  Controle de concorr�ncia de processamento da bilhetagem
--SELECT * FROM GEDAD.TDAD_TAREFA_VALIDACAO_DADO ttvd 


/*VERIFICAR SE EXISTE NUM_SEQUE_PRS NA TABELA ERROS DE PROCESSAMENTO*/
SELECT DISTINCT seq_numer_prs FROM gedad.tdad_procs_propt_bilhe
WHERE CTL_CONTR_TAF in (

33994817

)  -- ESSE C�DIGO VEM DO LOG DA APLICA��O CAMPO V_OUT_RESULT 
ORDER BY SEQ_NUMER_prs  ASC  

/*PROPOSTA*/
SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE --SEQ_NUMER_PRS in(506543) -- BUSCA POR SEQUENCIAL
NUM_APOLI in(3836900004455) -- BUSCA POR APOLICE

SELECT * FROM bilhet.LOG_BILHET lb 
WHERE SEQ_NUMER_PRS = 499288
ORDER BY seq  DESC

SELECT * FROM gedad.FATURA_BILHET fb 
WHERE SEQ_NUMER_FAT  = 67999978839

/*fatura*/
SELECT * FROM bilhet.TBIL_FATURA 
WHERE SEQ_NUMER_FAT = 7000284494 SEQ_NUMER_PRS = 505976
ORDER BY SEQ_NUMER_FAT DESC 
SEQ_NUMER_FAT = 7000284494  -- BUSCA POR NUMERO DA FATURA

/*AVERBA��O*/ 
SELECT * FROM BILHET.V_BIL_AVERBACAO vba 
WHERE  SEQ_NUMER_PRS IN (501088) -- BUSCA POR SEQUENCIA DA PROPOSTA
AND SEQ_NUMER_FAT = 7000222223 -- BUSCA POR NUMERO DA FATURA


/*RELACIONAMENTO DE AVERBA��ES E PROPOSTAS*/
SELECT * FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
WHERE SEQ_NUMER_FAT = 7000229146
AND SEQ_NUMER_PRS = 497388



/*BUSCA POR FATURAS DE UMA PROPOSTA N�O N�O ESTEJA CANCELADAS*/
SELECT * FROM bilhet.TBIL_FATURA tf 
WHERE --SEQ_NUMER_FAT = 7000228591 
SEQ_NUMER_PRS IN (497388
,497390)
AND SIT_FATUR <>6
ORDER BY NUM_MES_CPT 

/* FAZER SELECT PARA CONSULTAR SE EXISTEM PROPOSTAS PERDIDAS NAS TABELAS DE PROCESSAMENTO*/			 
/*SELECT 1*/
SELECT DISTINCT seq_numer_prs
FROM
	bilhet.TBIL_RELAC_VISAO_PERCU_PADRA
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
	--	ta.SEQ_NUMER_AVB =992465322
			tp.SEQ_NUMER_PRS IN (
			505036
)
		AND trap.NUM_ETAPA_AVB = 1
		AND trap.SEQ_NUMER_FAT + 0 IS NULL)
ORDER BY seq_numer_prs ASC; 

/*SELECT 2*/
--
SELECT * 
FROM bilhet.TBIL_RELAC_VISAO_PERCU_PROPT	
WHERE
(SEQ_NUMER_PRS,
SEQ_NUMER_AVB) IN (
SELECT
	trap.SEQ_NUMER_PRS,
	ta.SEQ_NUMER_AVB
FROM
	bilhet.TBIL_AVERBACAO ta
INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
	trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
INNER JOIN bilhet.TBIL_PROPOSTA tp ON
	tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
WHERE
--		ta.SEQ_NUMER_AVB =992465322
tp.SEQ_NUMER_PRS IN (
505036
)
	AND trap.NUM_ETAPA_AVB = 1
	AND trap.SEQ_NUMER_FAT + 0 IS NULL);
--


/*SELECT 3*/
SELECT DISTINCT seq_numer_prs 
FROM
	BILHET.TBIL_RELAC_VISAO_PROPT
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
--			ta.SEQ_NUMER_AVB =992465322
		tp.SEQ_NUMER_PRS IN (
505036
		)
		AND trap.NUM_ETAPA_AVB = 1
		AND trap.SEQ_NUMER_FAT + 0 IS NULL);

	

/* PROCESSO DE EXCLUS�O DE PROPOSTA PERDIDAS NAS TABELAS DE PROCESSAMENTO*/

/*DELETE 1*/
	DELETE
FROM
	bilhet.TBIL_RELAC_VISAO_PERCU_PADRA
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
		tp.SEQ_NUMER_PRS IN 
(499288)
AND trap.NUM_ETAPA_AVB = 1
AND trap.SEQ_NUMER_FAT + 0 IS NULL);

commit

/*DELETE 2*/
--
delete FROM bilhet.TBIL_RELAC_VISAO_PERCU_PROPT	
WHERE
(SEQ_NUMER_PRS,
SEQ_NUMER_AVB) IN (
SELECT
	trap.SEQ_NUMER_PRS,
	ta.SEQ_NUMER_AVB
FROM
	bilhet.TBIL_AVERBACAO ta
INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
	trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
INNER JOIN bilhet.TBIL_PROPOSTA tp ON
	tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
WHERE
		tp.SEQ_NUMER_PRS IN 
(499288)
	AND trap.NUM_ETAPA_AVB = 1
	AND trap.SEQ_NUMER_FAT + 0 IS NULL);
--


/*DELETE 3*/
DELETE
FROM
	BILHET.TBIL_RELAC_VISAO_PROPT
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
		tp.SEQ_NUMER_PRS IN 
(499288)
AND trap.NUM_ETAPA_AVB = 1
AND trap.SEQ_NUMER_FAT + 0 IS NULL);

COMMIT

/**
 --NOVOS DELETES IMPLEMENTAR DEPOIS DE VOLTAR O RELACIONAMENTO ENTRE AVERBACAO E RELAC_AVERB_PROPT 
		DELETE FROM bilhet.TBIL_RELAC_VISAO_PERCU_PADRA       
    WHERE (SEQ_NUMER_PRS, SEQ_NUMER_AVB)  IN 
					(SELECT trap.SEQ_NUMER_PRS, trap.SEQ_NUMER_AVB FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
           WHERE trap.SEQ_NUMER_PRS = v_proposta
					 AND trap.NUM_ETAPA_AVB =1      
           AND trap.SEQ_NUMER_FAT IS NULL);
--
		DELETE FROM bilhet.TBIL_RELAC_VISAO_PERCU_PROPT       
    WHERE (SEQ_NUMER_PRS, SEQ_NUMER_AVB)  IN 
					(SELECT trap.SEQ_NUMER_PRS, trap.SEQ_NUMER_AVB FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
           WHERE trap.SEQ_NUMER_PRS = v_proposta
					 AND trap.NUM_ETAPA_AVB =1      
           AND trap.SEQ_NUMER_FAT IS NULL);
--
		DELETE FROM bilhet.TBIL_RELAC_VISAO_PROPT       
    WHERE (SEQ_NUMER_PRS, SEQ_NUMER_AVB)  IN 
					(SELECT trap.SEQ_NUMER_PRS, trap.SEQ_NUMER_AVB FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
           WHERE trap.SEQ_NUMER_PRS = v_proposta
					 AND trap.NUM_ETAPA_AVB =1      
           AND trap.SEQ_NUMER_FAT IS NULL);
**/

/*SENSIBILIZA AVERBA��O NO SISTEMA DE TRANSPORTES*/
UPDATE DBPROD.TAVERBACAO SET
DHR_ALTER = CURRENT TIMESTAMP
WHERE CTL_AVERB IN (537519781
,537519787)

SELECT * FROM DBPROD.TAVERBACAO
WHERE CTL_AVERB IN (537519781
,537519787)


SELECT count(1) FROM bilhet.TBIL_RELAC_AVERB_PROPT
WHERE SEQ_NUMER_AVB IN ( 
	SELECT SEQ_NUMER_AVB  FROM bilhet.TBIL_AVERBACAO ta  
	WHERE ta.NUM_AVERB_PAM IN (537519781
,537519787))


	SELECT *  FROM bilhet.TBIL_AVERBACAO ta  
	WHERE ta.NUM_AVERB_PAM IN (537519781
,537519787)

SELECT
	NUM_TECNI,
	NOM_TECNI,
	NOM_APELI_TEC,
	TIP_DOCUM_PRI,
	COD_DOCUM_PRI,
	COD_LOGIN_USU,
	STA_ATIVO,
	DHR_ALTER,
	COD_USER
FROM
	bilhet.tBIL_TECNICO_SEGURO
WHERE
	1 = 1
	
SELECT
	tec.NUM_TECNI,
	tec.NOM_TECNI,
	tec.NOM_APELI_TEC,
	tec.TIP_DOCUM_PRI,
	tec.COD_DOCUM_PRI,
	tec.COD_LOGIN_USU,
	tec.STA_ATIVO,
	tec.DHR_ALTER,
	tec.COD_USER
FROM
	bilhet.tBIL_TECNICO_SEGURO tec
INNER JOIN bilhet.tBIL_RELAC_TECNICO_PROPOSTA relTec ON
	reltec.NUM_TECNI = tec.NUM_TECNI
WHERE
	relTec.DAT_FIM_VIG IS NULL
	AND tec.NUM_TECNI = ? FETCH FIRST 1 ROW ONLY	
	
