SELECT 
       AI.NUM_AVERB_PAM AS NUM_AVERB_PAM
     , A.SEQ_NUMER_AVB
     , P.SEQ_NUMER_PRS  
     , A.NUM_AVERB_CLI AS NUM_AVERB_CLI     
     , A.NUM_SEQUE_AVB AS NUM_SEQUE_AVB
     , A.COD_DOCUM_EMB AS MANIFESTO
     , (SELECT COD_IDENT_VEI FROM DBPROD.AVERBACAO_VEICULO V  WHERE V.CTL_AVERB = AI.NUM_AVERB_PAM  FETCH FIRST 1 ROWS ONLY) AS PLACA     
     , TRUNC(A.DHR_EMBAR) AS DHR_EMBAR
     , P.CTL_PEJUR_CIA AS CTL_PEJUR_CIA 
     , CIA.NOM_PESSO AS NOM_PEJUR_CIA
     , P.NUM_APOLI AS NUM_APOLI
     , CLI.NOM_PESSO AS NOM_FANTS_CLI
     , AP.VLR_IS AS TOTAL_EMBARCADO
     , DECODE(AI.VLR_PAMTX, 0, '', 'PX') STATUS_PAMTAX
     , CASE WHEN LO.TIP_LOCAL IN (1, 2) THEN LO.COD_IDENT_PAD ELSE LOR.COD_IDENT_PAD END ORIGEM 
     , CASE WHEN LD.TIP_LOCAL IN (1, 2) THEN LD.COD_IDENT_PAD ELSE LDE.COD_IDENT_PAD END DESTINO
     , (SELECT TP.PCE_TARIF_PEC FROM APLBIL.BIL_RELAC_VISAO_PERCU_PADRA RP 
         INNER JOIN APLBIL.BIL_VIGEN_TARIFA_PERCURSO TP ON (RP.CTL_VIGEN_PEC = TP.CTL_VIGEN_PEC)
         WHERE RP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND RP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
         FETCH FIRST 1 ROWS ONLY
        )AS TARIFA_PADRAO
     , (SELECT RP.VLR_TARIF_PEC FROM APLBIL.BIL_RELAC_VISAO_PERCU_PADRA RP 
         INNER JOIN APLBIL.BIL_VIGEN_TARIFA_PERCURSO TP ON (RP.CTL_VIGEN_PEC = TP.CTL_VIGEN_PEC)
         WHERE RP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND RP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
         ORDER BY RP.DHR_ALTER
         FETCH FIRST 1 ROWS ONLY
       ) AS PREMIO_TARIFA
     , FAT.NUM_MES_CPT 
     ,(SELECT  CASE WHEN COUNT(ST.SEQ_NUMER_FAT)=0 THEN 'N' ELSE 'S' END TEM_COMERCIAL
           FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA  ST 
           WHERE ST.NUM_TARIF = 16 AND ST.IDT_PREMI = 'C' AND ST.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT FETCH FIRST 1 ROWS ONLY)
     , CASE WHEN A.STA_FLUVI =null THEN 'N' ELSE A.STA_FLUVI END TEM_FLUVIAL
     , (SELECT SUM(
                CASE WHEN TP.NUM_TARIF IN(36,37) THEN NVL(VC.VLR_TARIF,0.06)
                WHEN TP.NUM_TARIF IN (33,34) THEN NVL(VC.VLR_TARIF,0.00)
                ELSE  VC.VLR_TARIF END) AS TARIFA_PROPOSTA 
                FROM APLBIL.BIL_RELAC_TAXA_PROPOSTA TP
                INNER JOIN APLBIL.BIL_TIPO_TARIFA_PROPOSTA T ON (T.NUM_TARIF = TP.NUM_TARIF)
                INNER JOIN APLBIL.BIL_VIGENCIA_TAXA_CLIENTE VC ON (TP.NUM_SEQUE_TAR = VC.NUM_SEQUE_TAR)
                WHERE TP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND TP.NUM_TARIF IN (15,16,33,34,36,37)
       ) AS TARIFA_PROPOSTA 
     , (SELECT NVL(MAX(PROPT.VLR_TARIF_PRS),0.00) AS PREMIO_PROPOSTA
            FROM APLBIL.BIL_RELAC_VISAO_PROPT PROPT
            INNER JOIN APLBIL.BIL_RELAC_TAXA_PROPOSTA TP ON (PROPT.SEQ_NUMER_PRS = TP.SEQ_NUMER_PRS)
            WHERE PROPT.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS  AND PROPT.SEQ_NUMER_AVB =A.SEQ_NUMER_AVB                    
      ) AS PREMIO_PROPOSTA
      , CLI.COD_DOCUM_PRI AS CNPJ
      , FAT.DAT_VENCI_FAT AS VENCTO_FATURA
      , CASE WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '01' THEN 'JANEIRO' 
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '02' THEN 'FEVEREIRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '03' THEN 'MAR�O'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '04' THEN 'ABRIL'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '05' THEN 'MAIO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '06' THEN 'JUNHO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '07' THEN 'JULHO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '08' THEN 'AGOSTO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '09' THEN 'SETEMBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '10' THEN 'OUTUBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '11' THEN 'NOVEMBRO'	
 	     WHEN SUBSTR(FAT.NUM_MES_CPT, 5,2) = '12' THEN 'DEZEMBRO' END
             ||'/'||SUBSTR(FAT.NUM_MES_CPT,1,4) ||' - '||PER.NOM_PERIO AS MES_FAT
       , R.SIG_RAMO
       ,(SELECT NVL(TF.VLR_CALCU,0) FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA TF  WHERE TF.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT AND TF.NUM_TARIF = 70 FETCH FIRST 1 ROWS ONLY) QTDE_AVB
       ,(SELECT NVL(ST.VLR_CALCU,0) PREMIO FROM APLBIL.BIL_VALOR_SOMA_TIPO_TARIFA ST WHERE ST.NUM_TARIF = 77 AND ST.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT FETCH FIRST 1 ROWS ONLY) AS PREMIO_AVERBACAO
 FROM APLBIL.BIL_FATURA FAT
INNER JOIN APLBIL.BIL_PROPOSTA P ON (P.SEQ_NUMER_PRS = FAT.SEQ_NUMER_PRS)
INNER JOIN APLBIL.BIL_PERIODO PER ON (P.NUM_PERIO = PER.NUM_PERIO)
INNER JOIN APLBIL.BIL_RELAC_AVERB_PROPT AP ON (AP.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND AP.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT)
INNER JOIN APLBIL.BIL_AVERBACAO A ON (A.SEQ_NUMER_AVB = AP.SEQ_NUMER_AVB)
INNER JOIN APLBIL.BIL_AVERBACAO_INDICE AI ON (AI.NUM_AVERB_PAM = A.NUM_AVERB_PAM)
INNER JOIN PAMAIS.V_CRP_PESSOA CIA ON (P.CTL_PEJUR_CIA = CIA.CTL_PESSO AND CIA.TIP_PESSO = 1)
INNER JOIN PAMAIS.V_CRP_PESSOA CLI ON (P.CTL_PESSO_CLI = CLI.CTL_PESSO AND CLI.TIP_PESSO = 1) 
INNER JOIN APLBIL.BIL_LOCALIDADE LO ON (LO.SEQ_NUMER_LOC = A.SEQ_LOCAL_ORI) 
LEFT JOIN APLBIL.BIL_LOCALIDADE LOR ON  (LO.SEQ_LOCAL_PAI = LOR.SEQ_NUMER_LOC) 
INNER JOIN APLBIL.BIL_LOCALIDADE LD ON (LD.SEQ_NUMER_LOC = A.SEQ_LOCAL_DES) 
LEFT JOIN APLBIL.BIL_LOCALIDADE LDE ON (LD.SEQ_LOCAL_PAI = LDE.SEQ_NUMER_LOC) 
INNER JOIN PAMAIS.V_CRP_RAMO_SEGURO  R ON (P.NUM_RAMO_SEG = R.NUM_RAMO_SEG)    
WHERE FAT.NUM_MES_CPT = 202402
  AND FAT.SEQ_NUMER_FAT =7000324203  
  AND FAT.NUM_PERIO_FAT = NVL(3 , FAT.NUM_PERIO_FAT)
  AND P.NUM_APOLI =  NVL(3836900011755, P.NUM_APOLI)
  AND P.NUM_RAMO_SEG =  NVL( 2, P.NUM_RAMO_SEG)
  AND AP.SEQ_NUMER_FAT IS NOT NULL
  AND AP.VLR_IS <> 0
ORDER BY ORIGEM,DHR_EMBAR,NUM_AVERB_PAM            
OPTIMIZE FOR 1 ROWS WITH UR