
--PROCESSO PARA ALTERAÇÃO DO VALOR DA TAXA EMBARCADOR

SELECT * FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA trtp 
WHERE SEQ_NUMER_PRS = 508381

SELECT b.NUM_SEQUE_VIG FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA a INNER JOIN BILHET.TBIL_VIGENCIA_TAXA_CLIENTE b 
ON b.NUM_SEQUE_TAR = a.NUM_SEQUE_TAR 
WHERE NUM_SEQUE_VIG = ?


SELECT num_seque_vig,
	b.num_seque_tar,
	to_char(dat_inici_vig,'dd/mm/yyyy') AS dat_inicio,
	to_char(dat_fim_vig,'dd/mm/yyyy') AS dat_fim, 
	vlr_tarif ,
	a.dhr_alter,
	a.cod_user
	FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a, 
      bilhet.TBIL_RELAC_TAXA_PROPOSTA b 
      WHERE b.NUM_SEQUE_TAR = a.NUM_SEQUE_TAR 
      AND b.SEQ_NUMER_PRS = 509015
      AND b.NUM_TARIF = 91
ORDER BY dat_inici_vig DESC 


SELECT * FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA trtp 
WHERE NUM_SEQUE_TAR = 1549782

SELECT * FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE tvtc 
WHERE NUM_SEQUE_TAR = 1549575


UPDATE bilhet.TBIL_VIGENCIA_TAXA_CLIENTE SET 
VLR_TARIF = 0.01
WHERE NUM_SEQUE_VIG IN (
1233515,
1233516,
1233517,
1233518
)

COMMIT


--SE RETORNAR NULO QUER DIZER QUE A DATA INFORMADA É MELHOR QUE O INICIO DA VIGENCIA EM ABERTO
SELECT * FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a, bilhet.TBIL_RELAC_TAXA_PROPOSTA b 
WHERE a.NUM_SEQUE_TAR = b.NUM_SEQUE_TAR 
AND  a.DAT_INICI_VIG < '2024-02-23' -- DATA QUE O USUÁRIO INFORMOU NO FORM
AND NUM_SEQUE_VIG IN (
	SELECT max(NUM_SEQUE_VIG) FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
	WHERE NUM_SEQUE_TAR = ? 
)


UPDATE bilhet.TBIL_VIGENCIA_TAXA_CLIENTE SET 
	DAT_FIM_VIG = ? ,
	DHR_ALTER = CURRENT timestamp,
	COD_USER = ?
WHERE NUM_SEQUE_VIG IN (
	SELECT max(NUM_SEQUE_VIG) FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
	WHERE NUM_SEQUE_TAR = ?
	
)






SELECT * FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a,
      bilhet.TBIL_RELAC_TAXA_PROPOSTA b
      WHERE b.NUM_SEQUE_TAR = a.NUM_SEQUE_TAR 
      AND b.SEQ_NUMER_PRS = ?
      AND b.NUM_TARIF = ?
ORDER BY b.NUM_SEQUE_TAR, dat_inici_vig DESC 
      
SELECT * FROM  bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
WHERE  NUM_SEQUE_VIG IN ( SELECT max(NUM_SEQUE_VIG) FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
WHERE NUM_SEQUE_TAR = 1545737)

SELECT 
      
      
DELETE FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA
WHERE num_seque_tar IN (
1545739,
1545740)

DELETE from bilhet.TBIL_VIGENCIA_TAXA_CLIENTE 
WHERE num_seque_vig IN (
1228989,
1228987,
1228990,
1228986,
1228988,
1228985
)

COMMIT


UPDATE BILHET.TBIL_VIGENCIA_TAXA_CLIENTE SET
STA_AGREGA_FILIAL = ?,
VLR_TARIF = ?, -- float até 3 casas decimais
DHR_ALTER = CURRENT TIMESTAMPDIFF,
COD_USER = ? --usuário logado NO sistema 
WHERE NUM_SEQUE_VIG = ? -- chave da tabela 

COMMIT



SELECT a.*, b.NOM_FANTS, b.NOM_PESSO
FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA a, pamais.TCRP_PESSOA b 
WHERE a.COD_CNPJ_EMBARCADOR = b.COD_DOCUM_PRI
AND a.SEQ_NUMER_PRS = 505822


SELECT COD_CNPJ_EMBARCADOR, dat_inici_vig, dat_fim_vig, vlr_tarif FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a,
      bilhet.TBIL_RELAC_TAXA_PROPOSTA b 
      WHERE b.NUM_SEQUE_TAR = a.NUM_SEQUE_TAR
      AND b.SEQ_NUMER_PRS = 508582 
      AND b.NUM_TARIF = 63--91
ORDER BY COD_CNPJ_EMBARCADOR, dat_fim_vig



SELECT
	EXISTS (
	SELECT
		1
	FROM
		bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a
	JOIN bilhet.TBIL_RELAC_TAXA_PROPOSTA b ON
		a.NUM_SEQUE_TAR = b.NUM_SEQUE_TAR
	WHERE
		a.DAT_INICI_VIG <'2023-12-31'
		AND a.NUM_SEQUE_VIG IN (
		SELECT
			MAX(NUM_SEQUE_VIG)
		FROM
			bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
		WHERE
			NUM_SEQUE_TAR = 1542075 
        )  
    )
    FROM DUAL 
    
    SELECT
	CASE
		WHEN EXISTS (
		SELECT
			1 
			FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a 
		JOIN bilhet.TBIL_RELAC_TAXA_PROPOSTA b ON
			a.NUM_SEQUE_TAR = b.NUM_SEQUE_TAR 
			WHERE a.DAT_INICI_VIG < '2023-12-01'
			AND a.NUM_SEQUE_VIG = ( 
			SELECT
				MAX(NUM_SEQUE_VIG) 
			FROM
				bilhet.TBIL_VIGENCIA_TAXA_CLIENTE
			WHERE
				NUM_SEQUE_TAR = 1542075 )) THEN 1
		ELSE 0
	END 
	FROM SYSIBM.SYSDUMMY1
	
	
	SELECT * FROM bilhet.TBIL_LOG_ALTERACAO_BILHET tlab 