/*LOCALIZA VIGENCIA DA APOLICE*/
SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 508790
NUM_APOLI = 3836006571254



SELECT DISTINCT 
SIG_SIMBO_MOE, 
P.NUM_SEQUE_VIG AS ID_VIGENCIA, 
MOEDA.SIG_SIMBO_MOE, 
T.NOM_APELI_TAR AS CAMPO, 
T.NUM_TARIF AS ID_TARIFA, 
P.DAT_INICI_VIG, 
P.DAT_FIM_VIG, 
P.VLR_TARIF AS VALOR, 
T.IDT_TIPO_DDO 
FROM 
bilhet.V_BIL_TAXA_PROPOSTA P 
INNER JOIN bilhet.tBIL_TIPO_TARIFA_PROPOSTA T ON P.NUM_TARIF = T.NUM_TARIF 
INNER JOIN bilhet.tBIL_PROPOSTA J ON P.SEQ_NUMER_PRS = J.SEQ_NUMER_PRS 
INNER JOIN bilhet.V_BIL_MOEDA MOEDA ON MOEDA.NUM_MOEDA = J.NUM_MOEDA_PRS 
WHERE J.NUM_APOLI = 3836900015155




/*LOCALIZA TAXAS DA APOLICE*/
SELECT * FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA trtp 
WHERE SEQ_NUMER_PRS = 508582


SELECT b.SEQ_NUMER_PRS, b.NUM_TARIF , * FROM bilhet.TBIL_VIGENCIA_TAXA_CLIENTE a
,bilhet.TBIL_RELAC_TAXA_PROPOSTA b
WHERE a.NUM_SEQUE_TAR = b.NUM_SEQUE_TAR 
and b.SEQ_NUMER_PRS in(507629)


/*LOCALIZA VIGENCIA DAS TAXAS APOLICE */
SELECT * FROM BILHET.TBIL_VIGENCIA_TAXA_CLIENTE tvtc 
WHERE NUM_SEQUE_TAR  IN ( 
1537270,
1537271,
1537272,
1537273
)
ORDER by NUM_SEQUE_TAR 

/*ATUALIZAR VIGENCIA DAS TAXAS DAS APOLICES, SOMENTE AS COM VIGENCIA DENTRO DO RANGE ATUAL, N�O CONSIDERAR TAXAS DE VIGENCIAS ANTERIORES*/
UPDATE BILHET.TBIL_VIGENCIA_TAXA_CLIENTE SET 
	DAT_INICI_VIG = '2022-12-31'
--	,dat_fim_vig = '2024-02-25'
WHERE NUM_SEQUE_VIG  IN (
1220196,
1220197,
1220198,
1220199
)							

COMMIT 

SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE seq_numer_prs = 507629

UPDATE bilhet.TBIL_PROPOSTA SET 
DAT_INICI_VIG = '2022-12-31'
--,DAT_FIM_VIG ='2024-02-25'
WHERE SEQ_NUMER_PRS = 507629

COMMIT
