/*VERIFICAR AVERBAÇÕES NO SISTEMA DE TRANSPORTES x BILHETAGEM*/

/*RETORNA AS AVERBAÇÕES DO SISTEMA DE TRANSPORTES QUE NÃO FORAM INSERIDAS NA TABELA DE AVERBAÇÕES DO BILHETAGEM
 * */
SELECT a.CTL_AVERB AS averbacao
	, b.NUM_PROPT AS proposta
	,(SELECT COD_DOCUM  FROM DOC_VINCULADO WHERE CTL_VINCD = b.CTL_VINCD_SED) AS documento
	,(SELECT NOM_VINCD FROM VINCULADO  WHERE CTL_VINCD  = b.CTL_VINCD_SED) AS nome
	,(SELECT NOM_GUERR FROM VINCULADO  WHERE CTL_VINCD  = b.CTL_VINCD_SED) AS fantasia
	, b.SIT_AVERB 
	,(SELECT des_situa_avb FROM TSITUACAO_AVERBACAO WHERE sit_averb = b.SIT_AVERB)
	, b.SIT_TRANS
	,(SELECT des_situa_trm FROM TSITUACAO_TRANSM WHERE sit_trans = b.SIT_TRANS)
	, c.TIP_ISENC_SEG 
	, (SELECT des_isenc_seg FROM TTIPO_ISENCAO_SEG WHERE tip_isenc_seg = c.TIP_ISENC_SEG)
	, d.TIP_PROPT 
	, d.DES_TIPO_PRS 
	, a.DHR_AVERB 
	, a.DHR_ENTRA 
	, a.DHR_LIBER 
	, a.DHR_ALTER
	, a.COD_USER
FROM TAVERBACAO a
, TAVERBACAO_INDICE b
, TITEM_DESTINO c
, SEGURO.TSEG_TIPO_PROPOSTA d
, SEGURO.TSEG_PROPOSTA_SEGURO e 
WHERE a.CTL_AVERB = b.CTL_AVERB
AND a.CTL_AVERB = c.CTL_AVERB 
AND b.NUM_PROPT = e.NUM_PROPT 
AND d.TIP_PROPT = e.TIP_PROPT 
AND (
	( b.sit_trans   = 0  and  b.sit_averb = 4  ) or
    ( b.sit_trans   = 1  and  b.sit_averb = 4  ) or
	( b.sit_trans   = 0  and  b.sit_averb = 10 ) or
    ( b.sit_trans   = 1  and  b.sit_averb = 10 ) or
	( b.sit_trans   = 0  and  b.sit_averb = 11 ) or
    ( b.sit_trans   = 1  and  b.sit_averb = 11 )
)
AND c.TIP_ISENC_SEG <> 5
AND d.TIP_PROPT = 1
AND b.CTL_VINCD_SED NOT IN (2561, 2830, 518946, 500312, 500008, 502211, 505324)
AND a.DAT_EMBAR BETWEEN '2022-07-01 00:00:00' AND CURRENT timestamp
AND NOT EXISTS (SELECT ta.SEQ_NUMER_AVB  FROM bilhet.TBIL_AVERBACAO ta 
						WHERE ta.NUM_AVERB_PAM = a.CTL_AVERB)

						
SELECT a.num_averb_pam FROM BILHET.TBIL_AVERBACAO a
WHERE a.DHR_AVERB BETWEEN '2022-05-01 00:00:00' AND '2022-07-04 23:59:59'
AND a.SEQ_NUMER_AVB NOT IN (SELECT b.SEQ_NUMER_AVB 
								FROM BILHET.TBIL_RELAC_AVERB_PROPT b
								)

SELECT a.CTL_VINCD, b.COD_DOCUM, a.TIP_ATIVI , a.TIP_VINCD , a.NOM_GUERR, a.NOM_VINCD FROM VINCULADO a, DOC_VINCULADO b 
WHERE a.ctl_vincd = b.ctl_vincd 
AND a.CTL_VINCD IN (2561, 2830, 518946, 500312, 500008, 502211, 505324)

/*ATUALIZA DHR_ALTER DA TABELA AVERBAÇÃO PARA ATIVAR A TRIGGER DE IMPORTAÇÃO PARA O BILHETAGEM*/
UPDATE AVERBACAO SET DHR_ALTER = current timestamp 
WHERE CTL_AVERB IN (
		SELECT a.CTL_AVERB AS averbacao
		FROM TAVERBACAO a
		, TAVERBACAO_INDICE b
		, TITEM_DESTINO c
		WHERE a.CTL_AVERB = b.CTL_AVERB
		AND a.CTL_AVERB = c.CTL_AVERB 
		AND (
			( b.sit_trans   = 0  and  b.sit_averb = 4  ) or
		    ( b.sit_trans   = 1  and  b.sit_averb = 4  ) or
			( b.sit_trans   = 0  and  b.sit_averb = 10 ) or
		    ( b.sit_trans   = 1  and  b.sit_averb = 10 ) or
			( b.sit_trans   = 0  and  b.sit_averb = 11 ) or
		    ( b.sit_trans   = 1  and  b.sit_averb = 11 )
		)
		AND c.TIP_ISENC_SEG <> 5
		AND b.CTL_VINCD_SED NOT IN (2561, 2830, 518946, 500312, 500008, 502211, 505324)
		AND a.DHR_AVERB BETWEEN '2022-06-30 00:00:00' AND '2022-07-05 23:59:59'
		AND NOT EXISTS (SELECT * FROM BILHET.TBIL_AVERBACAO ta WHERE ta.NUM_AVERB_PAM = a.CTL_AVERB)
)

COMMIT 


SELECT * FROM BILHET.TBIL_LOG_TRIGGER 


SELECT count(1) FROM bilhet.TBIL_RELAC_AVERB_PROPT
WHERE SEQ_NUMER_AVB IN ( 
	SELECT SEQ_NUMER_AVB  FROM bilhet.TBIL_AVERBACAO ta  
	WHERE ta.NUM_AVERB_PAM IN ())

/*LOCALIZA SE EXISTE INCONSISTENCIA REGISTRO NA TABELA DE AVERBAÇÃO QUE NÃO FOI COMPLEMENTADO NA TABELA BIL_RELAC_PROPT*/
SELECT SEQ_NUMER_AVB, NUM_AVERB_PAM, TIP_ISENC_SEG, DHR_AVERB, DHR_EMBAR, DHR_ALTER  
FROM BILHET.TBIL_AVERBACAO ta 
WHERE TIP_ISENC_SEG IN (1,7) 
AND ta.DHR_AVERB BETWEEN '2022-07-01 00:00:00' AND CURRENT TIMESTAMP  
AND NOT EXISTS (SELECT * FROM bilhet.TBIL_RELAC_AVERB_PROPT b WHERE b.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB)


/*VERIFICA SE EXISTE REGISTRO NA TBIL_RELAC_AVERB_PROPT*/
SELECT * FROM bilhet.TBIL_RELAC_AVERB_PROPT a
WHERE NOT EXISTS (SELECT * FROM BILHET.TBIL_AVERBACAO ta 
					WHERE TIP_ISENC_SEG IN (1,7))
AND a.DHR_ALTER BETWEEN '2022-07-01 00:00:00' AND CURRENT TIMESTAMP

SELECT * FROM TTIPO_ISENCAO_SEG tis 


SELECT * FROM bilhet.TBIL_AVERBACAO ta 
WHERE 1=1
--AND SEQ_NUMER_AVB= 1047712420
AND num_averb_pam IN (503046999 , 503052181, 502158758)

SELECT * FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
WHERE SEQ_NUMER_AVB IN (
)

SELECT * FROM bilhet.TBIL_AVERBACAO
WHERE NUM_AVERB_PAM IN ()
 --498455080

SELECT * FROM BILHET.TBIL_LOG_AVERBACAO
WHERE NUM_AVERB_PAM =  498455080

SELECT * FROM DBPROD.TAVERBACAO
WHERE CTL_AVERB IN ()


SELECT * FROM DBPROD.TAVERBACAO_INDICE ti 
WHERE CTL_AVERB IN ()


UPDATE DBPROD.TAVERBACAO SET
DHR_ALTER = CURRENT TIMESTAMP
WHERE CTL_AVERB = 513493575

COMMIT 

SELECT * FROM DBPROD.TITEM_DESTINO td 
WHERE CTL_AVERB IN ()


SELECT * FROM SEGURO.TSEG_TIPO_PROPOSTA ttp 


	SELECT
		c.num_averb_pam, a.SEQ_NUMER_PRS, a.DHR_ALTER, d.*
	FROM
		bilhet.TBIL_RELAC_AVERB_PROPT a,
		BILHET.TBIL_PROPOSTA b,
		bilhet.TBIL_AVERBACAO c,
		bilhet.tbil_log_trigger d
	WHERE a.seq_numer_avb = c.seq_numer_avb
		AND a.SEQ_NUMER_PRS = b.SEQ_NUMER_PRS
		AND d.ctl_averb = c.NUM_AVERB_PAM 
		AND b.CTL_PESSO_CLI IN(517733
, 15215
, 16674
, 15727
, 7347
, 19850)
    AND d.CTL_AVERB = 523091880
	AND a.DHR_ALTER BETWEEN '2022-07-13 10:00:00' AND CURRENT TIMESTAMP 

            
SELECT CTL_AVERB AS averbacao, 
		TO_char(DHR_CADAS,'dd/mm/yyyy hh24:mi:ss') AS DHR_CADAS 
		, NOM_TRIGGER
		, CLIENT_WRKSTNNAME AS instancia
		,APPLICATION_ID AS IP
		FROM bilhet.TBIL_LOG_TRIGGER tlt 
WHERE DHR_CADAS BETWEEN '2022-07-14 14:00:00' AND CURRENT TIMESTAMP  
ORDER BY CTL_AVERB ASC 			




SELECT * FROM pamais.tcrp_pessoa WHERE COD_DOCUM_PRI IN ('01599101000193', '24217653000195', '43244631000169', '00233065000187', '88085485000104', '08219203000185')

SELECT DISTINCT A.NUM_PROPT, A.CTL_CLIEN_PPS, P.COD_DOCUM_PRI, P.NOM_PESSO, P.NOM_FANTS
FROM SEGURO.TSEG_PROPOSTA_SEGURO A
INNER JOIN PAMAIS.TCRP_PESSOA P ON P.CTL_PESSO = A.CTL_CLIEN_PPS
INNER JOIN DBPROD.TAVERBACAO_INDICE I ON A.NUM_PROPT = I.NUM_PROPT AND A.TIP_PROPT = 1 AND A.SIT_TIPO_PRS = 1
INNER JOIN BILHET.TBIL_LOG_AVERBACAO L ON L.NUM_AVERB_PAM = I.CTL_AVERB
WHERE P.TIP_DOCUM_PRI = 1 
AND P.COD_DOCUM_PRI IN ('01599101000193', '24217653000195', '43244631000169', '00233065000187', '88085485000104', '08219203000185')


SELECT * FROM bilhet.TBIL_LOG_TRIGGER tlt 
WHERE CTL_AVERB = 523678444
ORDER BY DHR_CADAS 



SELECT count(1) FROM bilhet.TBIL_RELAC_AVERB_PROPT
WHERE SEQ_NUMER_AVB IN ( 
       SELECT SEQ_NUMER_AVB  FROM bilhet.TBIL_AVERBACAO ta  
       WHERE ta.NUM_AVERB_PAM IN (537519781,537519787))
