SELECT p.SEQ_NUMER_PRS,tp.NUM_PROPT, p.NUM_ETAPA_AVB, count(1) AS total
FROM bilhet.TBIL_RELAC_AVERB_PROPT p
INNER JOIN bilhet.TBIL_PROPOSTA tp ON tp.SEQ_NUMER_PRS = p.SEQ_NUMER_PRS 
INNER JOIN bilhet.tbil_AVERBACAO a ON a.SEQ_NUMER_AVB = p.SEQ_NUMER_AVB 
INNER JOIN bilhet.TBIL_AVERBACAO_INDICE ai ON ai.NUM_AVERB_PAM = a.NUM_AVERB_PAM 
WHERE p.SEQ_NUMER_PRS in (508958, 508411, 508412, 508550, 508551)
AND a.DHR_ALTER BETWEEN '2024-07-29 10:40:00' AND CURRENT timestamp 
GROUP BY  p.SEQ_NUMER_PRS, tp.NUM_PROPT , p.NUM_ETAPA_AVB


SELECT * FROM TIPO_AVERBACAO 

SELECT * FROM APLTRANS.AVERBACAO_INDICE 
WHERE NUM_PROPT = 24003407
AND CTL_AVERB = 860736765

UPDATE APLTRANS.AVERBACAO_INDICE SET 
SIT_AVERB = 0
,SIT_TRANS = 0
WHERE NUM_PROPT = 24003407
AND CTL_AVERB = 860736765

commit


SELECT ae.TIP_ERRO , ea.DES_ERRO, count(1) 
FROM APLTRANS.AVERBACAO_ERRO ae INNER JOIN apltrans.ERRO_AVERBACAO ea 
ON ea.TIP_ERRO = ae.TIP_ERRO 
GROUP BY ae.TIP_ERRO , ea.DES_ERRO

SELECT DISTINCT CTL_AVERB FROM APLTRANS.AVERBACAO_ERRO 
WHERE CTL_AVERB = 571962512





