/*cancelar fatura*/

SELECT * FROM bilhet.TBIL_FATURA tf 
WHERE SEQ_NUMER_PRS = 505976
ORDER BY SEQ_NUMER_FAT  DESC 

SEQ_NUMER_FAT = 7000238629


UPDATE bilhet.TBIL_FATURA SET
NUM_FATUR_CIA = NULL,
SIT_FATUR = 6,
SIT_ENVIO_FAT = 1
WHERE SEQ_NUMER_FAT IN (7000336184)
COMMIT 




SELECT * FROM bilhet.TBIL_SITUACAO

