
/*DELETAR PROPOSTAS DUPLICADAS (ESSE PROCEDIMENTO SÓ É VALIDO APÓS AJUSTES NA INTEGRAÇÃO)*/

SELECT * FROM BILHET.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 503885


/**/
SELECT *  FROM bilhet.TBIL_HIERQ_PRODR_PROPT  
WHERE SEQ_NUMER_PRS = 503885

DELETE  FROM bilhet.TBIL_HIERQ_PRODR_PROPT  
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_PROPOSTA_AJUSTAVEL   
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_PROPOSTA_AJUSTAVEL   
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_RELAC_PROPOSTA_DIVIS_CIA   
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_RELAC_PROPOSTA_DIVIS_CIA   
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_VENCIMENTO_FATURA_PROPT
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_VENCIMENTO_FATURA_PROPT
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_PROPOSTA_CREDITO_DEBITO 
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_PROPOSTA_CREDITO_DEBITO 
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_TARIF_PERCU_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_TARIF_PERCU_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_RELAC_TECNICO_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

DELETE  FROM bilhet.TBIL_RELAC_TECNICO_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT *  FROM bilhet.TBIL_RELAC_AVERB_PROPT 
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_RELAC_AVERB_PROPT 
WHERE SEQ_NUMER_PRS = 503885


/**/
SELECT * FROM BILHET.TBIL_VIGENCIA_TAXA_CLIENTE
WHERE NUM_SEQUE_TAR  IN (SELECT NUM_SEQUE_TAR  FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885
)

DELETE BILHET.TBIL_VIGENCIA_TAXA_CLIENTE
WHERE NUM_SEQUE_VIG IN (1198215
,1198216
,1198217
,1198218
,1198219)

ROLLBACK 

/**/
SELECT *  FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885

SELECT * FROM BILHET.TBIL_VIGENCIA_TAXA_CLIENTE
WHERE NUM_SEQUE_TAR  IN (SELECT NUM_SEQUE_TAR  FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA 
WHERE SEQ_NUMER_PRS = 503885
)

ROLLBACK 

/**/
SELECT *  FROM bilhet.TBIL_FATURA 
WHERE SEQ_NUMER_PRS = 503885

delete  FROM bilhet.TBIL_FATURA 
WHERE SEQ_NUMER_PRS = 503885

/**/
SELECT * FROM BILHET.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 503885

DELETE FROM BILHET.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 503885




