
SELECT
	f.SEQ_NUMER_FAT,
	p.NUM_APOLI ,
	p.NUM_RAMO_SEG ,
	CASE 
		WHEN f.IDT_ENVIO_CBR = 'I' THEN  'Incluido' 
		WHEN f.IDT_ENVIO_CBR = 'U' THEN 'Atualizado'
		WHEN f.IDT_ENVIO_CBR = 'C'THEN 'Cancelado'
		ELSE f.IDT_ENVIO_CBR
	END AS situacao_envio_cobranca,
	f.DHR_FATUR,
	f.DHR_ALTER,
	f.DAT_VENCI_FAT,
	f.NUM_MES_CPT,
	f.NUM_FATUR_CIA,
	f.CTL_GRUPO_FAT,
	f.sit_fatur,
	sf.DES_SITUA_FAT, 
	f.sit_envio_fat,
	sef.DES_SITUA_ENV
FROM
	bilhet.TBIL_FATURA f
INNER JOIN bilhet.TBIL_PROPOSTA p 
ON
	p.SEQ_NUMER_PRS = f.SEQ_NUMER_PRS
INNER JOIN bilhet.TBIL_SITUACAO_FATURA sf
ON 
	sf.SIT_FATUR = f.SIT_FATUR 
INNER JOIN bilhet.TBIL_SITUACAO_ENVIO_FATURA sef
ON
	sef.SIT_ENVIO_FAT = f.SIT_ENVIO_FAT 
WHERE
	f.SIT_ENVIO_FAT = 4
	AND f.DHR_ALTER BETWEEN '2024-07-01 00:00:00' AND CURRENT timestamp
ORDER BY
	f.SEQ_NUMER_FAT 
