--- Extração para MAPFRE --- 2022 - INICIO
SELECT DISTINCT
       SUBSTR(F.NUM_MES_CPT,5,2)||'_'||SUBSTR(F.NUM_MES_CPT,1,4) AS MES_ANO_COMPT
--     , M.DES_MOVIM_FAT as DATA_MOVIMENTO
     , SR.NUM_RAMO_SSP AS RAMO
     , SR.SIG_RAMO AS SIG_RAMO 
     , (CASE SR.NUM_RAMO_SEG 
     	WHEN 1 THEN 250
     	WHEN 66 THEN 250
     	WHEN 3 THEN 210
     	WHEN 67 THEN 210
     	WHEN 59 THEN 220
     	WHEN 1 THEN 250
        WHEN 30 THEN 291
        WHEN 9 THEN 290
        WHEN 2 THEN 260
        WHEN 56 THEN 270
        ELSE
			000 
		END ) AS PRODUTO	
     	
 ---     , P.FILIAL_ADM    AS FILIAL
     , P.NUM_APOLI     AS APOLICE
     , F.SEQ_NUMER_FAT AS PROPOSTA
     , (SELECT SUBSTR(DES_MOVIM_FAT,7,4)||'-'||SUBSTR(DES_MOVIM_FAT,4,2)||'-'||SUBSTR(DES_MOVIM_FAT,1,2) FROM BILHET.TBIL_MOVIM_FATURA M WHERE M.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND M.NUM_TARIF = 81) AS DT_EMIS
     , F.DAT_VENCI_FAT as DATA_VENCIMENTO
     , P.COD_DOCUM_CLI AS CNPJ
     , P.NOM_PESSO_CLI AS SEGURADO
     , C.NUM_SUCUR_PAM as CODIGO_CORRETOR
     , CAST((SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 70) AS INTEGER) AS QTD_VIAG
     , DECODE(P.NUM_MOEDA_PRS, 14, 'R$', 'US$') AS MOEDA_EMISSAO
     , (SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 69) AS TOTAL_MERCADORIA
--     , (SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 60 AND IDT_PREMI = 'C') AS PREMIO_TARIFA
--     , (SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 61 AND IDT_PREMI = 'C') AS PREMIO_COMERCIAL
     , (SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 61 AND IDT_PREMI = 'C') AS PREMIO_LIQUIDO
--     , (SELECT SUM(VLR_CALCU) FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF IN (65, 67) AND IDT_PREMI = 'C') AS CUSTO_PROCESSAMENTO
     , (SELECT VLR_CALCU FROM BILHET.TBIL_VALOR_SOMA_TIPO_TARIFA WHERE SEQ_NUMER_FAT = F.SEQ_NUMER_FAT AND NUM_TARIF = 68) AS PREM_TOTAL
--     , UPPER(S.DES_SITUA_FAT) AS STATUS_CONTA
FROM BILHET.TBIL_FATURA F
  INNER JOIN BILHET.V_BIL_PROPOSTA P ON (F.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS)
  INNER JOIN pamais.V_CRP_SUCURSAL_CIA_SEGURADORA C on C.CTL_PEJUR_CIA=P.CTL_PEJUR_CIA and C.CTL_SUCUR=P.CTL_SUCUR
  LEFT JOIN PAMAIS.V_CRP_RAMO_SEGURO SR ON (P.NUM_RAMO_SEG = SR.NUM_RAMO_SEG)
  INNER JOIN BILHET.TBIL_SITUACAO_FATURA S ON (F.SIT_FATUR = S.SIT_FATUR)
  INNER JOIN BILHET.TBIL_MOVIM_FATURA M ON (F.SEQ_NUMER_FAT = M.SEQ_NUMER_FAT)
WHERE F.SIT_FATUR NOT IN (1,3,6,7) --DCSIS NÃO ENVIA
  AND F.SIT_ENVIO_FAT = 4 -- EMITIDA
  AND P.CTL_PEJUR_CIA = 17341 -- MAPFRE
  AND TO_NUMBER(SUBSTR(F.NUM_MES_CPT,5,2)) ='01' --MES
  AND TO_NUMBER(SUBSTR(F.NUM_MES_CPT,1,4)) ='2022' --ANO
  AND M.NUM_TARIF = 81 --DATA DE PROCESSAMENTO DA FATURA NA PAMCARY
  --AND SUBSTR(M.DES_MOVIM_FAT,7,4)='2022' --ano
  --AND SUBSTR(M.DES_MOVIM_FAT,4,2)='01'  --MES

  --- Extração para MAPFRE --- 2022 - Final
*/
