      
/*VERIFICAR SE EXISTE A MESMA RAIZ DENTRO DA APOLICE COM AGREGA FILIAL = S*/      
SELECT B.SEQ_NUMER_PRS,  SUBSTR(b.COD_CNPJ_EMBARCADOR,1,8), COUNT(1) FROM bilhet.tbil_vigencia_taxa_cliente a
INNER JOIN bilhet.TBIL_RELAC_TAXA_PROPOSTA b
ON b.NUM_SEQUE_TAR = a.NUM_SEQUE_TAR 
WHERE a.STA_AGREGA_FILIAL = 'S'
GROUP BY B.SEQ_NUMER_PRS,  SUBSTR(b.COD_CNPJ_EMBARCADOR,1,8)
HAVING count(1) > 1