--CONSULTA DAT_INICI_VIG E DAT_FIM_VIG DE VIGENCIA DA APOLICE
SELECT SEQ_NUMER_PRS, NUM_APOLI, NUM_RAMO_SEG, DAT_INICI_VIG, DAT_FIM_VIG 
FROM bilhet.TBIL_PROPOSTA tp 
WHERE NUM_APOLI = 3836006776354

--ALTERAÇÃO DE VIGENCIA DA APOLICE E TAXAS

--CONSULTA AS TAXAS E VIGENCIAS CADASTRADAS NA APOLICE
SELECT A.NUM_SEQUE_TAR
	, B.NUM_SEQUE_VIG
	, A.NUM_TARIF
	, B.VLR_TARIF
	, B.DAT_INICI_VIG
	, B.DAT_FIM_VIG  
FROM bilhet.TBIL_RELAC_TAXA_PROPOSTA A INNER JOIN bilhet.TBIL_VIGENCIA_TAXA_CLIENTE B 
ON A.NUM_SEQUE_TAR = B.NUM_SEQUE_TAR 
WHERE SEQ_NUMER_PRS = 508790

COMMIT

--ATUALIZA DAT_INICI_VIG OU DAT_FIM_VIG  DAS TAXAS DA APOLICE
UPDATE bilhet.TBIL_VIGENCIA_TAXA_CLIENTE SET
DAT_INICI_VIG = '2024-02-29' 
--DAT_FIM_VIG = '2022-05-31'
WHERE NUM_SEQUE_VIG IN (
1226221,
1226222,
1226223,
1226224
)


--CONSULTA DAT_INICI_VIG E DAT_FIM_VIG DE VIGENCIA DA APOLICE
SELECT SEQ_NUMER_PRS, NUM_APOLI, NUM_RAMO_SEG, DAT_INICI_VIG, DAT_FIM_VIG 
FROM bilhet.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 508790

--ATUALIZA DAT_INICI_VIG OU DAT_FIM_VIG  DA APOLICE
UPDATE bilhet.TBIL_PROPOSTA SET
DAT_INICI_VIG = '2024-02-29'
--DAT_FIM_VIG = '2022-02-07'
WHERE SEQ_NUMER_PRS = 508790

COMMIT 

