]
/*PROCESSO PARA SENSIBILIZA TRIGGER PELA TABELA DE AVERBAÇÃO*/
SELECT * FROM TAVERBACAO
WHERE CTL_AVERB IN (64358835)

UPDATE AVERBACAO SET
dhr_alter = CURRENT TIMESTAMP 
WHERE CTL_AVERB IN (64358835)

COMMIT 


/*PROCESSO PARA SENSIBILIZAR TRIGGER PELA TABELA DE TAVERBAÇÃO_INDICE*/
SELECT * FROM TAVERBACAO_INDICE
WHERE CTL_AVERB IN (64120985)

UPDATE TAVERBACAO_INDICE SET
SIT_AVERB = 4
,SIT_TRANS = 0
WHERE CTL_AVERB = 64120985

COMMIT 

/*PROCESSO PARA SENSIBILIZAR TRIGGER PELA TABELA DE TAVERBACAO_COMPLEM_ATM*/
SELECT * FROM TAVERBACAO_COMPLEM_ATM tca 
WHERE CTL_AVERB IN (SELECT CTL_AVERB FROM AVERBACAO_INDICE)
WHERE CTL_AVERB IN (143489831)

UPDATE TAVERBACAO_COMPLEM_ATM SET
DHR_ALTER = CURRENT TIMESTAMP 
WHERE CTL_AVERB = 127911705

COMMIT 


/*PROCESSO PARA SENSIBILIZAR TRIGGER PELA TABELA DE TDESTINO*/
SELECT * from TDESTINO
WHERE CTL_AVERB IN (64120906)

UPDATE TDESTINO  SET
DHR_ALTER = CURRENT TIMESTAMP 
WHERE CTL_AVERB = 64120906

COMMIT 

/*PROCESSO PARA SENSIBILIZAR TRIGGER PELA TABELA DE TITEM_INDICE*/
SELECT * from TITEM_DESTINO
WHERE CTL_AVERB IN (64120906,64161425)

UPDATE TITEM_DESTINO  SET
DHR_ALTER = CURRENT TIMESTAMP 
WHERE CTL_AVERB = 64161425

COMMIT 



/*CONFERENCIA PARA IDENTIFICAR SE AS TRIGGERS FORAM ATIVADAS*/
SELECT * FROM BILHET.TBIL_LOG_TRIGGER
WHERE CTL_AVERB  IN (64358835, 64120985, 64120906, 127911705) 

DELETE FROM bilhet.tbil_log_trigger 
WHERE seq IN (
125579
,125580
,125581
,125582)

/*
 * TRIGGERS 
 * 1- TR_AU_TAVERBACAO
 * AFTER UPDATE
 * 
 * INSERT DBPROD.TAVERBACAO_LOG_BI
 * 
 * EXECUTAR BILHET.SP_BIL_INSERE_LOG
 * 
 * 
 * 2- TR_AU_TAVERBACAO_COMPLEM_ATM
 * 
 * 
 * 
 * TR_AU_TDESTINO
 * 
 * TR_AU_TITEM_DESTINO
 * 
 * 
 * */

SELECT * FROM bilhet.TBIL_LOG_TRIGGER tlt 
WHERE CTL_AVERB IN (482133287
)


SELECT *
FROM SYSCAT.TRIGGERS
WHERE TRIGNAME   LIKE '%AVERBACAO%' 
  AND TABCREATOR = @table_schema
  AND TRIGNAME   = @trigger_name
  AND TRIGSCHEMA = @trigger_schema
  

  
  