/*cancelar fatura*/

SELECT * FROM bilhet.TBIL_FATURA tf 
WHERE SEQ_NUMER_FAT = 7000342021
ORDER BY SEQ_NUMER_FAT  DESC 




UPDATE bilhet.TBIL_FATURA SET
--NUM_FATUR_CIA = NULL,
SIT_FATUR = 6,
SIT_ENVIO_FAT = 1,
IDT_ENVIO_CBR = 'C'
--CTL_GRUPO_FAT = NULL 
WHERE SEQ_NUMER_FAT IN (7000333187)


COMMIT 



SELECT * FROM PAMAIS.TCRP_HIERARQUIA_COMEC_PRODR thcp 
WHERE num_hierq = 41
AND CTL_PRODR = 1453


SELECT * FROM bilhet.TBIL_SITUACAO

