SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE tp.CTL_PEJUR_CIA = 17341
AND tp.NUM_RAMO_SEG = 1
AND tp.TIP_NEGOC = 1
AND tp.NUM_APOLI > 0
AND DAT_FIM_VIG >= '2024-02-29'

SELECT AP.SEQ_NUMER_AVB
,a.COD_CNPJ_TOMADOR
, a.DHR_EMBAR 
, COALESCE ((SELECT nom_pesso FROM PAMAIS.TCRP_PESSOA WHERE cod_docum_pri = a.COD_CNPJ_TOMADOR),'')
,ap.NUM_ETAPA_AVB 
,ap.SEQ_NUMER_FAT 
,A.VLR_EMBAR 
FROM BILHET.TBIL_AVERBACAO A
--INNER JOIN BILHET.TBIL_AVERBACAO_INDICE AI ON AI.NUM_AVERB_PAM = A.NUM_AVERB_PAM 
INNER JOIN BILHET.TBIL_RELAC_AVERB_PROPT AP ON AP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB 
WHERE AP.SEQ_NUMER_PRS IN(508582)
AND A.DHR_EMBAR BETWEEN '2024-02-01 00:00:00' AND '2024-02-29 23:59:59'
--AND A.COD_CNPJ_TOMADOR = 84046101001670
ORDER BY a.COD_CNPJ_TOMADOR 

UPDATE bilhet.TBIL_RELAC_AVERB_PROPT SET
NUM_ETAPA_AVB = 1
,SEQ_NUMER_FAT = NULL
WHERE NUM_ETAPA_AVB = 4
AND SEQ_NUMER_PRS IN
(508582)
AND SEQ_NUMER_AVB IN ( SELECT A.SEQ_NUMER_AVB FROM BILHET.TBIL_AVERBACAO A
INNER JOIN BILHET.TBIL_AVERBACAO_INDICE AI ON AI.NUM_AVERB_PAM = A.NUM_AVERB_PAM 
INNER JOIN BILHET.TBIL_RELAC_AVERB_PROPT AP ON AP.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB 
WHERE AP.SEQ_NUMER_PRS IN
(508582)
AND A.DHR_EMBAR BETWEEN '2024-02-01' AND '2024-02-29')

 COMMIT

SELECT * FROM  bilhet.tbil_vigencia_proposta_credb
    WHERE SEQ_CREDB_PRS IN (
    SELECT b.SEQ_CREDB_PRS FROM bilhet.tbil_proposta_credito_debito a INNER JOIN bilhet.tbil_vigencia_proposta_credb B
    ON b.SEQ_CREDB_PRS = a.SEQ_CREDB_PRS 
    WHERE a.SEQ_NUMER_PRS IN
(508582)    
	AND b.DAT_INICI_VIG >= '2024-02-01'
	AND b.DAT_FIM_VIG <= '2024-02-29'
    )

 
 /*VOLTA DEBITO E CREDITO*/
    UPDATE bilhet.tbil_vigencia_proposta_credb SET 
    SEQ_NUMER_fat = NULL 
    WHERE SEQ_CREDB_PRS IN (
    SELECT b.SEQ_CREDB_PRS FROM bilhet.tbil_proposta_credito_debito a INNER JOIN bilhet.tbil_vigencia_proposta_credb B
    ON b.SEQ_CREDB_PRS = a.SEQ_CREDB_PRS 
    WHERE a.SEQ_NUMER_PRS IN
(508582)
	AND b.DAT_INICI_VIG >= '2024-02-01'
	AND b.DAT_FIM_VIG <= '2024-02-29'
    )


 
/*CANCELAR FATURA*/ 
SELECT * FROM bilhet.TBIL_FATURA tf 
WHERE SEQ_NUMER_PRS IN(508582)
AND NUM_MES_CPT = 202402
ORDER BY SEQ_NUMER_FAT DESC 

UPDATE BILHET.TBIL_FATURA SET 
IDT_ENVIO_CBR ='C'
,NUM_MOTIV_SIT =6
,SIT_FATUR =6
,NUM_FATUR_CIA = NULL 
WHERE SEQ_NUMER_PRS IN
(508582)
AND NUM_MES_CPT = 202402

COMMIT

/* LIMPAR TABELA MOVIM PARA FATURAS CANCELADAS*/
DELETE FROM BILHET.TBIL_MOVIM_FATURA 
WHERE SEQ_NUMER_FAT IN (
SELECT SEQ_NUMER_FAT  FROM BILHET.TBIL_FATURA tf 
WHERE IDT_ENVIO_CBR = 'C'
AND NUM_MOTIV_SIT =6
AND NUM_FATUR_CIA IS NULL 
AND SEQ_NUMER_PRS  IN
(508582)
AND NUM_MES_CPT = 202402
)

COMMIT

SELECT  * FROM bilhet.TBIL_RELAC_AVERB_PROPT rap INNER JOIN bilhet.TBIL_AVERBACAO a 
ON a.SEQ_NUMER_AVB = rap.SEQ_NUMER_AVB 
WHERE rap.SEQ_NUMER_PRS = 508582
AND a.DHR_EMBAR BETWEEN '2024-02-01 00:00:00' AND '2024-02-24 23:59:59'
AND SUBSTR(a.COD_CNPJ_TOMADOR,1,8) = '60500121'
ORDER BY a.COD_CNPJ_TOMADOR


60500121001368
132.539,65

60500121001449
1.138.964,26


         SELECT * FROM bilhet.TBIL_VALOR_SOMA_TIPO_TAR_EMBAR tvstte 
         WHERE SEQ_NUMER_FAT = 7000325422

SELECT *  FROM bilhet.TBIL_FATURA
where ctl_pesso_dic = 0
WHERE SEQ_NUMER_FAT in( 7000351410, 7000351407, 7000351402)
         
SELECT * FROM pamais.TCRP_PESSOA tp 
WHERE ctl_pesso IN (1137887,1143177)


SELECT * FROM V_BSEG_PROPOSTA