--DELETAR FATURAS QUE TIVERAM ERRO DE CONSTRINT



--TIP_ALERT_DDO 2   CORREÇÃO URGENTE
--SELECT * FROM GEDAD.TDAD_TIPO_ALERTA_VALID_DADO ttavd  

--TIP_VALID_DD = 7 Proposta em processamento da bilhetagem
-- SELECT * FROM GEDAD.TDAD_TIPO_VALID_DADO ttvd 

--NUM_TAREF_VAL 87  Controle de concorrência de processamento da bilhetagem
--SELECT * FROM GEDAD.TDAD_TAREFA_VALIDACAO_DADO ttvd 



/*VERIFICAR SE EXISTE NUM_SEQUE_PRS NA TABELA ERROS DE PROCESSAMENTO*/
SELECT * FROM gedad.tdad_procs_propt_bilhe
WHERE SEQ_NUMER_PRS IN (502117)
CTL_CONTR_TAF = 25678438 -- ESSE CÓDIGO VEM DO LOG DA APLICAÇÃO CAMPO V_OUT_RESULT 



SELECT * FROM bilhet.TBIL_FATURA 
WHERE  SEQ_NUMER_FAT = 7000225052 

SELECT * FROM bilhet.TBIL_CONTROLE_ENVIO_COBRANCA
WHERE  SEQ_NUMER_FAT = 7000225052 

SEQ_NUMER_PRS = 501942

SELECT * FROM  gedad.tdad_contr_tarefa_validacao
WHERE CTL_CONTR_TAF = 25678190


SELECT * FROM gedad.tdad_tarefa_validacao_vigen
WHERE NUM_TAREF_VAL = 87




ORDER BY SEQ_NUMER_AVB 

SELECT * FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE 
SELECT * FROM BILHET.V_BIL_AVERBACAO vba 
WHERE  SEQ_NUMER_PRS IN (501223)
AND SEQ_NUMER_FAT = 7000222223


SELECT * FROM bilhet.TBIL_RELAC_VISAO_PERCU_PADRA trvpp 
WHERE  SEQ_NUMER_PRS IN (501223)
AND SEQ_NUMER_FAT = 7000222223

SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE --SEQ_NUMER_PRS in(501666,501151)
NUM_APOLI in(3836006513854,
3836006611054
)


550013431 


select * FROM BILHET.TBIL_RELAC_VISAO_PERCU_PADRA A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
											FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN (503433,437653) 

SELECT *  FROM BILHET.TBIL_RELAC_VISAO_PROPT A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
    										FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN (503433,437653)


SELECT * FROM BILHET.TBIL_RELAC_VISAO_PERCU_PROPT A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
											FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN (503433,437653)



/**/

delete FROM BILHET.TBIL_RELAC_VISAO_PERCU_PADRA A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
											FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN ( 501151,501666) 

commit


delete FROM BILHET.TBIL_RELAC_VISAO_PERCU_PROPT A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
											FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN ( 501151,501666) 

commit

delete  FROM BILHET.TBIL_RELAC_VISAO_PROPT A 
WHERE A.SEQ_NUMER_PRS NOT IN ( SELECT SEQ_NUMER_PRS FROM GEDAD.V_DAD_CONSULTA_PROCS_PROPT_BILHE )
AND (A.SEQ_NUMER_PRS, A.SEQ_NUMER_AVB) IN (SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB 
    										FROM BILHET.V_BIL_AVERBACAO B WHERE B.SEQ_NUMER_FAT IS NULL)
AND A.SEQ_NUMER_PRS IN ( 501151,501666) 


COMMIT 

502958




SELECT B.SEQ_NUMER_PRS, B.SEQ_NUMER_AVB , SEQ_NUMER_FAT 
    FROM BILHET.V_BIL_AVERBACAO B 
    WHERE B.SEQ_NUMER_FAT IS NULL
AND SEQ_NUMER_PRS in(500515)






Caso novo:
Apólices 3836006114154 = 499907, 499909
 3836001817055 = 499909

 Apólices: 3836006740354  = 501932
 3836001969355 =501934


 SELECT a.SEQ_NUMER_AVB, a.SEQ_NUMER_PRS 
 FROM BILHET.TBIL_RELAC_AVERB_PROPT a
 WHERE a.SEQ_NUMER_AVB IS NOT NULL
 AND a.SEQ_NUMER_PRS=502228
 AND NOT EXISTS (SELECT 1 
 					FROM BILHET.TBIL_AVERBACAO B
                  	WHERE B.SEQ_NUMER_AVB = A.SEQ_NUMER_AVB
                  ) WITH UR

                  
                  
 SELECT * FROM bilhet.TBIL_AVERBACAO ta 
WHERE NUM_AVERB_PAM IN (397796689,	397796690)	 



SELECT * FROM DBPROD.AVERBACAO 
SELECT cod_averb_ofc, count(*) a FROM DBPROD.AVERBACAO_OFICIAL 
GROUP BY cod_averb_ofc
HAVING count(*) > 1


SELECT * FROM TDOWNLOAD_ARQUIVO ta 
