/* TECNICO */	
	SELECT 
	tp.NUM_APOLI AS Apolice
	,TO_CHAR(tp.dat_inici_vig,'dd/mm/yyyy') AS Inicio_Vigencia
	,TO_CHAR(tp.dat_fim_vig,'dd/mm/yyyy') AS Fim_Vigencia
	,(SELECT nom_pesso FROM PAMAIS.TCRP_PESSOA tp WHERE CTL_PESSO = tp.ctl_pejur_cia ) AS Seguradora
	,(SELECT nom_pesso FROM PAMAIS.TCRP_PESSOA tp WHERE CTL_PESSO = tp.ctl_pesso_cli ) AS Segurado
	,(SELECT nom_pesso FROM PAMAIS.TCRP_PESSOA tp WHERE CTL_PESSO = tp.ctl_pesso_cog ) AS Coligada  
	,(SELECT sig_ramo FROM RAMO WHERE num_ramo = tp.num_ramo_seg) AS ramo
	,(SELECT NOM_NEGOC FROM PAMAIS.TCRP_TIPO_NEGOCIO WHERE tip_negoc = tp.tip_negoc) AS Negocio
	,( SELECT   
		CASE 
			WHEN seq_numer_prs IS not null THEN 'S'
			
			ELSE 'N'
		END
		FROM BILHET.TBIL_PROPOSTA_AJUSTAVEL WHERE SEQ_NUMER_PRS = TP.SEQ_NUMER_PRS
	) AS AJ
	,tts.NOM_TECNI AS Tecnico
	FROM bilhet.TBIL_PROPOSTA tp
		,bilhet.TBIL_RELAC_TECNICO_PROPOSTA trtp
		,bilhet.TBIL_TECNICO_SEGURO tts
	WHERE trtp.SEQ_NUMER_PRS = tp.SEQ_NUMER_PRS 
		AND trtp.NUM_TECNI = tts.NUM_TECNI 
		AND	tp.DAT_FIM_VIG > CURRENT TIMESTAMP  
	--AND tp.dat_inici_vig BETWEEN TO_DATE('20220801000000','yyyymmddhh24miss') AND TO_DATE('20220831235959','yyyymmddhh24miss')
	--AND tps.DAT_EMISS BETWEEN TO_DATE('20220801000000','yyyymmddhh24miss') AND TO_DATE('20220831235959','yyyymmddhh24miss')
	
	SELECT * FROM bilhet.TBIL_TECNICO_SEGURO tts 
	
	SELECT * FROM bilhet.TBIL_TECNICO_SEGURO tts 
	SELECT * FROM bilhet.TBIL_RELAC_TECNICO_PROPOSTA trtp 
	WHERE dat_inici_vig BETWEEN TO_DATE('20220801000000','yyyymmddhh24miss') AND TO_DATE('20220831235959','yyyymmddhh24miss')
	SELECT * FROM PAMAIS.TCRP_TIPO_NEGOCIO ttn 
	
	SELECT * FROM bilhet.TBIL_PROPOSTA
	
	
	SELECT * FROM pamais.TCRP_HIERARQUIA_COMEC_PRODR thcp 
	SELECT * FROM SEGURO.TSEG_PROPT_CORRETOR
	SELECT * FROM SEGURO.TSEG_RELAC_CORRETOR_FILIAL
			
	SELECT * FROM pamais.CRP_DIRET_FILIAL_PAMCARY 
	SELECT * FROM pamais.TCRP_DIRETORIA_NEGOCIO tdn  
	
,(SELECT *--d.NOM_DIRET_NEG ||'-'|| e.SIG_FILIA_NEG  
		FROM SEGURO.TSEG_PROPT_CORRETOR a
		, SEGURO.TSEG_RELAC_CORRETOR_FILIAL b
		,pamais.TCRP_FILIAL_NEGOCIO d 
		,pamais.TCRP_DIRET_FILIAL_PAMCARY e
		,pamais.tCRP_DIRETORIA_NEGOCIO f
	WHERE a.NUM_PROPT = 22004508
	AND a.CTL_CORRE = 214482
	AND a.CTL_CORRE = b.CTL_CORRE 
	AND b.NUM_FILIA_NEG = d.NUM_FILIA_NEG
	AND d.num_filia_neg = e.num_filia_neg
	AND e.NUM_DIRET_NEG = f.NUM_DIRET_NEG 
	--AND d.NUM_DIRET_NEG = c.NUM_DIRET_NEG
	--AND e.NUM_FILIA_NEG = c.NUM_FILIA_NEG) AS Hierarquia
	
