SELECT CLIENTE.COD_DOCUM_PRI,
	   CLIENTE.NOM_PESSO,
     SEGURADO.NOM_PESSO,
     P.NUM_APOLI,
     R.SIG_RAMO,
     COUNT(1) TOTAL
FROM BILHET.TBIL_AVERBACAO A
	 ,BILHET.TBIL_PROPOSTA P
	 ,BILHET.TBIL_RELAC_AVERB_PROPT AP
	 ,PAMAIS.TCRP_PESSOA CLIENTE
   ,PAMAIS.TCRP_PESSOA SEGURADO
   ,PAMAIS.TCRP_RAMO_SEGURO R
WHERE 1=1
AND P.SEQ_NUMER_PRS = AP.SEQ_NUMER_PRS
AND A.SEQ_NUMER_AVB = AP.SEQ_NUMER_AVB
AND CLIENTE.CTL_PESSO = P.CTL_PESSO_CLI
AND SEGURADO.CTL_PESSO = P.CTL_PEJUR_CIA
AND R.NUM_RAMO_SEG = P.NUM_RAMO_SEG
AND AP.VLR_IS = 60000
AND A.VLR_EMBAR = 60000
AND A.DHR_ALTER BETWEEN '2021-03-17 00:00:00' AND '2021-03-31 24:00:00'
AND  P.NUM_APOLI > 0
GROUP BY CLIENTE.COD_DOCUM_PRI,
	   CLIENTE.NOM_PESSO,
     SEGURADO.NOM_PESSO,
     P.NUM_APOLI,
     R.SIG_RAMO


SELECT * FROM PAMAIS.TCRP_RAMO_SEGURO