SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE NUM_APOLI = 3762900063621 


/*VERIFICAR SE EXISTE NUM_SEQUE_PRS NA TABELA ERROS DE PROCESSAMENTO*/
SELECT DISTINCT seq_numer_prs FROM gedad.tdad_procs_propt_bilhe
WHERE CTL_CONTR_TAF in (34604011
)  -- ESSE C�DIGO VEM DO LOG DA APLICA��O CAMPO V_OUT_RESULT 
ORDER BY SEQ_NUMER_prs  ASC  

	

/* PROCESSO DE EXCLUS�O DE PROPOSTA PERDIDAS NAS TABELAS DE PROCESSAMENTO*/

/*DELETE 1*/
	DELETE
FROM
	bilhet.TBIL_RELAC_VISAO_PERCU_PADRA
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
		tp.SEQ_NUMER_PRS IN 
(
506531
,506880
,506912
)
AND trap.NUM_ETAPA_AVB = 1
AND trap.SEQ_NUMER_FAT + 0 IS NULL);

commit

/*DELETE 2*/
--
delete FROM bilhet.TBIL_RELAC_VISAO_PERCU_PROPT	
WHERE
(SEQ_NUMER_PRS,
SEQ_NUMER_AVB) IN (
SELECT
	trap.SEQ_NUMER_PRS,
	ta.SEQ_NUMER_AVB
FROM
	bilhet.TBIL_AVERBACAO ta
INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
	trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
INNER JOIN bilhet.TBIL_PROPOSTA tp ON
	tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
WHERE
		tp.SEQ_NUMER_PRS IN 
(
506531
,506880
,506912

)
	AND trap.NUM_ETAPA_AVB = 1
	AND trap.SEQ_NUMER_FAT + 0 IS NULL);
--


/*DELETE 3*/
DELETE
FROM
	BILHET.TBIL_RELAC_VISAO_PROPT
WHERE
	(SEQ_NUMER_PRS,
	SEQ_NUMER_AVB) IN (
	SELECT
		trap.SEQ_NUMER_PRS,
		ta.SEQ_NUMER_AVB
	FROM
		bilhet.TBIL_AVERBACAO ta
	INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT trap ON
		trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB
	INNER JOIN bilhet.TBIL_PROPOSTA tp ON
		tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS
	WHERE
		tp.SEQ_NUMER_PRS IN 
(
506531
,506880
,506912

)
AND trap.NUM_ETAPA_AVB = 1
		AND trap.SEQ_NUMER_FAT + 0 IS NULL);

COMMIT


/*CONSULTA DEBITO CREDITO*/
SELECT * FROM  bilhet.tbil_vigencia_proposta_credb
    WHERE SEQ_CREDB_PRS IN (
    SELECT b.SEQ_CREDB_PRS FROM bilhet.tbil_proposta_credito_debito a INNER JOIN bilhet.tbil_vigencia_proposta_credb B
    ON b.SEQ_CREDB_PRS = a.SEQ_CREDB_PRS 
    WHERE a.SEQ_NUMER_PRS IN(504276)
	AND b.DAT_INICI_VIG >= '2024-03-01'
	AND b.DAT_FIM_VIG <= '2024-03-31'
    )


 /*VOLTA DEBITO E CREDITO*/
    UPDATE bilhet.tbil_vigencia_proposta_credb SET 
    SEQ_NUMER_fat = NULL 
    WHERE SEQ_CREDB_PRS IN (
    SELECT b.SEQ_CREDB_PRS FROM bilhet.tbil_proposta_credito_debito a INNER JOIN bilhet.tbil_vigencia_proposta_credb B
    ON b.SEQ_CREDB_PRS = a.SEQ_CREDB_PRS 
    WHERE a.SEQ_NUMER_PRS IN(506376)
	AND b.DAT_INICI_VIG >= '2024-02-01'
	AND b.DAT_FIM_VIG <= '2024-02-29'
    )



/*CANCELA FATURA*/	
SELECT * FROM BILHET.TBIL_FATURA tf 
WHERE SEQ_NUMER_PRS = 504276
AND NUM_MES_CPT = 202403
ORDER BY DHR_FATUR DESC  


UPDATE BILHET.TBIL_FATURA SET
SIT_FATUR = 6
,IDT_ENVIO_CBR = 'C'
,NUM_MOTIV_SIT = 6
WHERE SEQ_NUMER_PRS = 506377
AND NUM_MES_CPT = 202402


SELECT * FROM bilhet.TBIL_TIPO_TARIFA_PROPOSTA tttp 



UPDATE bilhet.TBIL_TIPO_TARIFA_PROPOSTA SET 
NOM_APELI_TAR = 'Desconto Comercial[Exc.Tx.Roubo, Tx.Emb e C.Risco]'
WHERE NUM_TARIF = 12

COMMIT



SELECT * FROM bilhet.TBIL_AVERBACAO ta 
WHERE DHR_ALTER >= '2024-04-11'
AND COD_CNPJ_TOMADOR  = '' x'



SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE tp.num_apoli in (3836900028055,3836901107854 )