

SELECT * 
FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
	INNER JOIN bilhet.TBIL_AVERBACAO ta ON trap.SEQ_NUMER_AVB = ta.SEQ_NUMER_AVB 
	INNER JOIN bilhet.TBIL_AVERBACAO_INDICE tai ON tai.NUM_AVERB_PAM = ta.NUM_AVERB_PAM 
WHERE ta.DHR_EMBAR BETWEEN '2023-12-01 00:00:00' AND '2023-12-31 23:59:59'
AND trap.SEQ_NUMER_FAT IS null 
AND trap.SEQ_NUMER_PRS IN (506611)
ORDER BY ta.SEQ_NUMER_AVB 



/*DELETE DAS AVERBA��ES DE COMPETENCIAS ANTERIORES QUE N�O DEVEM SER PROCESSADAS*/
DELETE FROM bilhet.TBIL_RELAC_AVERB_PROPT trap
WHERE trap.seq_numer_avb IN (SELECT SEQ_NUMER_AVB 
								FROM bilhet.TBIL_AVERBACAO 
								WHERE DHR_EMBAR BETWEEN '2023-12-01 00:00:00' AND '2023-12-31 23:59:59')
AND trap.SEQ_NUMER_FAT IS null 
AND trap.SEQ_NUMER_PRS IN (506611)

COMMIT 


SELECT * FROM APLTRANS.AVERBACAO_INDICE 
WHERE CTL_AVERB = 20461328