SELECT 
    PRS.SEQ_NUMER_PRS AS SEQUENCIA_PROPOSTA ,
    PRS.SEQ_PROPT_ATG AS SEQUENCIA_PROPOSTA_ANTIGA,
    PRS.NUM_APOLI AS APOLICE ,
    PRS.NUM_PROPT AS PROPOSTA ,
    PRS.NUM_RAMO_SEG AS NUMERO_RAMO,
    RAM.SIG_RAMO AS SIGLA_RAMO ,
    PRS.CTL_PEJUR_CIA AS SEQUENCIA_CIA ,
    CIA.NOM_CIA_SEGURADORA AS RAZAO_SOCIAL_CIA,
    PCI.NOM_FANTS AS NOME_FANTASIA_CIA,
    PCI.COD_DOCUM_PRI AS DOCUMENTO_CIA,
    PRS.CTL_SUCUR AS SEQUENCIA_SUCURSAL ,
    SUC.NOM_SUCUR_CIA AS NOME_SUCURSAL ,
    PRS.CTL_CORRE AS SEQUENCIA_CORRETOR ,
    COR.NUM_CORRE_PAM AS NUMERO_CORRETOR_PAMCARY ,
    COR.NOM_FANTS_COR AS NOME_FANTASIA_CORRETOR ,
    PRS.CTL_PESSO_CLI AS SEQUENCIA_CLIENTE ,
    CLI.NOM_PESSO AS RAZAO_SOCIAL_CLIENTE ,
    CLI.NOM_FANTS AS NOME_FANTASIA_CLIENTE ,
    CLI.COD_DOCUM_PRI AS DOCUMENTO_CLIENTE ,
    PRS.DAT_INICI_VIG AS INICIO_VIGENCIA ,
    PRS.DAT_FIM_VIG AS FIM_VIGENCIA ,
    PRS.NUM_ETAPA_PRS AS NUMERO_SITUACAO_PROPOSTA ,
    ETP.NOM_ETAPA_PRS AS NOME_SITUACAO_PROPOSTA ,
    PRS.NUM_PERIO AS NUMERO_PERIODO_PROPOSTA ,
    PRD.NOM_PERIO AS NOME_PERIODO_PROPOSTA ,
    PRS.NUM_MOEDA_PRS AS NUMERO_MOEDA_PROPOSTA ,
    MOE.SIG_SIMBO_MOE AS SIGLA_SIMBOLO_MOEDA ,
    MOE.DES_MOEDA AS NOME_MOEDA ,
    BILHET.FC_DIA_VENCI_PRS(PRS.SEQ_NUMER_PRS,3) AS VENCIMENTO_MENSAL ,
    BILHET.FC_DIA_VENCI_PRS(PRS.SEQ_NUMER_PRS,1) AS VENCIMENTO_PRIMEIRA_QUINZENA ,
    BILHET.FC_DIA_VENCI_PRS(PRS.SEQ_NUMER_PRS,2) AS VENCIMENTO_SEGUNDA_QUINZENA ,
    PRS.TIP_AVERB AS TIPO_AVERBACAO ,
    AVB.NOM_TIPO_AVB AS NOME_TIPO_AVERBACAO ,
    PRS.TIP_NEGOC AS TIPO_NEGOCIO ,
    NEG.NOM_NEGOC AS NOME_NEGOCIO ,
    PRS.NUM_COBER_BAS AS NUMERO_COBERTURA_BASICA ,
    COB.NOM_COBER_BAS AS NOME_COBERTURA_BASICA ,
    PRS.DHR_ALTER AS DATA_ALTERACAO ,
    PRS.CTL_PESSO_COG AS SEQUENCIA_COLIGADO ,
    COG.NOM_FANTS AS NOME_FANTASIA_COLIGADO ,
    COG.NOM_PESSO AS RAZAO_SOCIAL_COLIGADO ,
    COG.COD_DOCUM_PRI AS DOCUMENTO_COLIGADO ,
    PRS.STA_PAMTX AS STATUS_PAMTAX ,
    PHI.NUM_HIERQ AS NUMERO_HIERARQUIA ,
    PAMAIS.FC_RECUPERA_NOMHIE(PHI.NUM_HIERQ) AS NOME_HIERARQUIA ,
    PHI.CTL_PRODR AS SEQUENCIA_PRODUTOR ,
    PDR.NOME AS NOME_PRODUTOR ,
    CASE
        WHEN AJS.NUM_PERIO IS NULL THEN 'N'
        WHEN AJS.NUM_PERIO IS NOT NULL THEN 'S'
    END AS AJUSTAVEL ,
    AJS.NUM_PERIO AS NUMERO_PERIODO_AJUSTAVEL ,
    PAJ.NOM_PERIO AS NOME_PERIODO_AJUSTAVEL ,
    AJS.QTD_PARCE_SEG AS QUANTIDADE_PARCELA_AJUSTAVEL ,
    AJS.VLR_PREMI_FIX AS VALOR_PREMIO_FIXO ,
    TEC.NUM_TECNI AS NUMERO_TECNICO_FIXO,
    TEC.NOM_TECNI AS TECNICO_FIXO ,
    TCN.NUM_TECNI AS NUMERO_TECNICO_TEMPORARIO,
    TCN.NOM_TECNI AS TECNICO_TEMPORARIO,
	COALESCE ((
        SELECT
            rsc.NUM_CORRE_SUC
        FROM
            SEGURO.TSEG_COCORRETAGEM tc
        INNER JOIN SEGURO.TSEG_RELAC_PRC_CORRETOR trpc ON
            trpc.CTL_PEDID_RGT = tc.CTL_PEDID_RGT
        INNER JOIN PAMAIS.TCRP_CORRETOR_PARCEIRO_LETRA cpl ON
            CPL.CTL_CORRE = trpc.CTL_CORRE
        INNER JOIN pamais.TCRP_RELAC_SUCURSAL_CORRETOR rsc ON
            rsc.CTL_CORRE = cpl.CTL_CORRE
        WHERE
            tc.DAT_FIM_VIG IS NULL
            AND tc.NUM_PROPT = PRS.NUM_PROPT
            AND rsc.CTL_SUCUR = PRS.CTL_SUCUR
        LIMIT 1),0) AS NUMERO_CORRETOR_SUCURSAL
FROM
    BILHET.TBIL_PROPOSTA PRS
INNER JOIN APLBIL.V_CRP_RAMO_SEGURO RAM ON
    ( RAM.NUM_RAMO_SEG = PRS.NUM_RAMO_SEG )
INNER JOIN APLBIL.V_CRP_CIA_SEGURADORA CIA ON
    ( CIA.CTL_CIA_SEGURADORA = PRS.CTL_PEJUR_CIA )
INNER JOIN APLBIL.V_CRP_PESSOA PCI ON
    ( PCI.CTL_PESSO = CIA.CTL_CIA_SEGURADORA )
LEFT JOIN APLBIL.V_CRP_SUCURSAL SUC ON
    ( SUC.CTL_SUCUR = PRS.CTL_SUCUR )
INNER JOIN APLBIL.V_CRP_CORRETOR_PARCEIRO COR ON
    ( COR.CTL_CORRE = PRS.CTL_CORRE )
INNER JOIN APLBIL.V_CRP_PESSOA CLI ON
    ( CLI.CTL_PESSO = PRS.CTL_PESSO_CLI )
INNER JOIN BILHET.TBIL_SITUA_ETAPA_PROPOSTA ETP ON
    ( ETP.NUM_ETAPA_PRS = PRS.NUM_ETAPA_PRS )
INNER JOIN BILHET.TBIL_PERIODO PRD ON
    ( PRD.NUM_PERIO = PRS.NUM_PERIO )
INNER JOIN APLBIL.V_CRP_MOEDA MOE ON
    ( MOE.NUM_MOEDA = PRS.NUM_MOEDA_PRS )
INNER JOIN BILHET.TBIL_TIPO_AVERBACAO AVB ON
    ( AVB.TIP_AVERB = PRS.TIP_AVERB )
INNER JOIN APLBIL.V_CRP_TIPO_NEGOCIO NEG ON
    ( NEG.TIP_NEGOC = PRS.TIP_NEGOC )
LEFT JOIN BILHET.TBIL_COBERTURA_BASICA COB ON
    ( COB.NUM_COBER_BAS = PRS.NUM_COBER_BAS )
LEFT JOIN APLBIL.V_CRP_PESSOA COG ON
    ( COG.CTL_PESSO = PRS.CTL_PESSO_COG )
LEFT JOIN BILHET.TBIL_HIERQ_PRODR_PROPT PHI ON
    ( PHI.SEQ_NUMER_PRS = PRS.SEQ_NUMER_PRS )
LEFT JOIN APLBIL.V_CRP_PRODUTOR PDR ON
    ( PDR.CTL_PRODR = PHI.CTL_PRODR )
LEFT JOIN BILHET.TBIL_PROPOSTA_AJUSTAVEL AJS ON
    ( AJS.SEQ_NUMER_PRS = PRS.SEQ_NUMER_PRS )
LEFT JOIN BILHET.TBIL_PERIODO PAJ ON
    ( PAJ.NUM_PERIO = AJS.NUM_PERIO )
LEFT JOIN BILHET.TBIL_RELAC_TECNICO_PROPOSTA TFX ON
    ( PRS.SEQ_NUMER_PRS = TFX.SEQ_NUMER_PRS
        AND TFX.STA_TECNI_FIX = 'S'
        AND TFX.DAT_FIM_VIG IS NULL )
LEFT JOIN BILHET.TBIL_RELAC_TECNICO_PROPOSTA TPR ON
    ( PRS.SEQ_NUMER_PRS = TPR.SEQ_NUMER_PRS
        AND TPR.STA_TECNI_FIX = 'N'
        AND CURRENT_DATE BETWEEN TPR.DAT_INICI_VIG AND TPR.DAT_FIM_VIG )
LEFT JOIN BILHET.TBIL_TECNICO_SEGURO TEC ON
    ( TFX.NUM_TECNI = TEC.NUM_TECNI )
LEFT JOIN BILHET.TBIL_TECNICO_SEGURO TCN ON
    ( TPR.NUM_TECNI = TCN.NUM_TECNI )
WHERE   PRS.CTL_PEJUR_CIA = 37960
--AND prs.dat_fim_vig >= '2024-10-01'
AND PRS.NUM_RAMO_SEG NOT IN (69)
AND prs.num_propt in(509610)


        SELECT *            
        FROM
            SEGURO.TSEG_COCORRETAGEM tc
        INNER JOIN SEGURO.TSEG_RELAC_PRC_CORRETOR trpc ON
            trpc.CTL_PEDID_RGT = tc.CTL_PEDID_RGT
        INNER JOIN PAMAIS.TCRP_CORRETOR_PARCEIRO_LETRA cpl ON
            CPL.CTL_CORRE = trpc.CTL_CORRE
        INNER JOIN pamais.TCRP_RELAC_SUCURSAL_CORRETOR rsc ON
            rsc.CTL_CORRE = cpl.CTL_CORRE
        WHERE tc.DAT_FIM_VIG IS NULL
        	AND tc.NUM_PROPT = 24004881
        	AND rsc.CTL_SUCUR = 235
		
            
            SELECT * FROM pamais.TCRP_RELAC_SUCURSAL_CORRETOR
            WHERE CTL_CORRE  IN (214486,4593)
            AND CTL_SUCUR = 242
            
            SELECT * FROM PAMAIS.TCRP_CORRETOR_PARCEIRO_LETRA
            WHERE CTL_CORRE IN (214486,4593) 
            
            SELECT * FROM SEGURO.TSEG_RELAC_PRC_CORRETOR
            WHERE ctl_pedid_rgt = 68372
            
            SELECT * FROM seguro.TSEG_COCORRETAGEM 
            WHERE NUM_PROPT = 22007682
            
            
            
            SELECT NUM_APOLI, NUM_PROPT, CTL_SUCUR, CTL_PEJUR_CIA, * FROM bilhet.TBIL_PROPOSTA tp 
            WHERE num_apoli = 5400046367 

           
SELECT * FROM PAMAIS.CRP_PESSOA
WHERE COD_DOCUM_PRI = '01257995001610'

SELECT * FROM bilhet.TBIL_RELAC_PROPOSTA_DIVIS_CIA
WHERE SEQ_NUMER_PRS = 511237


SELECT * FROM BILHET.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 511237

select f.SEQ_NUMER_FAT, p.NOM_FANTS, p.COD_DOCUM_PRI, * from bilhet.tbil_fatura f INNER JOIN CRP_PESSOA p 
ON p.CTL_PESSO  = f.CTL_PESSO_DIC 
where seq_numer_fat in
(7000355302,
7000355299,
7000355298,
7000355296,
7000355293,
7000355292,
7000355290,
7000355286,
7000355285)


SELECT 	             
tf.seq_numer_fat,
							COALESCE(DIVIS.NOM_APELI_DIC || '(' || COLIGADO.NOM_FANTS || ')', DIVIS.NOM_APELI_DIC)  APELIDO,
			              DIVIS.CTL_PESSO_DIC  ID_PESSOA, 
			              PESSOA.NOM_FANTS     NOME, 
			              PESSOA.COD_DOCUM_PRI DOCUMENTO, 
			              DIVIS.SEQ_NUMER_PRS  PROPOSTA 
			          FROM 
			              BILHET.TBIL_RELAC_PROPOSTA_DIVIS_CIA DIVIS 
			              INNER JOIN V_CRP_PESSOA PESSOA ON DIVIS.CTL_PESSO_DIC = PESSOA.CTL_PESSO  
			              LEFT JOIN BIL_PROPOSTA PROPOSTA ON PESSOA.CTL_PESSO = PROPOSTA.CTL_PESSO_CLI 
			              LEFT JOIN V_CRP_PESSOA COLIGADO ON PROPOSTA.CTL_PESSO_COG = COLIGADO.CTL_PESSO
			              INNER JOIN bilhet.TBIL_FATURA tf ON tf.CTL_PESSO_DIC = DIVIS.CTL_PESSO_DIC 
			              WHERE DIVIS.SEQ_NUMER_PRS = 511237
			              AND TF.SEQ_NUMER_FAT in(7000355302,
7000355299,
7000355298,
7000355296,
7000355293,
7000355292,
7000355290,
7000355286,
7000355285)
			              
			              