
/*RECUPERA AVERBAÇÕES PARA PROCESSAMENTO SEM FATURAS*/
SELECT a.SEQ_NUMER_AVB 
, d.SEQ_NUMER_PRS 
--, e.SEQ_NUMER_FAT 
, b.NUM_AVERB_PAM 
, c.NUM_ETAPA_AVB 
, c.VLR_IS 
, a.DHR_EMBAR 
, a.SEQ_LOCAL_DES 
, a.STA_AVARI 
, a.IDT_TARIF 
, a.STA_FLUVI
, a.SEQ_LOCAL_INT 
, a.SEQ_LOCAL_ORI 
, a.STA_PERNA_DES 
, a.STA_PERNA_ORI 
, a.IDT_CARGA_DSC 
, a.TIP_ISENC_SEG 
, a.IDT_VEICU 
, d.CTL_PEJUR_CIA 
, d.NUM_COBER_BAS 
, d.CTL_PESSO_CLI 
, d.DAT_INICI_VIG 
, d.NUM_APOLI 
, d.NUM_PERIO 
, d.NUM_RAMO_SEG 
, d.NUM_ETAPA_PRS 
, d.TIP_AVERB 
, d.TIP_NEGOC 
--, e.DHR_FATUR 
--, e.DAT_VENCI_FAT 
--, e.NUM_MES_CPT 
--, e.SIT_FATUR 
--, e.SEQ_NUMER_FAT 
, f.NUM_DIA_VEC 
, f.NUM_PERIO_FAT 
, b.SIT_TRANS 
, b.VLR_EMBAR_TOT 
, b.VLR_PAMTX 
, origem.SEQ_NUMER_LOC
, origem.COD_IDENT_PAD 
, origem.SEQ_LOCAL_PAI 
, origem.STA_NINFO 
, origem.STA_URSUB 
, origem.TIP_LOCAL 
, destino.SEQ_NUMER_LOC 
, destino.COD_IDENT_PAD 
, destino.SEQ_LOCAL_PAI 
, destino.STA_NINFO 
, destino.STA_URSUB 
, destino.TIP_LOCAL 
FROM
BILHET.TBIL_AVERBACAO a
INNER JOIN BILHET.TBIL_AVERBACAO_INDICE b
ON a.NUM_AVERB_PAM = b.NUM_AVERB_PAM 
INNER JOIN BILHET.TBIL_RELAC_AVERB_PROPT c 
ON a.SEQ_NUMER_AVB   = c.SEQ_NUMER_AVB 
INNER JOIN BILHET.TBIL_PROPOSTA d 
ON c.SEQ_NUMER_PRS = d.SEQ_NUMER_PRS 
--INNER JOIN BILHET.TBIL_FATURA e 
--ON d.SEQ_NUMER_PRS = e.SEQ_NUMER_PRS 
INNER JOIN BILHET.TBIL_VENCIMENTO_FATURA_PROPT f 
ON d.SEQ_NUMER_PRS  = f.SEQ_NUMER_PRS
INNER JOIN BILHET.V_BIL_LOCALIDADE origem 
ON a.SEQ_LOCAL_ORI = origem.SEQ_NUMER_LOC
INNER JOIN BILHET.V_BIL_LOCALIDADE destino 
ON a.SEQ_LOCAL_DES = destino.SEQ_NUMER_LOC 
WHERE a.DHR_EMBAR <= '2021-11-30 23:59:59'
AND d.NUM_APOLI = 5400030111 --3836006319754--5400027717
AND c.NUM_ETAPA_AVB = 1
AND d.NUM_APOLI > 0
AND d.NUM_PERIO = 3
AND d.NUM_RAMO_SEG = 1
--AND e.SIT_FATUR <> 6
AND c.SEQ_NUMER_FAT IS NULL
--ORDER BY e.SEQ_NUMER_FAT DESC 

SELECT * 
FROM bilhet.TBIL_AVERBACAO ta
,bilhet.TBIL_RELAC_AVERB_PROPT trap
,bilhet.TBIL_PROPOSTA tp 
WHERE ta.SEQ_NUMER_AVB = trap.SEQ_NUMER_AVB  
AND tp.SEQ_NUMER_PRS = trap.SEQ_NUMER_PRS 
AND tp.NUM_APOLI = 5400030111 --5400027717 --3836006319754
AND trap.SEQ_NUMER_AVB IN (895351183,895156634)

SELECT * FROM BILHET.



SELECT * FROM BILHET.V_BIL_LOCALIDADE

, BILHET.V_BIL_LOCALIDADE
SELECT * FROM 



SELECT
	averbacao0_.SEQ_NUMER_AVB AS SEQ_NUME1_4_0_,
	proposta1_.SEQ_NUMER_PRS AS SEQ_NUME1_3_1_,
--	fatura5_.SEQ_NUMER_FAT AS SEQ_NUME1_2_2_,
--	vencimento6_.SEQ_NUMER_PRS AS SEQ_NUME1_13_3_,
	averbacaoi2_.NUM_AVERB_PAM AS NUM_AVER1_1_4_,
	localidade3_.SEQ_NUMER_LOC AS SEQ_NUME1_16_5_,
	localidade4_.SEQ_NUMER_LOC AS SEQ_NUME1_16_6_,
	averbacao0_.NUM_ETAPA_AVB AS NUM_ETAP2_4_0_,
	averbacao0_.SEQ_NUMER_PRS AS SEQ_NUME4_4_0_,
	averbacao0_.VLR_IS AS VLR_IS3_4_0_,
	averbacao0_1_.DHR_EMBAR AS DHR_EMBA1_0_0_,
	averbacao0_1_.SEQ_LOCAL_DES AS SEQ_LOC10_0_0_,
	averbacao0_1_.STA_AVARI AS STA_AVAR2_0_0_,
	averbacao0_1_.IDT_TARIF AS IDT_TARI3_0_0_,
	averbacao0_1_.STA_FLUVI AS STA_FLUV4_0_0_,
	averbacao0_1_.NUM_AVERB_PAM AS NUM_AVE11_0_0_,
	averbacao0_1_.SEQ_LOCAL_INT AS SEQ_LOC12_0_0_,
	averbacao0_1_.SEQ_LOCAL_ORI AS SEQ_LOC13_0_0_,
	averbacao0_1_.STA_PERNA_DES AS STA_PERN5_0_0_,
	averbacao0_1_.STA_PERNA_ORI AS STA_PERN6_0_0_,
	averbacao0_1_.IDT_CARGA_DSC AS IDT_CARG7_0_0_,
	averbacao0_1_.TIP_ISENC_SEG AS TIP_ISEN8_0_0_,
	averbacao0_1_.IDT_VEICU AS IDT_VEIC9_0_0_,
	proposta1_.CTL_PEJUR_CIA AS CTL_PEJU2_3_1_,
	proposta1_.NUM_COBER_BAS AS NUM_COBE3_3_1_,
	proposta1_.CTL_PESSO_CLI AS CTL_PESS4_3_1_,
	proposta1_.DAT_FIM_VIG AS DAT_FIM_5_3_1_,
	proposta1_.NUM_APOLI AS NUM_APOL6_3_1_,
	proposta1_.NUM_PERIO AS NUM_PERI7_3_1_,
	proposta1_.NUM_RAMO_SEG AS NUM_RAMO8_3_1_,
	proposta1_.NUM_ETAPA_PRS AS NUM_ETAP9_3_1_,
	proposta1_.TIP_AVERB AS TIP_AVE10_3_1_,
	proposta1_.TIP_NEGOC AS TIP_NEG11_3_1_,
--	fatura5_.DHR_FATUR AS DHR_FATU2_2_2_,
--	fatura5_.DAT_VENCI_FAT AS DAT_VENC3_2_2_,
--	fatura5_.NUM_MES_CPT AS NUM_MES_4_2_2_,
--	fatura5_.SIT_FATUR AS SIT_FATU5_2_2_,
--	fatura5_.SEQ_NUMER_PRS AS SEQ_NUME6_2_2_,
--	fatura5_.SEQ_NUMER_PRS AS SEQ_NUME6_3_0__,
--	fatura5_.SEQ_NUMER_FAT AS SEQ_NUME1_2_0__,
--	vencimento6_.NUM_DIA_VEC AS NUM_DIA_2_13_3_,
--	vencimento6_.NUM_PERIO_FAT AS NUM_PERI3_13_3_,
	averbacaoi2_.SIT_TRANS AS SIT_TRAN2_1_4_,
	averbacaoi2_.VLR_EMBAR_TOT AS VLR_EMBA3_1_4_,
	averbacaoi2_.VLR_PAMTX AS VLR_PAMT4_1_4_,
	localidade3_.COD_IDENT_PAD AS COD_IDEN2_16_5_,
	localidade3_.SEQ_LOCAL_PAI AS SEQ_LOCA6_16_5_,
	localidade3_.STA_NINFO AS STA_NINF3_16_5_,
	localidade3_.STA_URSUB AS STA_URSU4_16_5_,
	localidade3_.TIP_LOCAL AS TIP_LOCA5_16_5_,
	localidade4_.COD_IDENT_PAD AS COD_IDEN2_16_6_,
	localidade4_.SEQ_LOCAL_PAI AS SEQ_LOCA6_16_6_,
	localidade4_.STA_NINFO AS STA_NINF3_16_6_,
	localidade4_.STA_URSUB AS STA_URSU4_16_6_,
	localidade4_.TIP_LOCAL AS TIP_LOCA5_16_6_
FROM
	BILHET.TBIL_RELAC_AVERB_PROPT averbacao0_
LEFT OUTER JOIN BILHET.TBIL_AVERBACAO averbacao0_1_ ON
	averbacao0_.SEQ_NUMER_AVB = averbacao0_1_.SEQ_NUMER_AVB
INNER JOIN BILHET.TBIL_PROPOSTA proposta1_ ON
	averbacao0_.SEQ_NUMER_PRS = proposta1_.SEQ_NUMER_PRS
--LEFT OUTER JOIN BILHET.TBIL_FATURA fatura5_ ON
--	proposta1_.SEQ_NUMER_PRS = fatura5_.SEQ_NUMER_PRS
--LEFT OUTER JOIN BILHET.TBIL_VENCIMENTO_FATURA_PROPT vencimento6_ 
--	ON
--	fatura5_.SEQ_NUMER_PRS = vencimento6_.SEQ_NUMER_PRS
INNER JOIN BILHET.TBIL_AVERBACAO_INDICE averbacaoi2_ ON
	averbacao0_1_.NUM_AVERB_PAM = averbacaoi2_.NUM_AVERB_PAM
LEFT OUTER JOIN BILHET.V_BIL_LOCALIDADE localidade3_ ON
	averbacao0_1_.SEQ_LOCAL_ORI = localidade3_.SEQ_NUMER_LOC
LEFT OUTER JOIN BILHET.V_BIL_LOCALIDADE localidade4_ ON
	averbacao0_1_.SEQ_LOCAL_DES = localidade4_.SEQ_NUMER_LOC
WHERE
	averbacao0_1_.DHR_EMBAR <= '2023-05-31 23:59:59'
	AND proposta1_.NUM_APOLI = 5400034633
	AND averbacao0_.NUM_ETAPA_AVB = 1
	AND proposta1_.NUM_APOLI>0
	AND proposta1_.NUM_PERIO = 3
	AND proposta1_.NUM_RAMO_SEG = 1
ORDER BY
	--averbacao0_.SEQ_NUMER_AVB
	averbacao0_1_.DHR_EMBAR ASC
--	,fatura5_.SEQ_NUMER_FAT


SELECT tp.CTL_PESSO_CLI, tp.*  
FROM BILHET.TBIL_PROPOSTA tp, CRP_PESSOA a, bilhet.TBIL_RELAC_AVERB_PROPT trap 
WHERE a.CTL_PESSO = tp.CTL_PESSO_CLI 
AND trap.SEQ_NUMER_PRS = tp.SEQ_NUMER_PRS 
AND NOM_PESSO LIKE '%SEQUOIA%'
ORDER BY tp.DHR_ALTER DESC 


SELECT SEQ_NUMER_PRS, count(SEQ_NUMER_AVB ) AS averbacoes FROM bilhet.TBIL_RELAC_AVERB_PROPT trap 
WHERE SEQ_NUMER_FAT IS NULL 
GROUP BY SEQ_NUMER_PRS 
ORDER BY COUNT(SEQ_NUMER_AVB) DESC 

NUM_AVERB_CLI = 16674


SELECT * FROM bilhet.TBIL_PROPOSTA tp 
WHERE SEQ_NUMER_PRS = 503038


--sequoia ctl_pesso_cli = 16674
