/*VERIFICA CONTAS EM PROCESSAMENTO*/
select 
      c.num_apoli,
      b.seq_numer_prs,
      a.dhr_inici_prt,
      a.dhr_fim_prt,
      a.dhr_alter,
      a.cod_auten_usu,
      a.ctl_contr_taf,
      a.num_taref_val,
      c.*
from gedad.tdad_contr_tarefa_validacao a
, gedad.v_dad_consulta_procs_propt_bilhe b
, bilhet.tbil_proposta c
where a.dhr_fim_prt is null
and b.ctl_contr_taf = a.ctl_contr_taf
and c.seq_numer_prs = b.seq_numer_prs
order by a.dhr_inici_prt


(SELECT * FROM GEDAD.V_DAD_CONSULTA_SITUA_CONTR SC WHERE SC.NUM_TAREF_VAL = 87 AND SC.SIT_SITUA_CNR = 1)


/*LIMPAR FILA DE PROCESSAMENTO*/
DELETE FROM GEDAD.TDAD_CONTR_TAREFA_VALIDACAO
WHERE DHR_FIM_PRT IS NULL
AND CTL_CONTR_TAF IN (
35119496
)

COMMIT 

SELECT
	A.SEQ_NUMER_AVB ,
	A.NUM_AVERB_CLI ,
	COALESCE(A.NOM_FANTS_CLI || '(' || PESSOACOG.NOM_FANTS || ')', A.NOM_FANTS_CLI)||
	CASE
		WHEN AJ.SEQ_NUMER_PRS IS NOT NULL THEN '(AJ)'
		ELSE ''
	END AS NOM_FANTS_CLI ,
	A.SIG_SIMBO_MOE ,
	A.NUM_APOLI ,
	A.NUM_SEQUE_AVB ,
	A.SIG_RAMO ,
	A.DHR_EMBAR ,
	A.COD_DOCUM_EMB ,
	A.ORIGEM ,
	A.DESTINO ,
	A.VLR_IS IS ,
	A.VLR_IS_TOT IS_TOTAL ,
	A.VLR_EMBAR ,
	A.VLR_LIMIT_PRS ,
	A.VLR_EMBAR - A.VLR_IS VLR_EMBAR_LIMIT_PRS ,
	A.SEQ_NUMER_PRS ,
	A.CTL_PESSO_CLI ,
	A.NUM_AVERB_PAM ,
	A.VLR_LIMIT_PTX ,
	A.NUM_ETAPA_AVB
FROM
	BILHET.V_BIL_CONSULTA_AVERB_PROPT_EXTPO A
LEFT JOIN BILHET.TBIL_PROPOSTA PROPOSTA ON
	A.SEQ_NUMER_PRS = PROPOSTA.SEQ_NUMER_PRS
LEFT JOIN BILHET.TBIL_PROPOSTA_AJUSTAVEL AJ ON
	AJ.SEQ_NUMER_PRS = PROPOSTA.SEQ_NUMER_PRS
LEFT JOIN PAMAIS.V_CRP_PESSOA PESSOACOG ON
	PESSOACOG.CTL_PESSO = PROPOSTA.CTL_PESSO_COG
WHERE
	YEAR(A.DHR_EMBAR) = 2022
	AND MONTH(A.DHR_EMBAR) = 02      
	
	
SELECT * FROM DBPROD.TAVERBACAO_INDICE ti, DBPROD.TAVERBACAO t, DBPROD.ITEM_DESTINO i 
WHERE t.CTL_AVERB = ti.CTL_AVERB  
AND i.CTL_AVERB = t.CTL_AVERB 
AND t.CTL_AVERB  = 516090485


SELECT * FROM dbprod.TAVERBACAO t
SELECT * FROM DBPROD.TAVERBACAO_INDICE ti 
SELECT * FROM dbprod.TAVERBACAO_COMPLEM_ATM tca 


SELECT * FROM BILHET.TBIL_SITUA_ETAPA_PROPOSTA tsep 


SELECT * FROM bilhet.TBIL_TIPO_AVERBACAO tta 