SELECT
	*
FROM
	(
	SELECT
		F.SEQ_NUMER_FAT AS fatura,
		F.NUM_FATUR_CIA,
		P.NUM_APOLI AS apolice,
		P.NUM_RAMO_SEG AS ramo,
		F.NUM_MES_CPT AS competencia,
		F.NUM_PERIO_FAT AS periodo,
		'' AS caminho,
		F.SIT_FATUR AS situacao,
		(
		SELECT
			COUNT(D.SEQ_NUMER_FAT)
		FROM
			BIL_ARQUIVO_DOCUMENTO_WEB D
		WHERE
			D.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT
			AND D.NUM_ARQUI_RET = 2) AS aviso,
		CASE
			WHEN (
			SELECT
				COUNT(S.SEQ_NUMER_FAT)
			FROM
				BIL_VALOR_SOMA_TIPO_TARIFA S
			WHERE
				S.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT
				AND S.NUM_TARIF = 70
				AND S.VLR_CALCU > 1
				AND F.SIT_FATUR NOT IN(1, 3, 4, 6))>0 THEN (
			SELECT
				COUNT(D.SEQ_NUMER_FAT)
			FROM
				BIL_ARQUIVO_DOCUMENTO_WEB D
			WHERE
				D.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT
				AND D.NUM_ARQUI_RET = 1)
			ELSE -1
		END AS embarque,
		CASE
			WHEN (
			SELECT
				COUNT(S.SEQ_NUMER_FAT)
			FROM
				BIL_VALOR_SOMA_TIPO_TARIFA S
			WHERE
				S.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT
				AND S.NUM_TARIF = 27)>0 THEN (
			SELECT
				COUNT(D.SEQ_NUMER_FAT)
			FROM
				BIL_ARQUIVO_DOCUMENTO_WEB D
			WHERE
				D.SEQ_NUMER_FAT = F.SEQ_NUMER_FAT
				AND D.NUM_ARQUI_RET = 9)
			ELSE -1
		END AS pamtax,
		COALESCE( 
		(SELECT
				V.CTL_VINCD
		FROM
			DBPROD.DOC_VINCULADO V
		WHERE
			V.COD_DOCUM = VP.COD_DOCUM_PRI
			AND VP.TIP_PESSO = 1),0) codigoVinculado,
			H.NUM_SETOR_PAM AS numeroFilial,
		CO.NUM_CORRE_PAM AS codigoCorretor,
		PR.CTL_PRODR AS codigoProdutor
	FROM
		BIL_FATURA F
	INNER JOIN BIL_PROPOSTA P ON
		(F.SEQ_NUMER_PRS = P.SEQ_NUMER_PRS AND P.NUM_RAMO_SEG<>69)
	INNER JOIN PAMAIS.V_CRP_PESSOA VP ON
		(P.CTL_PESSO_CLI = VP.CTL_PESSO
			AND VP.TIP_PESSO = 1)
	INNER JOIN PAMAIS.V_CRP_CORRETOR_PARCEIRO CO ON
		(P.CTL_CORRE = CO.CTL_CORRE)
	INNER JOIN BIL_HIERQ_PRODR_PROPT PR ON
		(P.SEQ_NUMER_PRS = PR.SEQ_NUMER_PRS)
	INNER JOIN APLBIL.V_CRP_HIERARQUIA_COMERCIAL H ON
		(PR.NUM_HIERQ = H.NUM_HIERQ
			AND H.TIP_SETOR = 2)
	LEFT JOIN BIL_ARQUIVO_DOCUMENTO_WEB D ON
		(F.SEQ_NUMER_FAT = D.SEQ_NUMER_FAT)
	WHERE 1=1
		AND F.SIT_FATUR NOT IN(1, 3, 6)
--		AND F.NUM_FATUR_CIA > 0
		AND F.NUM_MES_CPT BETWEEN 202201 AND 202408 
		ORDER BY F.SEQ_NUMER_FAT  DESC 
	) A
WHERE
	codigoVinculado > 0
	AND AVISO = 0
OPTIMIZE FOR 1 ROWS WITH UR



