

/**RELATORIO PAMTAX**/
SELECT DISTINCT pe.COD_DOCUM_PRI, pe.NOM_FANTS, a.DHR_EMBAR, a.DHR_AVERB, p.CTL_AVERB, p.VLR_ITEM_PRE, i.VLR_PAMTX, p.DHR_ALTER  
FROM pamtax.TPTX_PREMIO_PAMTAX p 
INNER JOIN bilhet.TBIL_AVERBACAO_INDICE i ON i.NUM_AVERB_PAM = p.CTL_AVERB AND p.NUM_ITEM_PRE = 1
INNER JOIN bilhet.TBIL_AVERBACAO a ON a.NUM_AVERB_PAM = p.CTL_AVERB
INNER JOIN bilhet.TBIL_RELAC_AVERB_PROPT r ON r.SEQ_NUMER_AVB = a.SEQ_NUMER_AVB 
INNER JOIN bilhet.TBIL_PROPOSTA pro ON pro.SEQ_NUMER_PRS = r.SEQ_NUMER_PRS 
INNER JOIN pamais.TCRP_PESSOA pe ON pe.CTL_PESSO = pro.CTL_PESSO_CLI
WHERE a.DHR_EMBAR BETWEEN '2022-10-01' AND '2022-10-31'
--AND p.VLR_ITEM_PRE <> i.VLR_PAMTX
AND pe.COD_DOCUM_PRI = '35196765000123'
--AND pe.COD_DOCUM_PRI <> '01000786000100'
ORDER BY pe.NOM_FANTS
