/*1- AVERBAÇÃO CONSULTA DETALHE REDUZIDA*/
SELECT AI.CTL_AVERB
		,SPS.NUM_APOLI
		,AI.NUM_PROPT
		,AI.TIP_AVERB
		,(SELECT DES_TIPO_AVB FROM TIPO_AVERBACAO WHERE TIP_AVERB = AI.TIP_AVERB) AS DES_TIPO_AVB
		,AI.CTL_PESSO 
		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = AI.CTL_PESSO) AS NOM_PESSO
		,AI.NUM_RAMO
		,(SELECT SIG_RAMO FROM CRP_RAMO_SEGURO WHERE NUM_RAMO_SEG = AI.NUM_RAMO) AS SIG_RAMO 
		,SPS.NUM_CIA_PAM
		,(SELECT NOM_CIA_PAM FROM CRP_CIA_SEGURADORA_PAMCARY WHERE NUM_CIA_PAM = SPS.NUM_CIA_PAM) AS DES_CIA_PAM 
		,A.TIP_DOCUM_TRA 
		,(SELECT DES_DOCUM_TRA FROM TIPO_DOCUM_TRANSP WHERE TIP_DOCUM_TRA = A.TIP_DOCUM_TRA) AS DES_DOCUM_TRA 
		,A.COD_MANIF 
		,A.VLR_EMBAR 
		,A.DAT_EMBAR 
		,A.HOR_EMBAR 
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = AI.CTL_AVERB	AND num_fator_agr IN (17)) AS VLR_PREMIO_COBRADO_10_3 --Valor de Prêmio Cobrado
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = AI.CTL_AVERB	AND num_fator_agr IN (20)) AS VLR_SEGURADO_10_4 --Valor Segurado
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = Ai.CTL_AVERB	AND num_fator_agr IN (16)) AS TAXA_FINAL_AGR_10_5 --Taxa Final de Agravação (TFA)
		,A.DHR_ENTRA 
		,AI.SIT_AVERB
		,A.DHR_LIBER 
		,(SELECT DES_SITUA_AVB FROM SITUACAO_AVERBACAO WHERE SIT_AVERB = AI.SIT_AVERB) AS DES_SITUA_AVB
		,(SELECT DES_MTSIT_AVB FROM MTSIT_AVERBACAO WHERE TIP_MTSIT_AVB = A.TIP_MTSIT_AVB) AS DES_MTSIT_AVB_10_11
		,AI.SIT_TRANS
		,(SELECT DES_SITUA_TRM FROM SITUACAO_TRANSM WHERE SIT_TRANS = AI.SIT_TRANS) AS DES_SITUA_TRM
		,AI.CTL_VINCD_SED
		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = AI.CTL_VINCD_SED) AS NOM_VINCD_SED
		,A.TIP_MTSIT_AVB
		,A.NUM_TRANS_VIE 
		,A.DHR_AVERB 
FROM AVERBACAO_INDICE AI
	,AVERBACAO A
	,SEG_PROPOSTA_SEGURO SPS
WHERE AI.CTL_AVERB = A.CTL_AVERB
AND SPS.NUM_PROPT = AI.NUM_PROPT
AND SPS.NUM_VERSA_PRS = 1
AND AI.CTL_AVERB = 662726297 --570622739 --684229556  

/*2- AVERBACAO MOTORISTA*/
SELECT AM.CTL_AVERB
	,MM.CTL_MOTOT
	,MM.TIP_DOCUM
	,MM.COD_DOCUM_MOT
	,MM.NOM_MOTOT
	,MM.NUM_PAMCD
	,AM.TIP_MOTOT
	,TM.DES_TIPO_MOT
FROM AVERBACAO_MOTOT AM
,MOTORISTA_MOVTO MM
,TIPO_MOTORISTA TM
WHERE MM.CTL_MOTOT = AM.CTL_MOTOT
AND AM.TIP_MOTOT = TM.TIP_MOTOT
AND AM.CTL_AVERB = 570622739--684229556

/*3- AVERBAÇÃO VEICULO*/
SELECT AV.CTL_AVERB 
	,AV.NUM_SEQUE_VEI
	,AV.NUM_RENAV 
	,AV.COD_IDENT_VEI 
	,AV.TIP_VEICU 
	,(SELECT NOM_TIPO_VEI FROM V_CRP_TIPO_VEICULO WHERE TIP_VEICU = AV.TIP_VEICU) AS NOM_TIPO_VEI
	,AV.TIP_PROPR_VEI
	,TPV.DES_PROPR_VEI
	,AV.TIP_DOCUM_PRP 
	,AV.COD_DOCUM_PRP 
FROM AVERBACAO_VEICULO AV
	,TTIPO_PROPR_VEICULO TPV 
WHERE AV.TIP_PROPR_VEI = TPV.TIP_PROPR_VEI  
AND AV.CTL_AVERB = 662726297--684229556--570622739

/*4- ITENS DESTINO*/
SELECT ID.CTL_AVERB
	,ID.NUM_SEQUE_ITE
	,A.COD_CEP
	,(SELECT UF.NUM_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_ORI ) NUM_UF_ORI
	,(SELECT UF.SIG_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_ORI ) UF_ORI	
	,A.NUM_PRACA_ORI
	,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_ORI) AS DES_PRACA_ORI
	,(SELECT UF.NUM_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_DES ) NUM_UF_DES
	,(SELECT UF.SIG_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_DES ) UF_DES
	,A.NUM_PRACA_DES
	,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_DES) AS DES_PRACA_DES
	,ID.DAT_EMISS_DOC 
	,ID.HOR_EMISS_DOC
	,(SELECT UF.NUM_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_EMI ) NUM_UF_EMI
	,(SELECT UF.SIG_UNFED FROM UNIDADE_FEDERAL UF, PRACA P WHERE UF.NUM_UNFED = P.NUM_UNFED AND P.NUM_PRACA = A.NUM_PRACA_EMI ) UF_EMI
	,A.NUM_PRACA_EMI
	,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_EMI) AS DES_PRACA_EMI
	,ID.NUM_ESPEI_MER 
	,ID.DES_ESPEI 
	,ID.NUM_SEQUE_MER
	,(SELECT DES_MERCA_PAM FROM SINONIMO_MERCA  WHERE NUM_MERCA_PAM = ID.NUM_ESPEI_MER AND NUM_SEQUE_MER = ID.NUM_SEQUE_MER) AS DES_MERCA
	,ID.TIP_EMBAL
	,(SELECT DES_EMBAL FROM TIPO_EMBALAGEM WHERE TIP_EMBAL = ID.TIP_EMBAL) AS DES_EMBAL
	,ID.QTD_MERCA 
	,ID.QTD_PESO
	,ID.QTD_VOLUM 
	,FLOAT(ID.VLR_MERCA) AS VLR_MERCA 
	,ID.NUM_CONHE 
	,ID.COD_MANIF 
	,ID.NUM_NTFIS 
	,ID.TIP_ISENC_SEG
	,(SELECT DES_ISENC_SEG FROM TIPO_ISENCAO_SEG WHERE TIP_ISENC_SEG = ID.TIP_ISENC_SEG) AS DES_ISENC_SEG
	,ID.TIP_FRETE
	,(SELECT DES_FRETE FROM TIPO_FRETE WHERE TIP_FRETE = ID.TIP_FRETE) AS DES_FRETE
	,ID.STA_CARGA_DGA 
	,ID.TIP_TRNSP
	,(SELECT DES_TRNSP FROM TIPO_TRANSPORTE WHERE TIP_TRNSP = ID.TIP_TRNSP) AS DES_TRNSP
	,ID.STA_ICAME
	,ID.STA_RFLUV
	,ID.STA_AUTLO
	,ID.PCE_TARIF_CBR 
	,ID.STA_TRECH 
FROM ITEM_DESTINO ID
	,AVERBACAO A
WHERE A.CTL_AVERB = ID.CTL_AVERB 
AND ID.CTL_AVERB = 662726297--570622739 --684229556





/*AVERBAÇÃO COMPLETA NÃO UTILIZAR NO MOMENTO*/
SELECT AI.CTL_AVERB
		,SPS.NUM_APOLI
		,AI.NUM_PROPT
		,AI.TIP_AVERB
		,(SELECT DES_TIPO_AVB FROM TIPO_AVERBACAO WHERE TIP_AVERB = AI.TIP_AVERB) AS DES_TIPO_AVB
		,AI.CTL_PESSO 
		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = AI.CTL_PESSO) AS NOM_PESSO
		,AI.NUM_RAMO
		,(SELECT SIG_RAMO FROM CRP_RAMO_SEGURO WHERE NUM_RAMO_SEG = AI.NUM_RAMO) AS SIG_RAMO 
		,SPS.NUM_CIA_PAM
		,(SELECT NOM_CIA_PAM FROM CRP_CIA_SEGURADORA_PAMCARY WHERE NUM_CIA_PAM = SPS.NUM_CIA_PAM) AS DES_CIA_PAM 
		,A.TIP_DOCUM_TRA 
		,(SELECT DES_DOCUM_TRA FROM TIPO_DOCUM_TRANSP WHERE TIP_DOCUM_TRA = A.TIP_DOCUM_TRA) AS DES_DOCUM_TRA 
		,A.COD_MANIF 
		,A.VLR_EMBAR 
		,A.DAT_EMBAR 
		,A.HOR_EMBAR 
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = AI.CTL_AVERB	AND num_fator_agr IN (17)) AS VLR_PREMIO_COBRADO_10_3 --Valor de Prêmio Cobrado
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = AI.CTL_AVERB	AND num_fator_agr IN (20)) AS VLR_SEGURADO_10_4 --Valor Segurado
		,(SELECT VLR_FATOR_AGR FROM resultado_agrava WHERE ctl_averb = Ai.CTL_AVERB	AND num_fator_agr IN (16)) AS TAXA_FINAL_AGR_10_5 --Taxa Final de Agravação (TFA)
--		,A.NUM_MERCA
--		,(SELECT DES_MERCA FROM MERCADORIA WHERE NUM_MERCA_PAM = A.NUM_MERCA) AS DES_MERCA
--		,A.COD_CEP 
--		,A.NUM_PRACA_EMI
--		,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_EMI) AS DES_PRACA_EMI
--		,A.NUM_PRACA_ORI
--		,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_ORI) AS DES_PRACA_ORI
		,A.DHR_ENTRA 
		,AI.SIT_AVERB
		,(SELECT DES_SITUA_AVB FROM SITUACAO_AVERBACAO WHERE SIT_AVERB = AI.SIT_AVERB) AS DES_SITUA_AVB
		,(SELECT DES_MTSIT_AVB FROM MTSIT_AVERBACAO WHERE TIP_MTSIT_AVB = A.TIP_MTSIT_AVB) AS DES_MTSIT_AVB_10_11
		,A.DHR_LIBER 
		,AI.SIT_TRANS
		,(SELECT DES_SITUA_TRM FROM SITUACAO_TRANSM WHERE SIT_TRANS = AI.SIT_TRANS) AS DES_SITUA_TRM
--		,A.COD_USER
--		,A.DHR_ALTER
		,AI.CTL_VINCD_SED
		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = AI.CTL_VINCD_SED) AS NOM_VINCD_SED
--		,AI.CTL_PESSO 
--		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = AI.CTL_PESSO) AS NOM_PESSO
--		,AI.NUM_VERSA_PRS
--		,A.CTL_VINCD_COG -- QUAL A DIFERENCA ENTRE ESSE CAMPO E O CTL_PESSO_COG 
--		,A.NUM_LOCAL_ORI
--		,(SELECT SIG_UNFED FROM UNIDADE_FEDERAL WHERE NUM_UNFED = A.NUM_LOCAL_ORI) AS DES_LOCAL_ORI
--		,A.NUM_PRACA_DES
--		,(SELECT DES_PRACA FROM PRACA WHERE NUM_PRACA = A.NUM_PRACA_DES) AS DES_PRACA_DES
--		,A.NUM_MOEDA 
		,A.TIP_MTSIT_AVB
--		,A.SIT_MOTOT 
		,A.NUM_TRANS_VIE 
		,A.DHR_AVERB 
--		,A.STA_RCF 
--		,A.STA_RFLUV 
--		,A.NUM_SEQUE_HIS 
--		,A.STA_RECUP 
--		,A.SIT_ESCOL
--		,(SELECT DES_ESCOL FROM SITUACAO_ESCOLTA WHERE SIT_ESCOL = A.SIT_ESCOL) AS DES_ESCOL
--		,A.SIT_MONIT 
--		,(SELECT DES_MONIT FROM SITUACAO_MONITORA WHERE SIT_MONIT = A.SIT_MONIT) AS DES_MONIT
--		,A.TIP_MOTOT 
--		,(SELECT DES_TIPO_MOT FROM TIPO_MOTORISTA WHERE TIP_MOTOT = A.TIP_MOTOT) AS DES_TIPO_MOT
--		,A.CTL_PESSO_COG
--		,(SELECT NOM_PESSO FROM CRP_PESSOA WHERE CTL_PESSO = A.CTL_PESSO_COG) AS NOM_PESSO_COG
FROM AVERBACAO_INDICE AI
	,AVERBACAO A
	,SEG_PROPOSTA_SEGURO SPS
WHERE AI.CTL_AVERB = A.CTL_AVERB
AND SPS.NUM_PROPT = AI.NUM_PROPT
AND SPS.NUM_VERSA_PRS = 1
AND AI.CTL_AVERB =570622739 --684229556  