SELECT
	s.NUM_VERSA_PRS, 
	dv.CTL_VINCD AS ctl_vincd_sed, --EXIBIR NO GRID  E INSERT APLTRANS.SEGURADO_PARALELO
	s.CTL_clien_pps AS ctl_pesso, --EXIBIR NO GRID  E INSERT APLTRANS.SEGURADO_PARALELO
	s.NUM_RAMO_SEG AS num_ramo, --EXIBIR NO GRID  E INSERT APLTRANS.SEGURADO_PARALELO
	s.NUM_PROPT, --EXIBIR NO GRID
	s.dat_inici_vig AS datInicioVig,
	s.dat_fim_vig AS datFimVig,
	s.num_apoli, --EXIBIR NO GRID
	p.cod_docum_pri, --EXIBIR NO GRID
	p.nom_pesso, --EXIBIR NO GRID
	p.nom_fants, --EXIBIR NO GRID
	r.sig_ramo, --EXIBIR NO GRID
	PL.VLR_LIMIT AS vlrLimit,
	s.dat_baixa_apo AS datBaixaVig--EXIBIR NO GRID
FROM
	DOC_VINCULADO dv
INNER JOIN CRP_PESSOA p ON
	p.COD_DOCUM_PRI = dv.COD_DOCUM
INNER JOIN SEG_PROPOSTA_SEGURO s ON
	s.CTL_CLIEN_PPS = p.CTL_PESSO
	AND s.TIP_PROPT = 1
	AND s.sit_tipo_prs IN (1, 2, 3, 6, 98)
INNER JOIN SEG_PROPOSTA_LIMITE PL ON
	PL.NUM_PROPT = s.NUM_PROPT
	AND PL.TIP_LIMIT_SEG = 1
	AND PL.NUM_VERSA_PRS = s.NUM_VERSA_PRS
INNER JOIN CRP_RAMO_SEGURO r ON	
	r.NUM_RAMO_SEG = s.NUM_RAMO_SEG 
WHERE
	CURRENT TIMESTAMP BETWEEN s.dat_inici_vig + 1 DAY AND s.dat_fim_vig
	AND s.NUM_PROPT NOT BETWEEN 55000000 AND 55999999
	AND s.NUM_PROPT NOT BETWEEN 999000000 AND 999999999
	AND s.NUM_RAMO_SEG = 1 -- PARAMETRO DO COMBO RAMO
	AND	s.num_apoli IS NOT NULL 
--	AND (dv.CTL_VINCD, p.CTL_PESSO) NOT IN ( SELECT ctl_vinc_sed, CTL_PESSO  FROM SEGURADO_PARALELO)
--	AND s.CTL_CLIEN_PPS IN (1195341	)
	AND p.COD_DOCUM_PRI =  '21570775000172'--'26984726000108'--'21587595000101' --'20932142000102'--'22875014000191'--'11419190000100'--
	ORDER BY	CTL_PESSO


	SELECT * FROM CRP_PESSOA 
	WHERE COD_DOCUM_PRI = '22875014000191'
	
	SELECT * FROM seguro.V_SEG_PROPOSTA_SEGURO vsps 
	WHERE 1=1 
	AND CTL_CLIEN_PPS = 656749
	AND NUM_RAMO_SEG = 1
	AND TIP_PROPT = 1
--	AND SIT_TIPO_PRS= 4
	AND DAT_FIM_VIG IS NOT NULL 
	AND NUM_APOLI  IS NOT NULL 
	ORDER BY DAT_FIM_VIG  DESC 
	
	SELECT * FROM SEG_SITUACAO_TIPO_PROPOSTA
	WHERE TIP_PROPT = 1
	ORDER BY SIT_TIPO_PRS 
	
	
	select * FROM AVERBACAO 
	WHERE CTL_AVERB = 923803508
	
	SELECT * FROM ITEM_DESTINO 
	WHERE CTL_AVERB = 923433519
	
	SELECT * FROM DESTINO 
	WHERE ctl_averb = 923433519
	
	
	SELECT * FROM SEGURADO_PARALELO 
	WHERE CTL_PESSO = 828159