/*CABEÇALHO DO RELATÓRIO DE ERROS*/
SELECT a.CTL_AVERB, 
	a.COD_MANIF,
	a.DHR_AVERB,
	a.DAT_EMBAR,
	a.HOR_EMBAR,
	S.NUM_PROPT AS proposta,
	s.NUM_APOLI AS apolice,
	s.dat_inici_vig,
	s.dat_fim_vig,
	(SELECT NOM_PESSO FROM PAMAIS.TCRP_PESSOA WHERE CTL_PESSO = ai.ctl_pesso) AS segurado,
	(SELECT sig_ramo FROM PAMAIS.TCRP_RAMO_SEGURO WHERE num_ramo_seg = ai.num_ramo) AS ramo,
	s.NUM_CIA_PAM AS numCiaPam,
	(SELECT nom_cia_pam FROM PAMAIS.CRP_CIA_SEGURADORA_PAMCARY WHERE NUM_CIA_PAM = s.NUM_CIA_PAM) AS ciaSeguradora,
    COALESCE((SELECT sum(VLR_LIMIT) FROM seguro.TSEG_PROPOSTA_LIMITE WHERE NUM_PROPT = s.NUM_PROPT AND num_versa_prs = s.NUM_VERSA_PRS),0) AS lmr,
    ai.sit_averb,
    (SELECT des_situa_avb FROM SITUACAO_AVERBACAO WHERE sit_averb = ai.SIT_AVERB) situacao_averbacao,
    ai.SIT_TRANS, 
    (SELECT des_situa_trm FROM SITUACAO_TRANSM  WHERE sit_trans = ai.SIT_trans) situacao_transmissao,
    ae.TIP_ERRO ,
    (SELECT DES_ERRO FROM ERRO_AVERBACAO WHERE TIP_ERRO = ae.tip_erro ) AS tipo_erro,
    (SELECT des_tipo_avb FROM TIPO_AVERBACAO WHERE tip_averb = ai.TIP_AVERB) AS tipo_avb,
    a.cod_user    	
FROM AVERBACAO_INDICE AI 
	LEFT JOIN SEGURO.TSEG_PROPOSTA_SEGURO S
		ON S.NUM_PROPT = AI.NUM_PROPT AND S.TIP_PROPT = 1
	INNER JOIN AVERBACAO A
		ON AI.CTL_AVERB = A.CTL_AVERB
	LEFT JOIN AVERBACAO_ERRO ae
		ON ae.CTL_AVERB = ai.CTL_AVERB 
WHERE 1=1
AND A.DHR_AVERB BETWEEN '2023-05-01 00:00:00' AND '2023-05-02 23:59:59' 
/*OPÇÕES DE FILTRO*/
--AND A.DHR_ENTRA BETWEEN '2023-05-02 00:00:00' AND '2023-05-02 23:59:59'
--AND A.DAT_EMBAR BETWEEN '2023-05-02 00:00:00' AND '2023-05-02 23:59:59'
--AND a.CTL_AVERB IN (559235780,869801445,633294264,633304195,633304196)
AND AI.SIT_AVERB IN (1, 5, 9 )
ORDER BY CTL_AVERB, segurado, ramo
OPTIMIZE FOR 1 ROWS WITH UR
