SELECT * FROM AVERBACAO_ERRO 
WHERE CTL_AVERB IN ( SELECT a.ctl_averb FROM AVERBACAO_INDICE ai INNER JOIN AVERBACAO a ON a.ctl_averb = ai.ctl_averb WHERE ai.NUM_RAMO = 1
AND ai.CTL_PESSO = 15141
AND ai.CTL_VINCD_SED = 500269
AND ai.sit_averb= 5
AND a.dhr_alter BETWEEN '2024-08-12 15:45:00' AND CURRENT TIMESTAMP ) 

SELECT
	ai.NUM_PROPT,
	p.nom_pesso,
	p.COD_DOCUM_PRi,
	ai.SIT_AVERB,
	sa.DES_SITUA_AVB,
	count(1) AS total
FROM
	AVERBACAO_INDICE ai
INNER JOIN APLTRANS.SITUACAO_AVERBACAO sa ON
	sa.SIT_AVERB = ai.SIT_AVERB
INNER JOIN PAMAIS.CRP_PESSOA p ON
	p.ctl_pesso = ai.CTL_PESSO
INNER JOIN AVERBACAO a ON
	a.ctl_averb = ai.ctl_averb
INNER JOIN SEGURADO_PARALELO sp ON
	sp.CTL_PESSO = ai.CTL_PESSO
	AND sp.CTL_VINC_SED = ai.CTL_VINCD_SED  0
WHERE
	ai.CTL_AVERB > 900000000
	AND ai.NUM_RAMO = 1
	AND a.dhr_alter BETWEEN '2024-08-12 15:45:00' AND CURRENT timestamp
GROUP BY
	ai.num_propt,
	p.nom_pesso,
	p.COD_DOCUM_PRI,
	ai.SIT_AVERB,
	sa.DES_SITUA_AVB OPTIMIZE FOR 1 ROWS WITH ur

SELECT * FROM TAVERBACAO_CONSISTENCIA tc  INNER JOIN AVERBACAO_INDICE ai 
ON ai.CTL_AVERB = tc.CTL_AVERB 
WHERE AI.CTL_AVERB = 908492952
ai.NUM_PROPT = 24000787
ORDER BY DHR_ALTER DESC 





SELECT ai.CTL_AVERB AS averbacao
,ai.NUM_PROPT AS proposta
,ai.NUM_RAMO AS ramo
,(SELECT nom_vincd FROM vinculado WHERE ctl_vincd = ai.CTL_VINCD_SED) AS segurado
,a.DHR_AVERB 
,a.DHR_ALTER
,a.COD_USER 
,ai.CTL_PESSO 
,ai.CTL_VINCD_SED 
 ,* FROM AVERBACAO_INDICE Ai 
INNER JOIN AVERBACAO a ON a.CTL_AVERB = ai.CTL_AVERB 
WHERE ai.CTL_PESSO IN (15141)
AND a.DHR_ALTER BETWEEN '2024-08-12 15:45:00' AND CURRENT TIMESTAMP 
AND ai.SIT_AVERB = 0





SELECT * FROM APLTRANS.AVERBACAO_INDICE ai INNER JOIN APLTRANS.AVERBACAO a 
ON a.CTL_AVERB = ai.CTL_AVERB 
INNER JOIN APLTRANS.AVERBACAO_CONSISTENCIA ac 
ON ac.CTL_AVERB = ai.CTL_AVERB 
WHERE ai.CTL_AVERB IN (909048514,
909048519,
909048521
909048526)




SELECT COALESCE(a.NUM_PROPT,0) AS num_propt, c.DAT_EMBAR, a.DAT_INICI_VIG, a.DAT_FIM_VIG, b.CTL_VINCD_SED, b.CTL_PESSO, A.SIT_TIPO_PRS
,A.TIP_PROPT 
             FROM averbacao_indice b  
             INNER JOIN averbacao c ON b.ctl_averb = c.ctl_averb  
             LEFT JOIN seguro.Tseg_proposta_seguro a ON (a.CTL_CLIEN_PPS,a.NUM_RAMO_SEG) = (b.CTL_PESSO,b.NUM_RAMO) 
             AND A.TIP_PROPT = 1  --NOVO
             AND a.sit_tipo_prs IN (1,2,3,6) --NOVO               
             AND C.DAT_EMBAR BETWEEN a.dat_inici_vig  1 DAY AND a.dat_fim_vig  
             AND a.NUM_PROPT NOT BETWEEN 55000000 AND 55999999  
             AND a.NUM_PROPT NOT BETWEEN 999000000 AND 999999999  
             WHERE B.NUM_RAMO = A.NUM_RAMO_SEG -- NOVO
			 AND b.ctl_averb IN (920271177)
			 
			

SELECT * FROM AVERBACAO_CONSISTENCIA 
WHERE CTL_AVERB = 920533213--920544275--920533213


UPDATE AVERBACAO_INDICE SET 
SIT_AVERB = 0
WHERE CTL_AVERB IN
(906899979)



INSERT INTO AVERBACAO_CONSISTENCIA (CTL_AVERB, CTL_USER, DHR_ALTER, SIT_AVERB, NUM_SEQ)
SELECT CTL_AVERB, 15, CURRENT timestamp, 0, 0  
from AVERBACAO
WHERE CTL_AVERB IN 
(906899979
)


COMMIT





SELECT ai.CTL_AVERB AS ctlAverb  FROM AVERBACAO_CONSISTENCIA ac  JOIN AVERBACAO_INDICE AI
ON ac.CTL_AVERB = ai.CTL_AVERB
WHERE ac.SIT_AVERB = 0  AND ai.CTL_PESSO AND EXISTS
(SELECT se.ctl_pesso  FROM SEGURADO_EXCLUIDO_CONSISTENCIA se
WHERE se.STA_INATIVO = 0)
  AND (ai.CTL_PESSO, ai.NUM_RAMO)
   in ( 18517, 1 )
ORDER BY ac.DHR_ALTER ASC LIMIT 1000
OPTIMIZE FOR 1 ROWS WITH UR;

SELECT ai.CTL_AVERB AS ctlAverb, ai.NUM_PROPT 
FROM AVERBACAO_CONSISTENCIA ac
JOIN AVERBACAO_INDICE AI
ON ac.CTL_AVERB = ai.CTL_AVERB
WHERE ac.SIT_AVERB = 0 
AND ai.CTL_PESSO NOT IN (SELECT se.ctl_pesso
FROM SEGURADO_EXCLUIDO_CONSISTENCIA se WHERE se.STA_INATIVO = 0)
AND ai.CTL_PESSO = 18517
ORDER BY ac.DHR_ALTER ASC LIMIT 1000


SELECT * FROM ITEM_DESTINO 

SELECT ai.CTL_AVERB AS ctlAverb, ai.TIP_AVERB , ai.NUM_PROPT , ai.NUM_VERSA_PRS, ai.CTL_VINCD_SED, ai.CTL_PESSO 
FROM AVERBACAO_CONSISTENCIA ac
JOIN AVERBACAO_INDICE ai
ON ac.CTL_AVERB = ai.CTL_AVERB
WHERE ai.CTL_AVERB > 800000000
AND ac.SIT_AVERB = 0 
AND ai.NUM_RAMO = 1
AND ai.CTL_PESSO = 17049
LIMIT 1000
OPTIMIZE FOR 1 ROW WITH UR



SELECT * FROM apltrans.averbacao A INNER JOIN AVERBACAO_INDICE AI
ON AI.CTL_AVERB = A.CTL_AVERB
INNER JOIN AVERBACAO_ERRO ae ON ae.CTL_AVERB = ai.CTL_AVERB 
WHERE 1=1
--AND  a.DAT_EMBAR < '2024-08-01'
AND a.DHR_ALTER BETWEEN '2024-08-14 16:30:00' AND '2024-08-14 17:10:00'
AND ae.COD_USER = 'API-CONSISTENCIA-ERRO'
ORDER BY a.dat_embar DESC 



			
INSERT INTO APLTRANS.SEGURADO_PARALELO
(ctl_vinc_sed, ctl_pesso, num_ramo_seg, cod_user, dhr_alter)
VALUES (160678,15280,1,'ronaldo',CURRENT timestamp)

COMMIT
	


SELECT * FROM SEGURADO_PARALELO SP INNER JOIN PAMAIS.CRP_PESSOA P 
ON P.CTL_PESSO  = SP.CTL_PESSO 
INNER JOIN VINCULADO V 
ON V.CTL_VINCD = SP.CTL_VINC_SED 
ORDER BY sp.ctl_paralelo


COMMIT

SELECT p.nom_pesso, p.CTL_PESSO, count(1) 
FROM APLTRANS.SEGURADO_PARALELO sp INNER JOIN PAMAIS.CRP_PESSOA p
ON p.ctl_pesso = sp.ctl_pesso
GROUP BY p.nom_pesso, p.ctl_pesso
HAVING count(1) > 1



commit

SELECT * FROM SEGURADO_PARALELO 
WHERE CTL_PESSO IN (
1215598,
1215900,
1216557,
1216653
)
ORDER BY CTL_PESSO 



SELECT ai.CTL_AVERB AS ctlAverb  
        FROM AVERBACAO_CONSISTENCIA ac  
        JOIN AVERBACAO_INDICE ai  
            ON ac.CTL_AVERB = ai.CTL_AVERB  
        JOIN SEGURADO_PARALELO sp  
            ON sp.CTL_PESSO = ai.CTL_PESSO  
        WHERE ai.CTL_AVERB > 800000000  
        AND ac.SIT_AVERB = 0  
        AND ai.NUM_RAMO IN (SELECT sp_inner.num_ramo_seg  
                            FROM SEGURADO_PARALELO sp_inner  
                            WHERE sp_inner.CTL_PESSO = sp.CTL_PESSO)  
        LIMIT 1000  
        OPTIMIZE FOR 1 ROW WITH UR
        
        
        
        
        
        
        
        
   SELECT ai.CTL_AVERB AS ctlAverb, ai.CTL_PESSO  
            FROM AVERBACAO_CONSISTENCIA ac  
            JOIN AVERBACAO_INDICE ai  
                ON ac.CTL_AVERB = ai.CTL_AVERB  
            JOIN SEGURADO_PARALELO sp  
                ON sp.CTL_PESSO = ai.CTL_PESSO  
            WHERE ai.CTL_AVERB > 800000000  
            AND ac.SIT_AVERB = 0  
            AND ai.NUM_RAMO IN (SELECT sp_inner.num_ramo_seg  
                                FROM SEGURADO_PARALELO sp_inner  
                                WHERE sp_inner.CTL_PESSO = sp.CTL_PESSO)  
            LIMIT 1000  
            OPTIMIZE FOR 1 ROW WITH UR
     
       SELECT * FROM AVERBACAO_CONSISTENCIA ac INNER JOIN AVERBACAO_INDICE a 
       ON a.CTL_AVERB = ac.CTL_AVERB 
       WHERE ac.SIT_AVERB <> 0 
       
       a.CTL_AVERB = 920542119		

       SELECT * FROM AVERBACAO_INDICE 
       WHERE CTL_AVERB = 920542119		

       SELECT * FROM AVERBACAO_ERRO 
       WHERE CTL_AVERB IN
       
        
       
           
           
           
           
           
           
           
           
           
           
           