

SELECT ID.CTL_AVERB AS averbacao 
	,ID.NUM_SEQUE_ITE AS sequencia
	,PS.NUM_APOLI AS apolice
	,AI.NUM_PROPT AS proposta
	,PS.CTL_CLIEN_PPS  AS cod_segurado
	,P.COD_DOCUM_PRI AS cnpj_segurado
	,P.NOM_FANTS AS nome_fantasia_segurado
	,P.NOM_PESSO AS razao_social_segurado
	, AI.NUM_RAMO AS cod_ramo
	,R.SIG_RAMO AS ramo
	,ID.COD_MANIF AS manifesto
	,ID.NUM_CONHE AS conhecimento
	,ID.NUM_NTFIS AS nota_fiscal
	,ID.DAT_EMISS_DOC AS data_emissao
	,ID.HOR_EMISS_DOC AS hora_emissao
	,ID.NUM_PRACA_EMI AS num_praca_emiss
	,PI.DES_PRACA AS praca_emiss
	,PI.SIG_UNFED AS uf_emiss
	,A.COD_CEP AS cod_cep
	, ID.NUM_PRACA_ORI AS num_praca_ori
 	, PO.DES_PRACA AS praca_origem
    , PO.SIG_UNFED AS uf_origem
    , ID.NUM_LOCAL AS num_praca_des 
    , PD.NOM_UNFED AS uf_destino
    , PD.SIG_UNFED AS sig_uf_destino
    , ID.TIP_TRNSP AS cod_tip_transp
	, TT.DES_TRNSP AS tipo_transp	
	, ID.NUM_ESPEI_MER AS cod_mercadoria
	, M.DES_MERCA_PAM AS des_mercadoria
	, A.NUM_MOEDA AS num_moeda
	, MO.SIG_MOEDA AS moeda 
	, ID.VLR_MERCA AS valor_mercadoria
	, ID.TIP_ISENC_SEG AS cod_tipo_isencao
	, TI.DES_ISENC_SEG AS tipo_isencao
	, COALESCE(ID.STA_ICAME,'N') AS icamento 
	, COALESCE(ID.STA_CARGA_DGA,'N') AS carga_descarga
	, COALESCE(ID.STA_RFLUV ,'N') AS fluvial
	, COALESCE(ID.STA_AUTLO ,'N') AS meios_proprios
    , COALESCE(RA.VLR_FATOR_AGR,0) AS valor_pamtax
    , AI.TIP_AVERB AS cod_tip_averb
    , TA.DES_TIPO_AVB AS tipo_averbacao
    , A.COD_USER AS usuario
	, A.DHR_ALTER AS data_hora_inclusao
    , ACA.COD_CNPJ_TOM AS cnpj_tomador
    , 0 AS  PROTOCOLO_AVERBACAO     
FROM APLTRANS.ITEM_DESTINO ID 
	INNER JOIN APLTRANS.AVERBACAO_INDICE AI ON AI.CTL_AVERB = ID.CTL_AVERB 
	INNER JOIN SEGURO.TSEG_PROPOSTA_SEGURO PS ON PS.NUM_PROPT = AI.NUM_PROPT AND PS.NUM_VERSA_PRS = 1 AND PS.TIP_PROPT = 1
	INNER JOIN APLTRANS.RAMO R ON R.NUM_RAMO = AI.NUM_RAMO 
	INNER JOIN APLTRANS.CRP_PESSOA P ON P.CTL_PESSO = PS.CTL_CLIEN_PPS 
	INNER JOIN APLTRANS.AVERBACAO A ON A.CTL_AVERB = AI.CTL_AVERB 
	LEFT JOIN APLTRANS.AVERBACAO_COMPLEM_ATM ACA ON ACA.CTL_AVERB = ID.CTL_AVERB 
	INNER JOIN APLTRANS.SINONIMO_MERCA M ON M.NUM_MERCA_PAM = id.NUM_ESPEI_MER AND M.STA_AVERB = 'S'
	LEFT JOIN APLTRANS.V_PRACA PO ON PO.NUM_PRACA = ID.NUM_PRACA_ORI 
	INNER JOIN APLTRANS.UNIDADE_FEDERAL PD ON PD.NUM_UNFED = ID.NUM_LOCAL 
	LEFT JOIN APLTRANS.V_PRACA PI ON PI.NUM_PRACA = ID.NUM_PRACA_EMI 
	INNER JOIN APLTRANS.TIPO_AVERBACAO TA ON TA.TIP_AVERB = AI.TIP_AVERB 
	LEFT JOIN APLTRANS.TIPO_ISENCAO_SEG TI ON TI.TIP_ISENC_SEG = ID.TIP_ISENC_SEG 
	LEFT JOIN APLTRANS.RESULTADO_AGRAVA RA ON RA.CTL_AVERB = ID.CTL_AVERB AND RA.NUM_FATOR_AGR = 17
	LEFT JOIN APLTRANS.TIPO_TRANSPORTE TT ON TT.TIP_TRNSP = ID.TIP_TRNSP 
	INNER JOIN APLTRANS.MOEDA MO ON MO.NUM_MOEDA = A.NUM_MOEDA 
WHERE 1=1
--AND ID.CTL_AVERB = 572215576--905683902--207958032--860736598	
AND p.CTL_PESSO = 15141
AND A.DHR_ENTRA BETWEEN '2024-07-17 00:00:00' AND '2024-07-17 23:59:59'
ORDER BY ID.CTL_AVERB, ID.NUM_SEQUE_ITE 
OPTIMIZE FOR 1 ROWS WITH UR 

