/*consulta viagens Telerisco Sem MDF-e*/
SELECT
	DISTINCT MM.COD_DOCUM_MOT AS CPF_MOTOT,
	MM.NOM_MOTOT AS NOM_MOTOT,
	UF_ORI.SIG_UNFED AS UF_ORI,
	UF_DES.SIG_UNFED AS UF_DES,
	A.dat_embar AS DAT_EMBAR,
	AV.COD_IDENT_VEI AS PLACA_VEIC,
	(select P.cod_docum_pri from averbacao_indice AI 
			INNER JOIN PAMAIS.Tcrp_pessoa P
				ON P.CTL_PESSO = AI.CTL_PESSO
             WHERE AI.ctl_averb = A.CTL_AVERB ) AS DOC_SEGURADO,
    PRACA_ORI.des_praca AS PRACA_ORI,
	PRACA_DES.DES_PRACA AS PRACA_DES,
	A.VLR_EMBAR AS VLR_EMBAR,	
	A.CTL_AVERB AS CTL_AVERB,
	A.NUM_PRACA_EMI AS NUM_PRACA_EMI
FROM
	AVERBACAO A
	INNER JOIN AVERBACAO_MOTOT AM
	ON A.CTL_AVERB = AM.CTL_AVERB
	INNER JOIN MOTORISTA_MOVTO MM
	ON MM.CTL_MOTOT = AM.CTL_MOTOT
		AND MM.COD_DOCUM_MOT <> '00000000000'
   		AND MM.nom_motot <> 'NAO IDENTIFICADO'
	INNER JOIN AVERBACAO_VEICULO AV
		ON A.CTL_AVERB = AV.CTL_AVERB 
	INNER JOIN UNIDADE_FEDERAL UF_ORI
		ON UF_ORI.NUM_UNFED  =A.NUM_LOCAL_ORI 
	INNER JOIN PRACA PRACA_ORI
		ON PRACA_ORI.NUM_PRACA = A.NUM_PRACA_ORI
	INNER JOIN ITEM_DESTINO ID
		ON A.CTL_AVERB = ID.CTL_AVERB
	INNER JOIN UNIDADE_FEDERAL UF_DES
		ON UF_DES.NUM_UNFED = ID.NUM_LOCAL
	INNER JOIN PRACA PRACA_DES
		ON PRACA_DES.NUM_PRACA = ID.NUM_PRACA 
WHERE
    A.CTL_AVERB NOT IN (SELECT CTL_AVERB FROM  relac_averb_mdfe) 
    and date(A.dhr_entra)  between CURRENT DATE - 1 DAY AND CURRENT DATE - 1 DAY 
OPTIMIZE FOR 10 ROWS WITH UR



/*VIAGENS COM MDF-E*/
SELECT
	MOT.COD_DOCUM_MOT AS CPF_MOTORISTA,
	MOT.NOM_MOTOT AS NOME_MOTORISTA,
	MANIF.SIG_UNFED_ORI AS UF_ORIGEM,
	MANIF.SIG_UNFED_DES AS UF_DESTINO,
	TO_CHAR(MANIF.DHR_CHANC_MAN,'DD/MM/YYYY') AS DATA_EMBARQUE,
	CAV.COD_PLACA_TCA AS PLACA_CAVALO,
    MANIF.COD_CNPJ_EMI_DEC AS COD_DOCUM_PRI,
	MUNORI.NOM_MUNIC_CARREG AS CIDADE_ORIGEM,
	COALESCE(CAV.COD_RENAV_TCA, ' ') AS RENAVAM_CAVALO,
	COALESCE(CAV.COD_CPF_PRP, CAV.COD_CNPJ_PRP) AS DOCUMENTO_PROPRIETARIO,
	TO_CHAR(MANIF.DHR_CHANC_MAN,'HH24:MI:SS') AS HORA_EMBARQUE,
	( SELECT MAX(DOC.NOM_PRACA_DGA) FROM MDFE.TMDFE_MANIFESTO_DOC_CHAVE DOC 
		WHERE MANIF.CTL_MANIF = DOC.CTL_MANIF ) AS CIDADE_DESTINO,
	MANIF.VLR_CARGA AS VALOR_EMBARQUE,
	MANIF.COD_CHAVE_MAN AS CHAVE_MDFE,
	MANIF.CTL_MANIF AS CTL_MDFE
	,(SELECT COALESCE(MAX(a.num_praca_emi),0) FROM TAVERBACAO a,TRELAC_AVERB_MDFE b
   		WHERE a.ctl_averb = b.ctl_averb 
       	AND b.ctl_manif = MANIF.CTL_MANIF) AS num_praca_emi
FROM
	MDFE.TMDFE_MANIFESTO MANIF 
	INNER JOIN MDFE.TMDFE_MANIF_RODOV_MOTOT MOT
		ON MANIF.CTL_MANIF = MOT.CTL_MANIF 
	INNER JOIN MDFE.TMDFE_MANIF_RODOV_TRACAO CAV
		ON MANIF.CTL_MANIF = CAV.CTL_MANIF 
	INNER JOIN MDFE.TMDFE_MUNICIPIO_CARREGA MUNORI
		ON MANIF.CTL_MANIF = MUNORI.CTL_MANIF	
WHERE
	MANIF.IDT_SITUA_MAN <> 'C'
	AND DATE(MANIF.DHR_INCLU) BETWEEN CURRENT DATE -1 DAY AND CURRENT DATE - 1 DAY	
OPTIMIZE FOR 1 ROWS WITH UR

