
--API DOMINIOS CONSULTA MERCADORIAS SEM DUPLICIDADES
WITH mercadorias AS (
SELECT A.NUM_MERCA_PAM as numMercaPam  
        , A.NUM_SEQUE_MER as numSequeMer  
        , A.DES_MERCA_PAM as descricao  
        , COALESCE(B.NUM_MERCA,99) as numMerca  
        , COALESCE(B.DES_MERCA,'OUTROS') as desMerca  
	    ,ROW_NUMBER() OVER (PARTITION BY A.NUM_MERCA_PAM) AS merc
        FROM SINONIMO_MERCA A  
        LEFT JOIN MERC_ESPECIFICA B ON (A.NUM_MERCA_PAM, A.NUM_SEQUE_MER) = (B.NUM_MERCA_PAM, B.NUM_SEQUE_MER) 
		WHERE A.STA_AVERB = 'S'  
)
SELECT numMercaPam
	, numSequeMer
	,descricao
	,numMerca
	,desMerca
FROM mercadorias
WHERE merc = 1;

SELECT CTL_AVERB, NUM_MERCA FROM AVERBACAO
WHERE CTL_AVERB = 860736829





SELECT CTL_AVERB, NUM_ESPEI_MER, NUM_SEQUE_MER FROM ITEM_DESTINO 
WHERE CTL_AVERB = 860736829


--API DOMININOS COUNT DE MERCADORIAS SEM DUPLICIDADES
WITH mercadorias AS (
	SELECT A.NUM_MERCA_PAM as numMercaPam  
	,ROW_NUMBER() OVER (PARTITION BY A.NUM_MERCA_PAM) AS merc
	FROM SINONIMO_MERCA A  
         LEFT JOIN MERC_ESPECIFICA B  
           ON (A.NUM_MERCA_PAM, A.NUM_SEQUE_MER) = (B.NUM_MERCA_PAM, B.NUM_SEQUE_MER)
    WHERE A.STA_AVERB = 'S'       
)
SELECT COUNT(numMercaPam) FROM mercadorias
WHERE merc = 1;



--API DOMINIOS CONSULTA MERCADORIA POR ID SEM DUPLICIDADES
WITH mercadorias AS (
	SELECT
A.NUM_MERCA_PAM as numMercaPam  
        , A.NUM_SEQUE_MER as numSequeMer  
        , A.DES_MERCA_PAM as descricao  
	,ROW_NUMBER() OVER (PARTITION BY A.NUM_MERCA_PAM) AS merc
	FROM SINONIMO_MERCA A  
         LEFT JOIN MERC_ESPECIFICA B  
           ON (A.NUM_MERCA_PAM, A.NUM_SEQUE_MER) = (B.NUM_MERCA_PAM, B.NUM_SEQUE_MER)
    WHERE A.STA_AVERB = 'S'       
)
SELECT numMercaPam
	,numSequeMer
	,descricao
FROM mercadorias 
	WHERE numMercaPam = ?
	AND numSequeMer =?
	

--API DOMINIOS CONSULTA MERCADORIA POR DESCRIÇÃO SEM DUPLICIDADES
WITH mercadorias AS (
 SELECT A.NUM_MERCA_PAM as numMercaPam  
        , A.NUM_SEQUE_MER as numSequeMer  
        , A.DES_MERCA_PAM as descricao  
        , COALESCE(B.NUM_MERCA,99) as numMerca  
        , COALESCE(B.DES_MERCA,'OUTROS') as desMerca  
        ,ROW_NUMBER() OVER (PARTITION BY A.NUM_MERCA_PAM) AS merc
        FROM SINONIMO_MERCA A  
        LEFT JOIN MERC_ESPECIFICA B ON (A.NUM_MERCA_PAM, A.NUM_SEQUE_MER) = (B.NUM_MERCA_PAM, B.NUM_SEQUE_MER)  
        WHERE A.STA_AVERB = 'S' 
        AND UPPER(A.DES_MERCA_PAM) like UPPER('%':descricao'%')
)
SELECT numMercaPam
	,numSequeMer
	,descricao
	,numMerca
	,desMerca
FROM mercadorias
WHERE merc = 1;



SELECT ai.CTL_AVERB AS ctlAverb  FROM AVERBACAO_CONSISTENCIA ac  JOIN AVERBACAO_INDICE AI     
ON ac.CTL_AVERB = ai.CTL_AVERB
WHERE ac.SIT_AVERB = 0  AND ai.CTL_PESSO AND EXISTS
(SELECT se.ctl_pesso  FROM SEGURADO_EXCLUIDO_CONSISTENCIA se
WHERE se.STA_INATIVO = 0)
  AND (ai.CTL_PESSO, ai.NUM_RAMO)
   in ( SELECT sp.CTL_PESSO, sp.NUM_RAMO_SEG FROM SEGURADO_PARALELO sp )
ORDER BY ac.DHR_ALTER ASC LIMIT 1000
OPTIMIZE FOR 1 ROWS WITH UR;

