--ARQUIVO EFTP SOMPO DETALHE

SELECT DISTINCT CURRENT timestamp AS EMISSAO_PROPOSTA,
CASE
	WHEN FAT.NUM_PERIO_FAT = 1
	OR FAT.NUM_PERIO_FAT = 3 THEN
CASE
		WHEN PROPOSTA.DAT_INICI_VIG > DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-01') THEN PROPOSTA.DAT_INICI_VIG
		ELSE DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-01')
	END
	ELSE
CASE
		WHEN PROPOSTA.DAT_INICI_VIG > DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-16') THEN PROPOSTA.DAT_INICI_VIG
		ELSE DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-16')
	END
END AS INICIO_VIGENCIA,
PROPOSTA.NUM_APOLI AS APOLICE_MAE,
CASE
	WHEN FAT.NUM_PERIO_FAT = 3
	OR FAT.NUM_PERIO_FAT = 2 THEN
CASE
		WHEN PROPOSTA.DAT_FIM_VIG < LAST_DAY(DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-01')) THEN PROPOSTA.DAT_FIM_VIG
		ELSE LAST_DAY(DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-01'))
	END
	ELSE
CASE
		WHEN PROPOSTA.DAT_FIM_VIG < DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-15') THEN PROPOSTA.DAT_FIM_VIG
		ELSE DATE(LEFT(FAT.NUM_MES_CPT, 4) || '-' || RIGHT(FAT.NUM_MES_CPT, 2) || '-15')
	END
END AS FIM_VIGENCIA,
CASE
	WHEN RAMO.NUM_RAMO_SEG IN (66, 67, 68) THEN 53963
	ELSE SEG.NUM_SUCUR_PAM
END AS SUCURSAL,
FAT.SEQ_NUMER_FAT AS ID_FATURA,
COALESCE(P.COD_DOCUM_PRI, PESSOA.COD_DOCUM_PRI) AS DOCUMENTO,
RAMO.NUM_RAMO_SEG AS PRODUTO,
RAMO.NUM_RAMO_SSP AS RAMO_SUSEP,
CASE
	WHEN MOEDA.NUM_MOEDA = 14 THEN 1
	ELSE 3
END AS MOEDA,
(
SELECT
	SOMA.VLR_CALCU
FROM
	BIL_VALOR_SOMA_TIPO_TARIFA SOMA
WHERE
	SOMA.NUM_TARIF = 69
	AND SOMA.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT) AS VALOR_SOMA_AVERBACAO,
(
SELECT
	SUM(SOMA.VLR_CALCU)
FROM
	BIL_VALOR_SOMA_TIPO_TARIFA SOMA
WHERE
	SOMA.NUM_TARIF IN (61, 65, 67, 17)
		AND SOMA.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT) AS VALOR_CALCULADO,
FAT.DAT_VENCI_FAT AS VENCIMENTO_FATURA,
(
SELECT
	SOMA.VLR_CALCU
FROM
	BIL_VALOR_SOMA_TIPO_TARIFA SOMA
WHERE
	SOMA.NUM_TARIF = 70
	AND SOMA.SEQ_NUMER_FAT = FAT.SEQ_NUMER_FAT) AS QTDE_DE_AVERBACOES
,COALESCE(PROPOSTA.CTL_PEJUR_CIA,0) AS CTL_PEJUR_CIA	
FROM
V_BIL_FATURA FAT
INNER JOIN V_BIL_PROPOSTA PROPOSTA ON
PROPOSTA.SEQ_NUMER_PRS = FAT.SEQ_NUMER_PRS
INNER JOIN V_CRP_SUCURSAL_CIA_SEGURADORA SEG ON
SEG.CTL_SUCUR = PROPOSTA.CTL_SUCUR
INNER JOIN V_BIL_PESSOA_PROPOSTA PESSOA ON
PESSOA.CTL_PESSO = PROPOSTA.CTL_PESSO_CLI
INNER JOIN V_CRP_MOEDA MOEDA ON
MOEDA.NUM_MOEDA = PROPOSTA.NUM_MOEDA_PRS
INNER JOIN V_CRP_RAMO_SEGURO RAMO ON
RAMO.NUM_RAMO_SEG = PROPOSTA.NUM_RAMO_SEG
LEFT JOIN BIL_RELAC_PROPOSTA_DIVIS_CIA RELAC_DIV ON
RELAC_DIV.SEQ_NUMER_PRS = PROPOSTA.SEQ_NUMER_PRS
AND FAT.CTL_PESSO_DIC = RELAC_DIV.CTL_PESSO_DIC
LEFT JOIN V_CRP_PESSOA P ON
P.CTL_PESSO = RELAC_DIV.CTL_PESSO_DIC
WHERE
FAT.SEQ_NUMER_FAT IN (7000027242)