-- BILHET.V_BIL_ENVIA_COBRANCA source
SELECT
	f.SIT_ENVIO_FAT ,
	f.CTL_GRUPO_FAT ,
    f.SEQ_NUMER_FAT AS NOSSO_NUMERO,
    f.SIT_ENVIO_FAT AS SITUACAO_ENVIO,
    sp.NUM_CIA_PAM AS CIA,
    '2' AS TIPO_REGISTRO,
    LPAD(p.NUM_APOLI, 15, '0') AS APOLICE,
    LPAD(COALESCE(f.NUM_FATUR_CIA, 0), 15, 0) AS NR_FATURA,
    LPAD(F.NUM_PARCE, 2, '0') AS PRESTACAO,
    LPAD(p.COD_DOCUM_CLI, 15, '0') AS CPF_CNPJ,
    p.NUM_RAMO_SEG AS RAMO,
    RTRIM(CHAR(YEAR(f.DHR_FATUR))) || SUBSTR(DIGITS(MONTH(f.DHR_FATUR)), 9) || SUBSTR( DIGITS(DAY (f.DHR_FATUR)), 9) AS DATA_EMISSAO,
    RTRIM(CHAR(YEAR(f.DAT_VENCI_FAT))) || SUBSTR(DIGITS(MONTH(f.DAT_VENCI_FAT)), 9) || SUBSTR(DIGITS
    (DAY(f.DAT_VENCI_FAT)), 9) AS DATA_VENCIMENTO,
    LPAD(p.NUM_MOEDA_PRS, 2, '0') AS MOEDA,
    LPAD(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 61, 'C') + NVL(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 17, 'C'), 0) , 15, '0') AS PREMIO_LIQUIDO,
    LPAD(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 68, 'C'), 15, '0') AS PREMIO_TOTAL,
    LPAD(p.FILIAL_ADM, 2, '0') AS FILIAL_ADM,
    LPAD(f.SEQ_NUMER_FAT, 15, '0') AS NR_CONTA,
    SUBSTR(f.NUM_MES_CPT, 1, 4) AS ANO_REF,
    REPLACE(SUBSTR(f.NUM_MES_CPT, 5, 6), ' ', '') AS MES_REF,
    CASE
        f.NUM_PERIO_FAT
        WHEN 3
        THEN 2
        ELSE f.NUM_PERIO_FAT
    END AS FAT_REF,
    CASE
        f.IDT_ENVIO_CBR
        WHEN 'I'
        THEN '2'
        WHEN 'U'
        THEN '3'
        WHEN 'C'
        THEN '1'
    END AS STATUS_TRANSF,
    CASE
        F.SIT_FATUR
        WHEN 7
        THEN '14'
        ELSE '01'
    END AS TIPO_DOCUMENTO,
    LPAD((
            CASE f.NUM_PERIO_FAT
                WHEN 1
                THEN COALESCE(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 65, 'C'), 000000000000000)
                WHEN 3
                THEN COALESCE(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 67, 'C'), 000000000000000)
                ELSE COALESCE(BILHET.FC_TARIFA_FATURA(f.SEQ_NUMER_FAT, 65, 'C'), 000000000000000)
            END), 15, '0') AS CUSTO_ELETRONICO,
    LPAD(f.SEQ_NUMER_FAT, 11, '0') AS NR_PAMCARY,
    '  ' AS STATUS_CANCELAMENTO,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 60, 'T'), 0), 15, '0') AS PREMIO_BASICO,
    '   ' AS SPACE_3,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 69, 'A'), 0), 17, '0') AS
    TOTAL_MERCADORIA,
    '000' AS GRUPO_CONTA,
    COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 62, 'C'), 0) AS CRE_MIGR,
    '00000000000000' AS DEB_MIGR,
    COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 55, 'C'), 0) * -1 AS CREDITO,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 56, 'C'), 0), 14, '0') AS DEBITO,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 52, 'C'), 0), 17, '0') AS PREMIO_MINIMO,
    '00000000000000000' AS
    PREMIO_DEPOSITO,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 27, 'C'), 0), 17, '0') AS VALOR_PAMTAX,
    COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 12, 'C'), 0) * -1 AS DESCONTO,
    LPAD(COALESCE(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 57, 'C'), 0), 14, '0') AS JUROS,
    '00000000000000000' AS DIF_FAT,
    '00000000000000000' AS PREM_RA,
    LPAD(BILHET.FC_TARIFA_FATURA(F.SEQ_NUMER_FAT, 70, 'A'), 6, '0') AS QTDE_VIAGEM
FROM
    BILHET.TBIL_FATURA f
INNER JOIN BILHET.V_BIL_PROPOSTA p ON
    p.SEQ_NUMER_PRS = f.SEQ_NUMER_PRS
INNER JOIN PAMAIS.TCRP_CIA_SEGURADORA_PAMCARY sp ON
    sp.CTL_PEJUR_CIA = p.CTL_PEJUR_CIA
    AND sp.TIP_NEGOC = p.TIP_NEGOC
--LEFT JOIN PAMAIS.TCRP_SUCURSAL_CIA_SEGURADORA sc ON
--    p.CTL_SUCUR = sc.CTL_SUCUR
INNER JOIN seguro.TSEG_PROPOSTA_SEGURO tps ON
	tps.NUM_PROPT = p.NUM_PROPT
	AND tps.NUM_CIA_PAM = sp.NUM_CIA_PAM 
WHERE f.SIT_ENVIO_FAT = 4
AND f.CTL_GRUPO_FAT IS NULL
AND SEQ_NUMER_FAT IN ( 7000323143, 7000323146)
--AND sp.NUM_CIA_PAM = 367
ORDER BY CIA DESC --NOSSO_NUMERO;
    
SELECT * FROM SEGURO.TSEG_PROPOSTA_SEGURO
WHERE NUM_PROPT IN ( 
SELECT tp.NUM_PROPT 
FROM bilhet.TBIL_FATURA tf, bilhet.TBIL_PROPOSTA tp, pamais.TCRP_CIA_SEGURADORA_PAMCARY tcs,SEGURO.TSEG_PROPOSTA_SEGURO tps  
WHERE tp.SEQ_NUMER_PRS = tf.SEQ_NUMER_PRS 
	AND tp.CTL_PEJUR_CIA = tcs.CTL_PEJUR_CIA
	AND tcs.TIP_NEGOC = tcs.TIP_NEGOC 
	AND tp.NUM_PROPT = tps.NUM_PROPT 
	AND tcs.NUM_CIA_PAM = tps.NUM_CIA_PAM 
	AND tf.SIT_ENVIO_FAT = 4
--	AND tp.CTL_PEJUR_CIA = 17341
	AND tf.CTL_GRUPO_FAT IS NULL
	)
ORDER BY tcs.NUM_CIA_PAM DESC