/*
* SOMATORIA DE VIAGENS POR MOTORISTAS OPERAÇÃO TSV
* UNIÃO DAS INFORMAÇÕES NA BASE TRANSACIONAL E HISTORICA
* EXCETO VIAGENS CANCELADAS
*/

SELECT SUM(TOTAL1) TOTAL, NOM_PESSO MOTORISTAS, COD_DOCUM_PRI CPF 
FROM (
  SELECT COUNT(PV1.CTL_PLVIA) TOTAL1, P1.NOM_PESSO, P1.COD_DOCUM_PRI
  FROM PLANO_VIAGEM PV1,
       V_CRP_PESSOA P1,
       inf_motorista_plano_viagem M1
  WHERE 1=1
    AND PV1.CTL_OPERA_TIP = 397
    AND PV1.SIT_PLVIA <> 10
    AND PV1.CTL_PLVIA = M1.CTL_PLVIA
    AND P1.CTL_PESSO = M1.CTL_MOTOT
    AND PV1.dhr_inclu between to_date('01/01/2020','dd/mm/yyyy hh24:mi:ss') and to_date('31/12/2020','dd/mm/yyyy hh24:mi:ss')
    GROUP BY P1.NOM_PESSO,P1.COD_DOCUM_PRI
UNION ALL
  SELECT COUNT(PV2.CTL_PLVIA) TOTAL2, P2.NOM_PESSO,P2.COD_DOCUM_PRI
  FROM hissup.hist_PLANO_VIAGEM PV2, 
    hissup.texp_motorista_plano_viagem M2,
    V_CRP_PESSOA P2
  WHERE 1=1
    AND PV2.dhr_inclu between to_date('01/01/2020','dd/mm/yyyy hh24:mi:ss') and to_date('31/12/2020','dd/mm/yyyy hh24:mi:ss')
    AND PV2.CTL_OPERA_TIP = 397
    AND PV2.CTL_PLVIA = M2.CTL_PLVIA
    AND PV2.SIT_PLVIA <> 10
    AND P2.CTL_PESSO = M2.CTL_MOTOT
  GROUP BY P2.NOM_PESSO, P2.COD_DOCUM_PRI
  
) GROUP BY NOM_PESSO, COD_DOCUM_PRI