SELECT count(1)
/*
TO_CHAR(R.DHR_ALTER,'MM-YYYY') AS ANO_MES_REF 
,TO_CHAR(R.DHR_ALTER,'DD') AS DIA_REF
,TT.DES_OPERA_TIP AS OPERACAO
,T.TIP_ALERT_VIE
,T.DES_ALERT_VIE
,COUNT(1) AS QTD
*/
FROM RELAC_ALERTA_MOTOT_PLVIA R, 
      TIPO_ALERTA_VIAGEM T, 
      PLANO_VIAGEM P, 
      TIPO_OPERACAO TT,
      PERFIL_ALERTA_VIAGEM PA,
      RELAC_CONTATO RC, COMUNICACAO_RELAC_CONTATO CRC
WHERE T.TIP_ALERT_VIE = R.TIP_ALERT_VIE
AND R.CTL_PLVIA = P.CTL_PLVIA
AND P.CTL_OPERA_TIP = TT.CTL_OPERA_TIP
AND PA.CTL_VINCD = TT.CTL_VINCD_EMB
AND R.TIP_ALERT_VIE = PA.TIP_ALERT_VIE
AND RC.CTL_VINCD = PA.CTL_VINCD
AND RC.CTL_VINCD_RLD = PA.CTL_VINCD_RLD
AND RC.CTL_RELAC_CON = CRC.CTL_RELAC_CON
AND CRC.TIP_COMUN = 7
AND R.DHR_ALTER BETWEEN TO_DATE('01/05/2021 00:00:00','DD/MM/YYYY HH24:MI:SS')
AND TO_DATE('31/05/2021 23:59:59','DD/MM/YYYY HH24:MI:SS')
      
AND R.TIP_ALERT_VIE IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,41,43,45,47)
AND R.STA_ENVIA_MSG = 'S'
AND PA.CTL_VINCD_RLD IN ( SELECT DISTINCT V.CTL_VINCD FROM PLANO_VIAGEM PP,DESTINATARIO_PLANO_VIAGEM D,VINCULADO V
                          WHERE PP.CTL_PLVIA = P.CTL_PLVIA
                          AND D.CTL_PLVIA = PP.CTL_PLVIA
                          AND V.CTL_VINCD IN (D.CTL_DESTI,PP.CTL_TRNSP, PP.CTL_REMET)
                        )
GROUP  BY TO_CHAR(R.DHR_ALTER,'MM-YYYY'), TO_CHAR(R.DHR_ALTER,'DD'), TT.DES_OPERA_TIP, T.TIP_ALERT_VIE, T.DES_ALERT_VIE        
ORDER  BY DIA_REF, TT.DES_OPERA_TIP, T.TIP_ALERT_VIE


/*ALERTAS TABELAS DE EMAILS DE GRUPO DE INTERESSE*/

SELECT 
TO_CHAR(R.DHR_ALTER,'MM-YYYY') AS ANO_MES_REF, 
TO_CHAR(R.DHR_ALTER,'DD') AS DIA_REF,
TT.DES_OPERA_TIP AS OPERACAO,
T.TIP_ALERT_VIE,
T.DES_ALERT_VIE,
COUNT(1) QTD
FROM RELAC_ALERTA_MOTOT_PLVIA R, 
      TIPO_ALERTA_VIAGEM T, 
      PLANO_VIAGEM P, 
      TIPO_OPERACAO TT
WHERE T.TIP_ALERT_VIE = R.TIP_ALERT_VIE
AND R.CTL_PLVIA = P.CTL_PLVIA
AND P.CTL_OPERA_TIP = TT.CTL_OPERA_TIP
AND R.DHR_ALTER BETWEEN TO_DATE('01/05/2021 00:00:00','DD/MM/YYYY HH24:MI:SS')
AND TO_DATE('31/05/2021 23:590:59','DD/MM/YYYY HH24:MI:SS')
      
AND R.TIP_ALERT_VIE IN (36,39,40,46)
AND R.STA_ENVIA_MSG = 'S'
AND 0 < (SELECT COUNT(1)
            FROM PLANO_VIAGEM PP, INF_CONTATO_ALERTA A, INF_RELAC_CONTT_ALERT B 
            WHERE PP.CTL_PLVIA = P.CTL_PLVIA
            AND A.CTL_CONTT_ALE = B.CTL_CONTT_ALE
            AND B.CTL_OPERA_TIP = PP.CTL_OPERA_TIP
            AND B.TIP_ALERT_VIE = R.TIP_ALERT_VIE )     

GROUP  BY TO_CHAR(R.DHR_ALTER,'MM-YYYY'), TO_CHAR(R.DHR_ALTER,'DD'), TT.DES_OPERA_TIP, T.TIP_ALERT_VIE, T.DES_ALERT_VIE 
ORDER  BY DIA_REF, TT.DES_OPERA_TIP, T.TIP_ALERT_VIE;  

/*ALERTAS EMAILS TELERISCO*/
SELECT 
TO_CHAR(R.DHR_ALTER,'MM-YYYY') AS ANO_MES_REF, 
TO_CHAR(R.DHR_ALTER,'DD') AS DIA_REF,
TT.DES_OPERA_TIP AS OPERACAO,
T.TIP_ALERT_VIE,
T.DES_ALERT_VIE,
COUNT(1) QTD
FROM RELAC_ALERTA_MOTOT_PLVIA R, 
      TIPO_ALERTA_VIAGEM T, 
      PLANO_VIAGEM P, 
      TIPO_OPERACAO TT
WHERE T.TIP_ALERT_VIE = R.TIP_ALERT_VIE
AND R.CTL_PLVIA = P.CTL_PLVIA
AND P.CTL_OPERA_TIP = TT.CTL_OPERA_TIP
AND R.DHR_ALTER BETWEEN TO_DATE('18/05/2021 00:00:00','DD/MM/YYYY HH24:MI:SS')
AND TO_DATE('18/05/2021 09:30:59','DD/MM/YYYY HH24:MI:SS')
      
AND R.TIP_ALERT_VIE IN (48)
AND R.STA_ENVIA_MSG = 'S'
AND 0 < (SELECT COUNT(1) 
            FROM PLANO_VIAGEM PP, INF_CONTATO_ALERTA A, INF_RELAC_CONTT_ALERT B 
            WHERE PP.CTL_PLVIA = P.CTL_PLVIA
            AND A.CTL_CONTT_ALE = B.CTL_CONTT_ALE
            AND B.CTL_OPERA_TIP = 51
            AND B.TIP_ALERT_VIE = 48 )     

GROUP  BY TO_CHAR(R.DHR_ALTER,'MM-YYYY'), TO_CHAR(R.DHR_ALTER,'DD'), TT.DES_OPERA_TIP, T.TIP_ALERT_VIE, T.DES_ALERT_VIE 
ORDER  BY DIA_REF, TT.DES_OPERA_TIP, T.TIP_ALERT_VIE; 

/*STATUS DE NOTIFICACAO DE PLANO. CONFIGURADO POR PLANO DE VIAGEM (NÃO EXISTE HISTORICO, APENAS GUARDAMOS O UÇTIMO REGISTRO) */
SELECT 
TO_CHAR(PVN.DHR_ALTER,'MM-YYYY') AS ANO_MES_REF, 
TO_CHAR(PVN.DHR_ALTER,'DD') AS DIA_REF,
TT.DES_OPERA_TIP AS OPERACAO,
'1000' AS ALERTA, 'STATUS NOTIFICACAO PLANO' AS DESCRICAO,

COUNT(1) QTD
FROM PLANO_VIAGEM_NOTIFICACAO PVN, 
      PLANO_VIAGEM P, RELAC_NOTIF_OPERA_EMAIL RNO, 
      TIPO_OPERACAO TT
WHERE P.CTL_PLVIA = PVN.CTL_PLVIA 
AND PVN.CTL_NOTIF_EML = RNO.CTL_NOTIF_EML 
AND P.CTL_OPERA_TIP = TT.CTL_OPERA_TIP
AND PVN.DHR_ALTER BETWEEN TO_DATE('18/05/2021 00:00:00','DD/MM/YYYY HH24:MI:SS')
AND TO_DATE('18/05/2021 09:30:59','DD/MM/YYYY HH24:MI:SS')

GROUP  BY TO_CHAR(PVN.DHR_ALTER,'MM-YYYY'), TO_CHAR(PVN.DHR_ALTER,'DD'), TT.DES_OPERA_TIP
ORDER  BY DIA_REF, TT.DES_OPERA_TIP; 


select to_char(dhr_alter,'dd/mm/yyyy hh24:mi:ss'), p.* from PLANO_VIAGEM_NOTIFICACAO p
where ctl_plvia = 11426544

select to_char(dhr_alter,'dd/mm/yyyy hh24:mi:ss'), r.* 
from RELAC_NOTIF_OPERA_EMAIL r
where ctl_notif_eml in (509
,521
,503
,511
,500
,508
,512
,507
,506
,522
,518
,510
,513
,515
,501
,505
,502
,504
)
= 'deletar@gmail.com'

select * from relac_contato ctl_relac_con
SELECT * FROM COMUNICACAO_CONTATO ctl_contt ctl_comun_cot
SELECT * from comunicacao_relac_contato ctl_relac_con

select FC_VINCULADO_NOM_GUERR(RC.CTL_VINCD)
,FC_VINCULADO_NOM_GUERR(RC.CTL_VINCD_RLD)
,CRC.CTL_RELAC_CON
,RC.NOM_CONTT
,CRC.DES_COMUN_VIN
FROM COMUNICACAO_RELAC_CONTATO CRC 
              ,relac_contato RC
WHERE RC.ctl_relac_con = CRC.ctl_relac_con
AND CRC.TIP_COMUN = 7
AND UPPER(CRC.DES_COMUN_VIN) LIKE '%WMSUL.COM.BR%'


select * from inf_contato_alerta 
where upper(des_email_ale) like '%WMSUL.COM.BR%'

select * from relac_notif_opera_email
where upper(des_email_ntf) like '%WMSUL.COM.BR%'

WAL-MART.COM, WMNE.COM.BR, WMSUL.COM.BR 


SELECT * FROM INF_RELAC_CONTT_ALERT

