/*DELETAR RELACIONAMENTO VINCULADO E SUAS DEPENDENCIAS*/


SELECT * FROM REF_PARADA_VINCULADO
WHERE CTL_PROVE_VIN IN (
  SELECT CTL_PROVE_VIN FROM PROVTECN_RELVINCD
  WHERE CTL_VINCD = 1638126
  and tip_relac in (1,2,3,4)
  
  )
  

SELECT FC_VINCULADO_NOM_GUERR(X.CTL_VINCD) operacao,
      FC_VINCULADO_NOM_GUERR(X.CTL_VINCD_RLD) entidades,
      v.cod_ativi,
        X.*  
FROM RELACIONAMENTO_VINCULADO X, vinculado v
WHERE x.CTL_VINCD = 1195848
and v.ctl_vincd = x.ctl_vincd_rld
AND TIP_RELAC in (1,2,3, 4)
ORDER BY ENTIDADES DESC




DELETE FROM REF_PARADA_VINCULADO
WHERE CTL_PROVE_VIN IN (
  SELECT CTL_PROVE_VIN FROM PROVTECN_RELVINCD
  WHERE CTL_VINCD = 1993332
  AND TIP_RELAC in (1, 2, 3, 4)
  )


DELETE FROM PROVTECN_RELVINCD
WHERE CTL_VINCD = 1993332
AND TIP_RELAC IN (1, 2, 3, 4)


DELETE FROM RELACIONAMENTO_VINCULADO
WHERE CTL_VINCD = 1993332
AND CTL_VINCD_RLD <> 1993332


SELECT * FROM RELACIONAMENTO_VINCULADO
WHERE CTL_VINCD = 1993332
AND CTL_VINCD_RLD = 1195848
AND TIP_RELAC = 4



select * from usuario_internet
where usr_name like '%CCN.PAMCARY%'



SELECT COLUMN_NAME,TABLE_NAME
FROM all_cons_columns
WHERE CONSTRAINT_NAME ='CTRLTRVI_CTLTRAVI_FK2'
