SELECT RPD.CTL_PLVIA,  
       TDF.DES_DOCUM_FIS, 
       DFC.COD_DOCUM_FIS,
       (CASE WHEN (RPD.ORD_DESTI = 0 ) THEN 'ORIGEM'
             ELSE 'DESTINO' END) ORD_DEST,
       FC_VINCULADO_NOM_GUERR(RPD.CTL_DESTI) AS ENTIDADE,
       TO_CHAR(RPD.DHR_ALTER,'DD/MM/YYYY HH24:MI') AS INCLUSAO
FROM DOCUMENTO_FISCAL_CLIENTE DFC,
     --RELAC_PLVIA_DOCUMENTO RPD,
     THIST_RELAC_PLVIA_DOCUM RPD,
     TIPO_DOCUMENTO_FISCAL TDF
WHERE DFC.CTL_DOCUM_CLI = RPD.CTL_DOCUM_CLI
  AND DFC.CTL_OPERA_TIP = 310
  AND TDF.TIP_DOCUM_FIS = DFC.TIP_DOCUM_FIS
  AND TDF.TIP_DOCUM_FIS <> 3
  AND RPD.DHR_ALTER between to_date('01/01/2018 00:00:00','dd/mm/yyyy hh24:mi:ss') and to_date('31/08/2018 23:59:59','dd/mm/yyyy hh24:mi:ss')
ORDER BY RPD.DHR_ALTER, RPD.CTL_PLVIA

18/02