SELECT PV.CTL_PLVIA AS PLANO, 
PV.CTL_OPERA_TIP AS OPERACAO, O.DES_OPERA_TIP AS CLIENTE,
NVL((SELECT V.COD_PLACA
      FROM V_CRP_VEICULO V,
           INF_VEICU_PLANO_VIAGEM PL
     WHERE V.NUM_CATEG_VEI NOT IN (3)
       AND PL.CTL_PLVIA = PV.CTL_PLVIA
       AND V.CTL_VEICU = PL.CTL_VEICU
       AND rownum = 1),'') AS VEICULO,
NVL((SELECT V.COD_PLACA
		  FROM V_CRP_VEICULO              V,
           INF_VEICU_PLANO_VIAGEM PL
     WHERE V.NUM_CATEG_VEI IN (3)
       AND PL.CTL_PLVIA = PV.CTL_PLVIA
       AND V.CTL_VEICU = PL.CTL_VEICU
       AND rownum = 1),'') AS CARRETA,
MV.NOM_MOTORISTA AS MOTORISTA,
ODV.COD_DOCUM AS DOC_ORIGEM, 
OV.NOM_GUERR AS ORIGEM, 
RM.ORD_DESTI,
RM.NUM_SEQUE,
DDV.COD_DOCUM AS DOC_DESTINO, 
DV.NOM_GUERR AS DESTINO,
EDV.NUM_LATIT AS LAT_DESTINO,
EDV.NUM_LONGI AS LONG_DESTINO,
PV.NUM_LATIT_ULT AS LAT_ULT_POSIC,
PV.NUM_LONGI_ULT AS LONG_ULT_POSIC,
(SELECT to_char(dhr_efeti_rea,'DD/MM/YYYY HH24:MI:SS') 
      FROM ROTEIRO_MOTORISTA 
      WHERE CTL_PLVIA = PV.CTL_PLVIA 
      AND ORD_DESTI = 0 
      AND CTL_PARAD = 10 
      AND sit_fase_rea in ('R', 'T')) AS DT_REA_IV,
(SELECT      
      FC_RELATORIO_DADOS_EVENTO_VIA(RM.CTL_RTMOT)
    FROM 
      ROTEIRO_MOTORISTA RM
    WHERE       
    RM.CTL_PLVIA = PV.CTL_PLVIA 
    AND RM.ORD_DESTI = 0         
    AND RM.CTL_PARAD = 10        
    AND RM.sit_fase_rea in ('R', 'T')) AS REGISTRO_VIA_IV,
(SELECT     
      RM.COD_USER     
    FROM 
      ROTEIRO_MOTORISTA RM,
      PLANO_VIAGEM P
    WHERE 
    P.CTL_PLVIA = PV.CTL_PLVIA
    AND P.CTL_PLVIA = RM.CTL_PLVIA 
    AND RM.ORD_DESTI = 0
    AND RM.CTL_PARAD = 10       
    AND RM.SIT_FASE_REA IN ('R', 'T')) AS USER_VIA_IV,
(SELECT 
      DHR_EFETI_REA FROM roteiro_motorista
    WHERE ctl_plvia = PV.CTL_PLVIA
    AND SIT_FASE_REA IN ('R', 'T')  
    and ctl_parad = 12          
    AND ORD_DESTI = RM.ORD_DESTI) AS DT_REA_FV,
(SELECT      
      FC_RELATORIO_DADOS_EVENTO_VIA(CTL_RTMOT)  
    FROM    
      ROTEIRO_MOTORISTA      
    WHERE ctl_plvia = PV.CTL_PLVIA
    AND SIT_FASE_REA IN ('R', 'T')  
    and ctl_parad = 12          
    AND ORD_DESTI = RM.ORD_DESTI) AS REGISTRO_VIA_FV,
(SELECT     
      COD_USER
    FROM 
      ROTEIRO_MOTORISTA
    WHERE ctl_plvia = PV.CTL_PLVIA
    AND SIT_FASE_REA IN ('R', 'T')  
    and ctl_parad = 12          
    AND ORD_DESTI = RM.ORD_DESTI) AS USER_VIA_FV,
PV.DES_PRACA_ULT AS ULTIMA_POSIC, 
DHR_POSIC_ULT AS EVENTO_ULT_POSIC,
(SELECT DFC.COD_DOCUM_FIS AS DOCUMENTO  
                  FROM  relac_plvia_documento rpd,    
                        DOCUMENTO_FISCAL_CLIENTE DFC
                  WHERE RPD.CTL_PLVIA = PV.CTL_PLVIA
                        AND DFC.TIP_DOCUM_FIS = 7 
                        AND RPD.ORD_DESTI = 0
                        AND RPD.CTL_DOCUM_CLI = DFC.CTL_DOCUM_CLI
                        AND ROWNUM = 1) AS DOCUMENTO,
TV.NOM_GUERR AS TRANSPORTADORA, 
TP.SIG_PARAD AS TIPO_EVENTO, 
RM.DHR_PREVI_SIS AS DATA_EVENTO_PREVISAO, 
(SELECT     
      DHR_EFETI_REA
    FROM 
      ROTEIRO_MOTORISTA      
    WHERE 
      CTL_RTMOT = RM.CTL_RTMOT          
    AND SIT_FASE_REA IN ('R', 'T')
    AND ROWNUM = 1) AS DATA_EVENTO,
FC_RELATORIO_DADOS_EVENTO_VIA(RM.CTL_RTMOT) AS REGISTRO_VIA_EVENTO, 
(SELECT     
      COD_USER   
    FROM 
      ROTEIRO_MOTORISTA      
    WHERE 
      CTL_RTMOT = RM.CTL_RTMOT          
    AND SIT_FASE_REA IN ('R', 'T')
    AND ROWNUM = 1) AS USER_REGISTRO_VIA_EVENTO, 
PV.DHR_INCLU AS DATA_INCLUSAO,
T.DES_OPERA_VIE AS TIPO_OPERACAO_VIAGEM,
S.DES_SITUA AS SITUACAO_PLANO,
CASE
  WHEN PV.DHR_ATVIE_PLN is NOT NULL THEN
       PV.DHR_ATVIE_PLN
  ELSE
       PV.DHR_INCLU
  END AS DATA_ATIVACAO,
CASE
  WHEN PV.DHR_ATVIE_PLN is NOT NULL THEN
       TO_CHAR(PV.DHR_ATVIE_PLN, 'MM/YYYY')
  ELSE
       TO_CHAR(PV.DHR_INCLU, 'MM/YYYY')
  END AS ANO_MES,
  FC_EVENTO_PREVISTO(PV.CTL_PLVIA, 24, 0) AS DATA_CH_ORIGEM,
  FC_EVENTO_PREVISTO(PV.CTL_PLVIA, 24, 1) AS DATA_CH_DESTINO,
PV.QTD_TOTAL_CGA AS PESO,
(SELECT dhr_efeti_rea 
      FROM ROTEIRO_MOTORISTA 
      WHERE CTL_PLVIA = PV.CTL_PLVIA 
      AND ORD_DESTI = 1 
      AND CTL_PARAD = 24 
      AND sit_fase_rea in ('R', 'T')) AS DT_REA_CH,

(SELECT tn.des_tipo_neg 
FROM PLANO_VIAGEM PVD, DESTINATARIO_PLANO_VIAGEM DPVD, RELAC_TIPO_NEGOCIO_VINCD neg, TIPO_NEGOCIO_OPERA tn 
WHERE PVD.CTL_PLVIA = pv.ctl_plvia
AND PVD.CTL_PLVIA = DPVD.CTL_PLVIA
AND DPVD.ORD_DESTI = rm.ord_desti
AND PVD.CTL_OPERA_TIP = pv.ctl_opera_tip
AND DPVD.ctl_desti = neg.ctl_vincd(+)
AND PVD.CTL_OPERA_TIP = TN.CTL_OPERA_TIP
AND neg.ctl_negoc_opr = tn.ctl_negoc_opr(+)) AS des_tipo_neg_destino,

(SELECT 
      DHR_PREVI_SIS FROM roteiro_motorista
    WHERE ctl_plvia = PV.CTL_PLVIA
    and ctl_parad = 24          
    and ORD_DESTI > 0
    AND ORD_DESTI = RM.ORD_DESTI) AS DT_PREV_CH,
(SELECT 
      DHR_PREVI_SIS FROM roteiro_motorista
    WHERE 
    ctl_plvia = PV.CTL_PLVIA
    and ctl_parad IN (10,12)
    and ORD_DESTI > 0
    AND ORD_DESTI = RM.ORD_DESTI) AS DT_PREV_FV,
FC_VINCULADO_ENDERECO_PRACA(RM.CTL_PTOPD,1) AS PRACA,
FC_VINCULADO_ENDERECO_SIGLAUF(RM.CTL_PTOPD,1) AS UF
    
FROM PLANO_VIAGEM PV, INF_MOTORISTA_PLANO_VIAGEM MPV, V_CRP_MOTORISTA MV,
DOC_VINCULADO ODV, VINCULADO OV, DOC_VINCULADO DDV, VINCULADO DV, ENDERECO_VINCULADO EDV,
VINCULADO TV, ROTEIRO_MOTORISTA RM, TIPO_PARADA TP, TIPO_OPERACAO O, 
TIPO_OPERACAO_VIAGEM T, SITUACAO_PLANO_VIAGEM S
WHERE O.CTL_OPERA_TIP = PV.CTL_OPERA_TIP
AND T.TIP_OPERA_VIE = PV.TIP_OPERA_VIE
AND S.SIT_PLVIA = PV.SIT_PLVIA
AND PV.CTL_PLVIA = MPV.CTL_PLVIA(+)
AND MPV.CTL_MOTOT = MV.CTL_MOTOT(+)
AND PV.CTL_REMET = OV.CTL_VINCD
AND OV.CTL_VINCD = ODV.CTL_VINCD
AND PV.CTL_PLVIA = RM.CTL_PLVIA
AND RM.CTL_PARAD = TP.CTL_PARAD
AND RM.CTL_PTOPD = DV.CTL_VINCD(+)
AND DV.CTL_VINCD = DDV.CTL_VINCD(+)
AND DV.CTL_VINCD = EDV.CTL_VINCD(+)
AND PV.CTL_TRNSP = TV.CTL_VINCD
AND RM.CTL_PARAD NOT IN (13,25)
AND PV.SIT_PLVIA <> 10
AND PV.CTL_OPERA_TIP = 20
AND PV.CTL_PLVIA = 8985856



