select
	RDPV.CTL_PLVIA,
	TIPO.DES_OPERA_TIP,
	MD.NOM_MODEL_DIO,
	MD.NUM_MODEL_DIO,
	PT.CTL_PROVE_TEN,
	PT.NOM_FANTS,
	MC.TIP_MEIO_CMU,
	MC.DES_MEIO_CMU,
	D.COD_DISPO_RST,
	CDPC.CTL_CLASS_DIO,
	CDPC.DES_CLASS_DIO,
	RDPV.COD_USER,
	RDPV.DHR_ALTER	
from
	TINF_RELAC_DISPO_PLANO_VIAGEM RDPV,
	TINF_DISPOSITIVO D,
	TINF_RELAC_PROVE_RASTR_DISPO RPRD,
	TINF_MODELO_DISPOSITIVO MD,
	PAMAIS_PRD.V_CRP_PROVEDOR_TECNOLOGIA PT,
	TINF_MEIO_COMUNICACAO MC,
	TINF_CLASS_DISPO_PROTE_COMPL CDPC,
	PLANO_VIAGEM PV,
	TIPO_OPERACAO TIPO
where
	RPRD.CTL_PROVE_TEN = 6269
	and RDPV.ctl_class_dio = 4
	and RDPV.CTL_DISPO_RST = D.CTL_DISPO_RST
	and RDPV.CTL_DISPO_RST = RPRD.CTL_DISPO_RST
	and RPRD.TIP_RASTR = MD.TIP_RASTR
	and RPRD.CTL_PROVE_TEN = MD.CTL_PROVE_TEN
	and RPRD.TIP_MEIO_CMU = MD.TIP_MEIO_CMU
	and RPRD.TIP_MEIO_CMU = MC.TIP_MEIO_CMU
	and RPRD.NUM_MODEL_DIO = MD.NUM_MODEL_DIO
	and RPRD.CTL_PROVE_TEN = PT.CTL_PROVE_TEN
	and RDPV.CTL_CLASS_DIO = CDPC.CTL_CLASS_DIO
	and PV.CTL_PLVIA = RDPV.CTL_PLVIA
	and TIPO.CTL_OPERA_TIP = PV.CTL_OPERA_TIP
	and RDPV.DHR_ALTER between '2024-11-01 00:00:00' and '2024-11-30 23:59:59'
 