
/*Qtde Entidades cadastradas com CPF*/
/*
  1	EMBARCADOR X CLIENTE COMPRADOR
  2	EMBARCADOR X TRANSPORTADORA
  3	EMBARCADOR X ORIGEM EMBARQUE
  4	EMBARCADOR X USUARIO INTERNET
*/
SELECT a.TIP_RELAC, count(a.CTL_VINCD_RLD) 
FROM relacionamento_vinculado a
INNER JOIN doc_vinculado b 
ON a.CTL_VINCD_RLD = b.CTL_VINCD 
WHERE b.TIP_DOCUM = 2
GROUP BY a.TIP_RELAC
	
/*Qdte motoristas com CPF*/
SELECT count(1) FROM PAMAIS_PRD.CRP_PESSOA 
WHERE tip_docum_pri = 2



/*Qtde proprietarios de Veiculos PF	*/
SELECT count(1) 
FROM INF_VEICU_PROPR_MOTOT A 
INNER JOIN PAMAIS_PRD.V_CRP_PESSOA B 
ON B.CTL_PESSO = A.CTL_MOTOT 
WHERE B.TIP_DOCUM_PRI = 2
