SELECT 
(SELECT M.COD_DOCUM_MOT FROM V_CRP_MOTORISTA M, INF_MOTORISTA_PLANO_VIAGEM MPV 
  WHERE M.CTL_MOTOT = MPV.CTL_MOTOT
  AND MPV.ORD_MOTOT =1
  AND MPV.CTL_PLVIA = R.CTL_PLVIA) AS DOC_MOTORISTA,
(SELECT M.NOM_MOTORISTA FROM V_CRP_MOTORISTA M, INF_MOTORISTA_PLANO_VIAGEM MPV 
  WHERE M.CTL_MOTOT = MPV.CTL_MOTOT
  AND MPV.ORD_MOTOT =1
  AND MPV.CTL_PLVIA = R.CTL_PLVIA) AS NOME_MOTORISTA,
T.DES_ALERT_VIE AS TIPO_ALERTA,
TO_CHAR(R.DHR_ALTER,'DD/MM/YYYY HH24:MI') AS DATA_GERACAO_ALERTA,
R.CTL_PLVIA AS PLANO,
R.COD_PLACA_CAV AS VEICULO,
'TSV' AS TIPO_OPERACAO,
(SELECT DES_OPERA_VIE FROM TIPO_OPERACAO_VIAGEM TT, PLANO_VIAGEM P 
  WHERE TT.TIP_OPERA_VIE = P.TIP_OPERA_VIE AND P.CTL_PLVIA = R.CTL_PLVIA) AS TIPO_OPERACAO_VIAGEM,
FC_RELATORIO_DOCUMENTO_CLIENTE(R.CTL_PLVIA) AS DOC_PROPRIO_CLIENTE,
(SELECT FC_VINCULADO_NOM_GUERR(CTL_TRNSP) FROM PLANO_VIAGEM WHERE CTL_PLVIA = R.CTL_PLVIA) AS TRANSPORTADORA,
(SELECT FC_VINCULADO_NOM_GUERR(CTL_REMET) FROM PLANO_VIAGEM WHERE CTL_PLVIA = R.CTL_PLVIA) AS ORIGEM,
(SELECT FC_VINCULADO_NOM_GUERR(CTL_DESTI) FROM PLANO_VIAGEM WHERE CTL_PLVIA = R.CTL_PLVIA) AS DESTINO_FINAL
FROM RELAC_ALERTA_MOTOT_PLVIA r, TIPO_ALERTA_VIAGEM T
WHERE r.CTL_PLVIA IN (SELECT CTL_PLVIA FROM PLANO_VIAGEM WHERE CTL_OPERA_TIP = 397)
AND r.DHR_ALTER BETWEEN TO_DATE('21/11/2018 00:00:00','DD/MM/YYYY HH24:MI:SS') 
AND TO_DATE('21/12/2018 23:59:59','DD/MM/YYYY HH24:MI:SS')
AND r.TIP_ALERT_VIE IN (23)
AND R.STA_ENVIA_MSG = 'S'
AND R.TIP_ALERT_VIE = T.TIP_ALERT_VIE
order by ctl_alert_plv;


select * from tipo_alerta_viagem