SELECT 
  IIRTN_GRMN,
  IIRTN_ACCOUNTNUMBER,
  IIRTN_MCTADDRESS,
  IIRTN_MSGPRIORITY,
  IIRTN_VEHICLEIGNITION,
  IIRTN_MACRONUMBER,
  IIRTN_MACROVERSION,
  IIRTN_BINARYDATATYPE,
  to_char(IIRTN_MESSAGETIME,'DD/MM/YYYY HH24:MI:SS') AS IIRTN_MESSAGETIME,
  IIRTN_TEXT,
  IIRTN_LATITUDE,
  IIRTN_LONGITUDE,
  to_char(IIRTN_TIMEPOSITION,'DD/MM/YYYY HH24:MI:SS') AS IIRTN_TIMEPOSITION,
  IIRTN_LANDMARK,
  IIRTN_STATUSLEITURA
FROM TAUX_FILAMSGREC_FMR
WHERE IIRTN_ACCOUNTNUMBER = 32189213