/* LOCALIZA ROTAS POR PLANO DE VIAGEM*/
SELECT PV.CTL_PLVIA, COUNT(1)
FROM DESTINATARIO_PLANO_VIAGEM DPV, 
     PLANO_VIAGEM PV
WHERE PV.CTL_PLVIA = DPV.CTL_PLVIA
AND PV.CTL_OPERA_TIP = 441
GROUP BY PV.CTL_PLVIA

SELECT PV.CTL_PLVIA AS VIAGEM
      ,PV.CAM_PREVI_VIE AS ROTA_COMPLETA
      ,DPV.ORD_DESTI AS ORDEM_ENTREGA
      ,R.NOM_ROTA AS NOME_ROTA
      ,FC_VINCULADO_NOM_GUERR(R.CTL_VINCD_ORI) AS PONTO_INICIAL
      ,FC_VINCULADO_NOM_GUERR(R.CTL_VINCD_DES) AS PONTO_FINAL
      ,R.QTD_METRO_DTI AS DISTANCIA
      ,DES_COORD_ROT AS POLYLINE
FROM PLANO_VIAGEM PV
    ,DESTINATARIO_PLANO_VIAGEM DPV
    ,INF_ROTA R
WHERE PV.CTL_PLVIA = DPV.CTL_PLVIA
AND R.CTL_ROTA_GRI = DPV.CTL_ROTA_GRI
AND PV.CTL_PLVIA = 11441606
ORDER BY DPV.ORD_DESTI

SELECT * FROM INF_ROTA
SELECT * FROM DESTINATARIO_PLANO_VIAGEM