select to_char(dhr_event,'dd/mm/yyyy hh24:mi:ss'), l.* from log_monitora_terminal l
where num_termn = 834124
and tip_event_ter <> 99
order by dhr_event desc
and tip_event_ter = 43
order by dhr_event desc

select * from log_monitora_terminal_det
where num_seque_ter = 81567782
and num_termn = 834124

865518
817471
958714

Macro 62 Versao 1
INCLUSAO DE PLANO DE VIAGEM 
CPF 04083453818 
CARRETA ANH1385 
ORIGEM 16 
DESTINO(S)
D1 10 
DESCARGA /     CARGA X 
D2 10


803599 - 1023784
867865 - 1023538
816173 - 1023540
819337 - 1023373
