SELECT TO_CHAR(PV.DHR_INCLU,'DD/MM/YYYY HH24:MI') AS INCLUSAO,
       TO_CHAR(PV.DHR_ATVIE_PLN,'DD/MM/YYYY HH24:MI') AS ATIVACAO,
       TO_CHAR(PV.DHR_MANUT,'DD/MM/YYYY HH24:MI') AS ULTIMA_ALTERACAO,
       PV.CTL_PLVIA AS PLANO_VIAGEM,
       TP.DES_OPERA_TIP AS OPERACAO,
       TOV.DES_OPERA_VIE AS OPERACAO_VIAGEM,
       PV.VLR_TOTAL_EMB AS VALOR_TOTAL_EMBARQUE,
       PV.QTD_TOTAL_CGA AS QTD_TOTAL_CARGA,

       (SELECT COD_DOCUM FROM DOC_VINCULADO 
          WHERE CTL_VINCD = PV.CTL_TRNSP) AS CNPJ_TRANSPORTADORA,
       
       FC_VINCULADO_NOM_GUERR(PV.CTL_TRNSP) AS TRANSPORTADORA,
       
       (SELECT COD_DOCUM FROM DOC_VINCULADO 
          WHERE CTL_VINCD = PV.CTL_REMET) AS CNPJ_ORIGEM,
       
       FC_VINCULADO_NOM_GUERR(PV.CTL_REMET) AS ORIGEM,
       
       EVO.NUM_LATIT AS LATITUDE_ORIGEM,
       EVO.NUM_LONGI AS LONGITUDE_ORIGEM,
       EVO.COD_CEP_END AS CEP_ENDERECO_ORIGEM,
       PO.DES_PRACA AS PRACA_ORIGEM,
       PO.NUM_CEP AS CEP_PRACA_ORIGEM,
       UFO.SIG_UNFED AS UF_ORIGEM,
       PO.NUM_IBGE AS IBGE_ORIGEM,
  
  
       (SELECT TO_CHAR(RMO.DHR_PREVI_SIS,'DD/MM/YYYY HH24:MI') FROM ROTEIRO_MOTORISTA RMO
        WHERE RMO.CTL_PLVIA = PV.CTL_PLVIA
        AND RMO.CTL_PTOPD = PV.CTL_REMET
        AND RMO.ORD_DESTI = 0
        AND RMO.CTL_PARAD = 10) AS DHR_PREVI_ORIGEM,

       (SELECT TO_CHAR(RMR.DHR_EFETI_REA,'DD/MM/YYYY HH24:MI') FROM ROTEIRO_MOTORISTA RMR
        WHERE RMR.CTL_PLVIA = PV.CTL_PLVIA
        AND RMR.CTL_PTOPD = PV.CTL_REMET
        AND RMR.ORD_DESTI = 0
        AND RMR.SIT_FASE_REA IN('R','T')
        AND RMR.CTL_PARAD = 10) AS DHR_REAL_ORIGEM,

       (SELECT COUNT(1) 
           FROM DESTINATARIO_PLANO_VIAGEM 
           WHERE CTL_PLVIA = PV.CTL_PLVIA) AS QTDE_DESTINOS,
       
       (SELECT COD_DOCUM FROM DOC_VINCULADO 
          WHERE CTL_VINCD = PV.CTL_DESTI) AS CNPJ_DESTINO,
       
       FC_VINCULADO_NOM_GUERR(PV.CTL_DESTI) AS DESTINO,
       
       EVD.NUM_LATIT AS LATITUDE_DESTINO,
       EVD.NUM_LONGI AS LONGITUDE_DESTNO,
       EVD.COD_CEP_END AS CEP_ENDERECO_DESTINO,
       PD.DES_PRACA AS PRACA_DESTINO,
       PD.NUM_CEP AS CEP_PRACA_DESTINO,
       UFD.SIG_UNFED AS UF_DESTINO,
       PD.NUM_IBGE AS IBGE_DESTINO,

       (SELECT TO_CHAR(DHR_PREVI_SIS,'DD/MM/YYYY HH24:MI') FROM ROTEIRO_MOTORISTA RMD
        WHERE RMD.CTL_PLVIA = PV.CTL_PLVIA
        AND RMD.CTL_PTOPD = PV.CTL_DESTI
        AND RMD.CTL_PARAD = 12
        AND RMD.ORD_DESTI = (SELECT MAX(ORD_DESTI) FROM ROTEIRO_MOTORISTA WHERE CTL_PLVIA = PV.CTL_PLVIA  AND CTL_PARAD = 12)
        ) AS DHR_PREVI_DESTINO,

       (SELECT TO_CHAR(DHR_EFETI_REA,'DD/MM/YYYY HH24:MI') FROM ROTEIRO_MOTORISTA RMDR
        WHERE RMDR.CTL_PLVIA = PV.CTL_PLVIA
        AND RMDR.CTL_PTOPD = PV.CTL_DESTI
        AND RMDR.CTL_PARAD = 12
        AND RMDR.ORD_DESTI = (SELECT MAX(ORD_DESTI) FROM ROTEIRO_MOTORISTA WHERE CTL_PLVIA = PV.CTL_PLVIA AND CTL_PARAD = 12)
        AND RMDR.SIT_FASE_REA IN('R','T')) AS DHR_REAL_DESTINO,
        
        VCP.NOM_PESSO AS MOTORISTA, 
        VCP.SIG_TIPO_DOC AS TIPO_DOCUM,
        VCP.COD_DOCUM_PRI AS COD_DOCUM , 
        VCTVM.NOM_TIPO_VIC AS PERFIL,
        (SELECT NUM_DDD FROM V_CRP_TELEFONE_CONTATO_PESSOA WHERE CTL_PESSO = VCP.CTL_PESSO AND ROWNUM = 1)  AS DDD,
        (SELECT COD_TELEF FROM V_CRP_TELEFONE_CONTATO_PESSOA WHERE CTL_PESSO = VCP.CTL_PESSO AND ROWNUM = 1) AS TELEFONE,
        
        (SELECT COD_PLACA FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS PLACA_VEICULO,
                
        (SELECT IDP_V.COD_DISPO_RST FROM V_CRP_VEICULO VEI, 
                                  INF_VEICU_PLANO_VIAGEM VPVV_V,  
                                  INF_RELAC_VEICU_DISPO_PLANO IRVDP_V,
                                  INF_RELAC_VEICU_DISPO IRVD_V,
                                  INF_DISPOSITIVO IDP_V
                WHERE VPVV_V.CTL_PLVIA = PV.CTL_PLVIA 
                  AND VPVV_V.CTL_VEICU = VEI.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND IRVDP_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IRVDP_V.CTL_PLVIA = VPVV_V.CTL_PLVIA
                  AND IRVDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.STA_ATIVO = 'S'                  
                  AND ROWNUM = 1) AS DISPOSITIVO_VEICULO,
                  
        (SELECT VCPT_V.NOM_PESSO FROM V_CRP_VEICULO VEI, 
                                  INF_VEICU_PLANO_VIAGEM VPVV_V,  
                                  INF_RELAC_VEICU_DISPO_PLANO IRVDP_V,
                                  INF_RELAC_VEICU_DISPO IRVD_V,
                                  INF_DISPOSITIVO IDP_V,
                                  INF_RELAC_PROVE_RASTR_DISPO IRPRD_V,
                                  V_CRP_PROVEDOR_TECNOLOGIA VCPT_V

                WHERE VPVV_V.CTL_PLVIA = PV.CTL_PLVIA 
                  AND VPVV_V.CTL_VEICU = VEI.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND IRVDP_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IRVDP_V.CTL_PLVIA = VPVV_V.CTL_PLVIA
                  AND IRVDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRPRD_V.CTL_DISPO_RST = IDP_V.CTL_DISPO_RST
                  AND IRPRD_V.CTL_PROVE_TEN = VCPT_V.CTL_PROVE_TEN
                  AND IRVD_V.STA_ATIVO = 'S'                  
                  AND ROWNUM = 1) AS TECNOLOGIA_VEICULO,
                  
                  
        (SELECT VEI.NOM_MARCA_VEI FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS MARCA_VEICULO,
                  
        (SELECT VEI.NOM_MODEL_VEI FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS MODELO_VEICULO,
                  

        (SELECT VEI.NOM_TIPO_VEICU_INF FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS TIPO_VEICULO,
                  
        (SELECT VEI.ANO_FABRC FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS ANO_VEICULO,
                    
        (SELECT VEI.NUM_RENAV FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI <> 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS RENAVAM_VEICULO,



        (SELECT COD_PLACA FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS PLACA_CARRETA,
                
        (SELECT IDP_V.COD_DISPO_RST FROM V_CRP_VEICULO VEI, 
                                  INF_VEICU_PLANO_VIAGEM VPVV_V,  
                                  INF_RELAC_VEICU_DISPO_PLANO IRVDP_V,
                                  INF_RELAC_VEICU_DISPO IRVD_V,
                                  INF_DISPOSITIVO IDP_V
                WHERE VPVV_V.CTL_PLVIA = PV.CTL_PLVIA 
                  AND VPVV_V.CTL_VEICU = VEI.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND IRVDP_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IRVDP_V.CTL_PLVIA = VPVV_V.CTL_PLVIA
                  AND IRVDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.STA_ATIVO = 'S'                  
                  AND ROWNUM = 1) AS DISPOSITIVO_CARRETA,
                  
        (SELECT VCPT_V.NOM_PESSO FROM V_CRP_VEICULO VEI, 
                                  INF_VEICU_PLANO_VIAGEM VPVV_V,  
                                  INF_RELAC_VEICU_DISPO_PLANO IRVDP_V,
                                  INF_RELAC_VEICU_DISPO IRVD_V,
                                  INF_DISPOSITIVO IDP_V,
                                  INF_RELAC_PROVE_RASTR_DISPO IRPRD_V,
                                  V_CRP_PROVEDOR_TECNOLOGIA VCPT_V

                WHERE VPVV_V.CTL_PLVIA = PV.CTL_PLVIA 
                  AND VPVV_V.CTL_VEICU = VEI.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND IRVDP_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IRVDP_V.CTL_PLVIA = VPVV_V.CTL_PLVIA
                  AND IRVDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRVD_V.CTL_VEICU = VEI.CTL_VEICU
                  AND IDP_V.CTL_DISPO_RST = IRVD_V.CTL_DISPO_RST
                  AND IRPRD_V.CTL_DISPO_RST = IDP_V.CTL_DISPO_RST
                  AND IRPRD_V.CTL_PROVE_TEN = VCPT_V.CTL_PROVE_TEN
                  AND IRVD_V.STA_ATIVO = 'S'                  
                  AND ROWNUM = 1) AS TECNOLOGIA_CARRETA,
                  
                  
        (SELECT VEI.NOM_MARCA_VEI FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS MARCA_CARRETA,
                  
        (SELECT VEI.NOM_MODEL_VEI FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS MODELO_CARRETA,
                  

        (SELECT VEI.NOM_TIPO_VEICU_INF FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS TIPO_CARRETA,
                  
        (SELECT VEI.ANO_FABRC FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS ANO_CARRETA,
                    
        (SELECT VEI.NUM_RENAV FROM V_CRP_VEICULO VEI, INF_VEICU_PLANO_VIAGEM VPVV 
                WHERE VEI.CTL_VEICU = VPVV.CTL_VEICU
                  AND VEI.NUM_CATEG_VEI = 3
                  AND VPVV.CTL_PLVIA = PV.CTL_PLVIA 
                  AND ROWNUM = 1) AS RENAVAM_CARRETA

                   
       FROM 
        PLANO_VIAGEM PV,
        TIPO_OPERACAO TP,
        SITUACAO_PLANO_VIAGEM SPV,
        TIPO_OPERACAO_VIAGEM TOV,
        
        ENDERECO_VINCULADO EVO,
        PRACA PO,
        UNIDADE_FEDERAL UFO,
        
        ENDERECO_VINCULADO EVD,
        PRACA PD,
        UNIDADE_FEDERAL UFD,
        
        INF_MOTORISTA_PLANO_VIAGEM IMPV,
        V_CRP_PESSOA VCP,

        V_CRP_TIPO_VINCULO_MOTORISTA VCTVM
        
        
WHERE PV.SIT_PLVIA NOT IN(14,10)
  AND TP.CTL_OPERA_TIP = PV.CTL_OPERA_TIP
  AND SPV.SIT_PLVIA = PV.SIT_PLVIA
  AND TOV.TIP_OPERA_VIE = PV.TIP_OPERA_VIE
  AND EVO.CTL_VINCD = PV.CTL_REMET
  AND EVO.COD_PRACA = PO.COD_PRACA
  AND PO.COD_UNFED = UFO.COD_UNFED
  AND EVD.CTL_VINCD = PV.CTL_DESTI
  AND EVD.COD_PRACA = PD.COD_PRACA
  AND PD.COD_UNFED = UFD.COD_UNFED
  AND IMPV.CTL_PLVIA = PV.CTL_PLVIA
  AND IMPV.CTL_MOTOT = VCP.CTL_PESSO
  AND VCTVM.TIP_VINCU_MOT = IMPV.TIP_VINCU_MOT
  
  ORDER BY PV.DHR_INCLU, PV.CTL_PLVIA
  
  