/*RETORNA ROTA*/
  
  SELECT R.CTL_ROTA_GRI ID_ROTA, 
         O.CTL_OPERA_TIP AS ID_OPERACAO,
         O.DES_OPERA_TIP AS OPERACAO,
         R.NOM_ROTA AS NOME_ROTA,
         (SELECT COD_DOCUM FROM DOC_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_ORI) AS ORIGEM_DOCUM,
         FC_VINCULADO_NOM_GUERR(R.CTL_VINCD_ORI) AS ORIGEM,
         (SELECT NUM_LATIT FROM ENDERECO_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_ORI) AS ORIGEM_LATIT,
         (SELECT NUM_LONGI FROM ENDERECO_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_ORI) AS ORIGEM_LONGI,
         (SELECT COD_DOCUM FROM DOC_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_DES) AS DESTINO_DOCUM,
         FC_VINCULADO_NOM_GUERR(R.CTL_VINCD_DES) AS DESTINO,
         (SELECT NUM_LATIT FROM ENDERECO_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_DES) AS DESTINO_LATIT,
         (SELECT NUM_LONGI FROM ENDERECO_VINCULADO WHERE CTL_VINCD = R.CTL_VINCD_DES) AS DESTINO_LONGI,
         R.QTD_METRO_DTI,
         R.QTD_TEMPO_ROT,
         ' ' AS PASSANDO_POR_DOCUM,
         RR.DES_REFER AS PASSANDO_POR,
         RR.NUM_LATIT AS PASSANDO_POR_LATIT,
         RR.NUM_LONGI AS PASSANDO_POR_LONGI,
         RR.NUM_ORDEM_REF AS PASSANDO_POR_ORDEM
  FROM INF_ROTA R,
       TIPO_OPERACAO O,
       INF_ROTA_REFERENCIA RR
  WHERE O.CTL_OPERA_TIP = R.CTL_OPERA_TIP
  AND R.CTL_ROTA_GRI = RR.CTL_ROTA_GRI
  AND R.CTL_ROTA_GRI =3075173
  ORDER BY RR.CTL_REFER_ROT

