SELECT PV.CTL_PLVIA AS VIAGEM_INFOLOG, 
       TO_CHAR(PV.DHR_INCLU,'DD/MM/YYYY HH24:MI:SS') AS INCLUSAO_INFOLOG,
       SP.DES_SITUA AS SITUACAO_ATUAL_INFOLOG, 
       ASPK.STA_PLANO_KRONA AS STA_KRONA,
       to_char(ASPK.dhr_alter,'dd/mm/yyyy hh24:mi:ss') AS ALTERACAO_KRONA
FROM PLANO_VIAGEM PV, 
      SITUACAO_PLANO_VIAGEM SP, 
      INF_ALTERA_STATUS_PLANO_KRONA ASPK
WHERE 1=1
--AND PV.CTL_OPERA_TIP = 397
AND PV.SIT_PLVIA = SP.SIT_PLVIA
AND PV.CTL_PLVIA = ASPK.CTL_PLVIA
--AND PV.DHR_INCLU BETWEEN TO_DATE('01/11/2019 00:00:00','DD/MM/YYYY HH24:MI:SS') AND TO_DATE('18/11/2019 23:59:59','DD/MM/YYYY HH24:MI:SS')

ORDER BY PV.CTL_PLVIA, ASPK.DHR_ALTER