/*TOTAL DE VIAGENS INTEGRADAS*/
SELECT TP.DES_OPERA_TIP, COUNT(IRV.CTL_REQUI_VIE)
FROM INF_REQUISICAO_VIAGEM IRV
, TIPO_OPERACAO TP
WHERE IRV.DHR_ALTER BETWEEN TO_DATE('20190826000000','YYYYMMDDHH24MISS') AND TO_DATE('20190827235959','YYYYMMDDHH24MISS')
AND IRV.CTL_OPERA_TIP = TP.CTL_OPERA_TIP
GROUP BY TP.DES_OPERA_TIP
