DECLARE
  TIP_PROC CHAR(200);
  DDATA1 VARCHAR2(200);
  DDATA2 VARCHAR2(200);
BEGIN
  TIP_PROC := '4';
  DDATA1 := '20100101000000';
  DDATA2 := '20100131235959';

  SUPERVISOR.PR_INTEGRACAO_BRASKEM_HIST(
    TIP_PROC => TIP_PROC,
    DDATA1 => DDATA1,
    DDATA2 => DDATA2
  );
END;




SELECT DISTINCT P.CTL_PLVIA AS NUM_VIAGEM,
                   TRIM(RPD.COD_DOCUM_FIS) AS COD_DOCUM_FIS,
                   NVL(TO_CHAR(FC_DHR_INICIO_VIAGEM(P.CTL_PLVIA, 0), 'DD.MM.YYYY'), '') AS DAT_INICIO,
                   NVL(CASE WHEN R_TER.SIT_FASE_REA IN ('R','T') THEN TO_CHAR(R_TER.DHR_EFETI_REA, 'DD.MM.YYYY') ELSE NULL END, '00.00.0000') AS DATA_TERMN
            FROM PLANO_VIAGEM P, RELAC_PLVIA_DOCUMENTO RPD, ROTEIRO_MOTORISTA R_TER
            WHERE P.CTL_OPERA_TIP IN (11,228)
              AND RPD.tip_docum_fis = 7
              AND p.sit_plvia <> 10
              AND p.ctl_plvia = rpd.ctl_plvia
              AND TO_CHAR(P.DHR_INCLU, 'YYYYMMDDHH24MISS') BETWEEN '20100501000000' AND '20100531235959'
              AND P.CTL_PLVIA = R_TER.CTL_PLVIA
              AND R_TER.CTL_PARAD = 12
              AND R_TER.ORD_DESTI IN (SELECT MAX(ORD_DESTI) FROM ROTEIRO_MOTORISTA WHERE CTL_PLVIA = P.CTL_PLVIA)
              ORDER BY P.CTL_PLVIA
              
              

SELECT DISTINCT P.CTL_PLVIA AS NUM_VIAGEM,
       TRIM(RPD.COD_DOCUM_FIS) AS COD_DOCUM_FIS,
       NVL(TO_CHAR(FC_DHR_INICIO_VIAGEM(P.CTL_PLVIA, 0), 'DD.MM.YYYY'), '') AS DAT_INICIO,
--       NVL(CASE WHEN R_TER.SIT_FASE_REA IN ('R','T') THEN TO_CHAR(R_TER.DHR_EFETI_REA, '') ELSE NULL END, '00.00.0000') AS DATA_TERMN
        CASE WHEN R_TER.SIT_FASE_REA IN ('R','T') THEN TO_CHAR(R_TER.DHR_EFETI_REA, 'DD.MM.YYYY') ELSE NULL END AS DATA_TERMN
FROM PLANO_VIAGEM P, RELAC_PLVIA_DOCUMENTO RPD, ROTEIRO_MOTORISTA R_TER
WHERE P.CTL_OPERA_TIP IN (11,228)
      AND RPD.tip_docum_fis = 7
      AND p.sit_plvia <> 10
      AND p.ctl_plvia = rpd.ctl_plvia
      AND p.ctl_plvia = 2006595
      AND P.CTL_PLVIA = R_TER.CTL_PLVIA
      AND R_TER.CTL_PARAD = 12
      AND R_TER.ORD_DESTI IN (SELECT MAX(ORD_DESTI) FROM ROTEIRO_MOTORISTA WHERE CTL_PLVIA = P.CTL_PLVIA)
ORDER BY P.CTL_PLVIA              
              
 1902642             
              select sit_fase_rea, ctl_parad, dhr_efeti_rea, r.* from roteiro_motorista r
              where ctl_plvia = 2006595
              order by ord_desti
              
              SELECT MAX(ORD_DESTI) FROM ROTEIRO_MOTORISTA WHERE CTL_PLVIA = 2006595
              
'SELECT DISTINCT P.CTL_PLVIA AS NUM_VIAGEM,
                   TRIM(RPD.COD_DOCUM_FIS) AS COD_DOCUM_FIS,
                   NVL(TO_CHAR(FC_H_DHR_INICIO_VIAGEM(P.CTL_PLVIA), ''DD.MM.YYYY''), '''') AS DAT_INICIO,
                   NVL(CASE WHEN R_TER.SIT_FASE_REA IN (''R'',''T'') THEN TO_CHAR(R_TER.DHR_EFETI_REA, ''DD.MM.YYYY'') ELSE NULL END, '''') AS DATA_TERMN
            FROM HIST_PLANO_VIAGEM P, HIST_RELAC_PLVIA_DOCUM RPD, HIST_ROTEIRO_MOTORISTA R_TER
            WHERE P.CTL_OPERA_TIP IN (11,228)
              AND RPD.tip_docum_fis = 7
              AND p.sit_plvia <> 10
              AND p.ctl_plvia = rpd.ctl_plvia
              AND TO_CHAR(P.DHR_INCLU, ''YYYYMMDDHH24MISS'') BETWEEN :DT1 AND :DT2
              AND P.CTL_PLVIA = R_TER.CTL_PLVIA
              AND R_TER.CTL_PARAD = 12
              AND R_TER.ORD_DESTI IN (SELECT MAX(ORD_DESTI) FROM HIST_ROTEIRO_MOTORISTA WHERE CTL_PLVIA = P.CTL_PLVIA)
              ORDER BY P.CTL_PLVIA';
              